docker-compose.yml
frontend/.env.local.example
frontend/Dockerfile
frontend/__tests__/Software.test.jsx
frontend/components/layout/AppHeader.tsx
frontend/config/pagination.ts
frontend/package.json
frontend/pages/_app.tsx
frontend/pages/projects/[slug]/index.tsx
frontend/pages/projects/index.tsx
frontend/pages/software/[slug]/index.tsx
frontend/pages/software/index.tsx
frontend/pages/user/profile.tsx
frontend/styles/global.css
frontend/styles/themeConfig.js
frontend/tailwind.config.js
frontend/types/SoftwareItem.ts
frontend/utils/extractCountFromHeader.ts
frontend/utils/extractQueryParam.ts
frontend/utils/getProjects.ts
frontend/utils/getSoftware.ts
frontend/yarn.lock

Handles #52 
* Create local development and local production env files
* Connect software and project page to postgrest backend
* Upgrade tailwind css to new version (v3.0)
How to test:
* Copy `.env.local.example` to `.env.production.local`
* Start the solution `docker-compose up`
* Navigate to software page, you should see a list of software names similar to image below
* You can use navigation on the right, change number of items per page etc.
* On the projects page similar functionality is implemented

Connect frontend to backend

---

authentication/src/main/java/nl/esciencecenter/rsd/authentication/JwtCreator.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/JwtVerifier.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Main.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/SurfconextLogin.java

* The redirect url for SURFconext is now read from the env files instead of being hardcoded
* Fix accounts not being created because no rsd_admin token was sent to PostgREST
* Tokens are now sent as cookies
* Add endpoint to refresh tokens
How to test:
* Build the authentication service. 
* Start the database, backend and authentication services. 
* Go to http://localhost:7000/login/surfconext and follow the link. After signing in, you should see a JWT on the screen. The same JWT should be in a cookie with name "rsd_token". This cookie should have the Secure and HttpOnly values to true and the SameSite value to Lax. 
* Then go to http://localhost:7000/refresh. Your cookie should be replaced with a new one. The token should have the same content, …

Auth fix account creation

---

backend-postgrest/tests/README.md
backend-postgrest/tests/RSD-SaaS-auth.postman_collection.json
backend-postgrest/tests/docker-compose.yml
backend-postgrest/tests/dockerfile
data-migration/src/main/java/nl/esciencecenter/rsd/migration/Main.java
database/003-create-relations-for-software.sql
database/005-create-project-table.sql
database/006-create-relations-for-projects.sql
database/008-create-mention-table.sql
database/010-create-account-table.sql
database/011-create-organisation-table.sql
database/012-inter-relation-tables.sql
database/020-row-level-security.sql

* add organisation table
* add status for inter relationships: can either be requested by one side or approved by both sides
* some tests are added
* not related but needed: change flag `is_corporate_blog` to `is_featured` for mentions
How to test:
* build and run the tests, there should be no failures and 67 assertions
* you can make requests to /organisation, /software_for_organisation and /project_for_organisation
* data migration should still work
PR Checklist:
*   [x] Tests
closes #35

Organisation table

---

docker-compose.yml
frontend/components/layout/ImageAsBackground.tsx
frontend/components/layout/UserMenu.test.js
frontend/components/layout/UserMenu.tsx
frontend/components/software/MentionIsFeatured.tsx
frontend/components/software/MentionItem.tsx
frontend/components/software/MentionsByType.tsx
frontend/components/software/MentionsSection.test.js
frontend/components/software/MentionsSection.tsx
frontend/components/software/__mocks__/mentionSectionData.json
frontend/package.json
frontend/pages/software/[slug]/index.tsx
frontend/tailwind.config.js
frontend/types/MentionType.ts
frontend/utils/dateFn.test.js
frontend/utils/dateFn.ts
frontend/utils/getSoftware.ts
frontend/utils/sortFn.test.js
frontend/utils/sortFn.ts

*  Add mentions section to software item page. There are slight design differences compared to legacy version due to use of different component libraries. If needed, the design can be further improved.
How to test:
*  `docker-compose up`
*  visit one of the featured software items (they have more mentions), like Xenon: http://localhost/software/xenon. At the bottom of the page you should see mentions section with one 'featured' item and number of other mentions per type.
* Click on feature item will open new web page
The software item page with the mention section should look something like in the picture below.

Software item mentions section

---

authentication/src/main/java/nl/esciencecenter/rsd/authentication/Main.java
backend-postgrest/tests/RSD-SaaS-auth.postman_collection.json
backend-postgrest/tests/docker-compose.yml
data-migration/docker-compose.yml
data-migration/src/main/java/nl/esciencecenter/rsd/migration/Main.java
database/002-create-software-table.sql
database/003-create-relations-for-software.sql
database/005-create-project-table.sql
database/006-create-relations-for-projects.sql
database/011-create-organisation-table.sql
docker-compose.yml
nginx/nginx.conf

Fixes #
* An extra location is added to the NGINX config that adds the necessary header to get images so they can be requested normally by browsers
* Extra functions added to the database that provides the correct mime type for images
* Testimonials table and data-migration
* Small database improvements, including slug for organisations
How to test:
* Build and start
* Tests should still succeed
* Data migration should still succeed
* http://localhost/api/v1/software?slug=eq.ggir&select=*,testimonial(*) should show two testimonials
* http://localhost/api/v1/testimonial should show content
* http://localhost/image/rpc/get_project_image?id=valid-uuid should show an image, saving it should suggest as filename the slug of the project
* …

Testimonials images database

---

docker-compose.yml
frontend/components/software/ContactPersonCard.tsx
frontend/components/software/ContributorsList.tsx
frontend/components/software/ContributorsSection.tsx
frontend/components/software/MentionItem.tsx
frontend/components/software/TestimonialItem.tsx
frontend/components/software/TestimonialsSection.tsx
frontend/config/app.ts
frontend/package.json
frontend/pages/index.tsx
frontend/pages/software/[slug]/index.tsx
frontend/pages/software/index.tsx
frontend/types/Contributor.ts
frontend/types/Testimonial.ts
frontend/utils/getDisplayName.ts
frontend/utils/getSoftware.ts

In this PR I created all components for contributors and testimonials. There are slight improvements (imho) compared to legacy version.
* Contributors
* All contributor have avatar
* If no image provided contributor initials are shown the avatar area
* Testimonials: all testimonials are listed. In the legacy version only first/top testimonial was shown 
How to test:
* `docker compose up`
* visit software page, example: http://localhost/software/xenon
New contributor section should look like screenshot below
Testimonial section for [GGIR](http://localhost/software/ggir) has 2 entries now

Software contributors and testimonials

---

docker-compose.yml
frontend/Dockerfile
frontend/components/software/AboutSection.tsx
frontend/components/software/CitationSection.tsx
frontend/components/software/RelatedToolsSection.tsx
frontend/components/software/SoftwareCard.tsx
frontend/package.json
frontend/pages/software/[slug]/index.tsx
frontend/types/SoftwareItem.ts
frontend/utils/dateFn.ts
frontend/utils/getSoftware.ts

Closes #60 
* Related tools section is added. This is final section 
* Minor improvements in page layout
* Minor refactor of SoftwareItemCard to be reused on this page too
* Improved caching in frontend dockerfile
How to test:
* visit the software without related tool section, like [GGIR](http://localhost/software/ggir), the section will not be visible
* visit an software page with related tool section, like [Xenon](http://localhost/software/xenon), the section should be visible and similair to picture below

Related tools section - Software page

---

docker-compose.yml
frontend/components/software/CitationDownload.tsx
frontend/components/software/ContributorsSection.tsx
frontend/components/software/citationFormats.ts
frontend/next.config.js
frontend/package.json
frontend/pages/api/fe/cite/[id].ts

Fixes #85 
* Downloaded citation files follow the naming convention implemented in legacy RSD
How to test:
* `docker compose up` to start app
* navigate to software, for example [Xenon](http://localhost/software/xenon)
* select software version you want to cite
* select citation format
* click on `download file` button
* the file name should follow convention specified in #85 
- BibTex: {slug}.bib
- EndNote: {slug}.enw
- RIS: {slug}.ris
- CodeMeta: codemeta.json
- CIFF: CITATION.ciff (name in capitals)
- citation files should contain "proper" content (but that might be more difficult to confirm)
PR Checklist:

Software citation download

---

docker-compose.yml
frontend/components/layout/AppFooter.tsx
frontend/components/layout/UserMenu.tsx
frontend/components/seo/CanonicalUrl.tsx
frontend/components/seo/CitationMeta.tsx
frontend/components/seo/OgMetaTags.tsx
frontend/components/seo/PageMeta.tsx
frontend/components/software/MentionIsFeatured.tsx
frontend/components/software/MentionItem.tsx
frontend/package.json
frontend/pages/software/[slug]/index.tsx
frontend/utils/getSoftware.ts

Closes #95 
* Added meta tags according to task #95 
* Did few more SEO improvements based on Lighthouse feedback
How to test:
*  If you already runned the data-migration and have software entries in the database:
*  `docker-compose up`
* Visit software page, for example GGIR
* Open debugger (F12)
* Inspect Head of the page and confirm that meta tags are present
PR Checklist:
*   [x ] Link to a GitHub issue

Software page meta

---

database/013-software-scraped-data.sql
database/020-row-level-security.sql
docker-compose.yml
frontend/.env.local.example
scrapers/dockerfile
scrapers/jobs.cron
scrapers/pom.xml
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/Config.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/Utils.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/language/FilterUrlOnlyPLRDecorator.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/language/GithubPL.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/language/Main.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/language/OrderByDatePLRDecorator.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/language/PostgrestPLR.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/language/ProgrammingLanguages.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/language/ProgrammingLanguagesRepository.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/language/RepositoryUrlData.java

* Add a scraper that scrapes the GitHub API to collect the programming languages used in repositories. It runs a cron job in a Docker container that runs every 6 minutes. The amount of requests is makes is configurable and it supports using a GitHub authentication token to increase the rate limit. 
How to test:
Since the database structure has changed, we have to delete and build everything
* Copy the new version of the file `frontend/.env.local.example` to `frontend/.env.production.local`
* Optionally fill in the new values
* Dont't forget to fill in the existing secrets again
* Every six minutes, you should see that the amount of data on …

feat: programming languages GitHub scraper

---

database/003-create-relations-for-software.sql
scrapers/jobs.cron
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/AggregateContributionsPerWeekSIDecorator.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/FilterUrlOnlySIRDecorator.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/GithubSI.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/LicenseData.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/MainCommits.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/MainLicenses.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/MainProgrammingLanguages.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/OrderByDateSIRDecorator.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/PostgrestSIR.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/ProgrammingLanguageData.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/RepositoryUrlData.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/SoftwareInfo.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/SoftwareInfoRepository.java

* Add a commit history scraper, which scrapes the full commit history, e.g. from https://api.github.com/repos/research-software-directory/RSD-as-a-service/stats/contributors, and saves the data as a single JSON string aggregated per week
How to test:
* The database structure has changed, so we need to rebuild everything:
* Run the data migration script
* At 4, 10, 16, etc. minutes past the hour the commit history scraper should run and print two lines to the console
* Check https://localhost/api/v1/repository_url to see that data is indeed scraped and saved
* (The existing programming languages scraper should run at 0, 6, 12, etc. minutes past the hour)
* (The existing …

Commit activity scraper

---

database/002-create-software-table.sql
database/009-create-release-table.sql
frontend/.env.local.example
scrapers/dockerfile
scrapers/jobs.cron
scrapers/src/main/resources/releases.py
scrapers/src/main/resources/requirements.txt

* Add a releases script that scrapes citation info from Zenodo and GitHub, adapted from the legacy RSD script
How to test:
* This change affects the database structure, so we need to rebuild everything:
* Copy the new lines from `frontend/.env.production.local` to `frontend/.env.local.example` and provide a value for `ZENODO_ACCESS_TOKEN`
* At minutes 7, 13, 19 etc. the releases script should run. It should print some messages and should end with a done message.  
PR Checklist:
*   [ ] Tests
closes #136

Zenodo releases scraper

---

frontend/components/layout/ImageAsBackground.tsx
frontend/components/software/OrganisationsSection.tsx
frontend/components/software/ParticipatingOrganisation.tsx
frontend/components/software/edit/organisations/index.tsx
frontend/pages/software/[slug]/index.tsx
frontend/types/Organisation.ts
frontend/utils/editOrganisation.ts

Closes #88 
*     Show participating organisations on the software page
How to test:
* `docker-compose down --volumes`: remove old database
* `docker-compose build`: build new solution
* `docker-compose up`: start solution
*  Login to RSD as professor1
*  Create new software
*  Navigate to organisation section and add organisations
*  Upload logos for some organisation, so you have some organisation with logo and some without the logo
*  View software page, you should see organisations listed. Each organisation has a link to their website that opens in separate tab
*  Logout, you should still be able to see organisations and logos on the software page
**The organisations without logo are represented with an suqare containing first 3 letters and …

Participating organisations

---

.github/workflows/fair_software.yml

Fixes #N/A
* Bumped patch version of https://github.com/marketplace/actions/fair-software
How to test:
* before merging use the workflow dispatch trigger to start the fair-software workflow. It should fail with a "gcc can't be found" type of error. This error has been fixed in 0.2.1 of said github action. Not sure if you get the option to run the updated workflow via its `workflow_dispatch`, but if not, just merge and check afterwards; roll back if needed.
PR Checklist:
*   [ ] Link to a GitHub issue _nope_
*   [ ] Update documentation _nope_
*   [ ] Tests _nope_

Updated howfairis github action to 0.2.1

---

database/100-create-api-views.sql
docker-compose.yml
frontend/README.md
frontend/components/form/Searchbox.tsx
frontend/components/layout/ImageAsBackground.tsx
frontend/components/organisation/OrganisationCard.tsx
frontend/components/organisation/OrganisationGrid.tsx
frontend/config/menuItems.ts
frontend/pages/logout.tsx
frontend/pages/organisation/[slug]/index.tsx
frontend/pages/organisation/index.tsx
frontend/pages/software/index.tsx
frontend/pages/user/profile.tsx
frontend/pages/user/software.tsx
frontend/types/Organisation.ts
frontend/utils/editOrganisation.ts
frontend/utils/getOrganisations.ts
frontend/utils/getPropsFromObject.ts
frontend/utils/postgrestUrl.ts
frontend/utils/useParticipatingOrganisations.ts

Closes #160
* The organisations present in RSD are shown in an overview with the number of software packages registered in RSD      
* The overview is visible to all visitors (you do not have to be logged in)
* The organisation card shows name, logo and software packages count
* Clicking on the organisation redirects to organisation page. **The organisation page shows very simple "under construction" message at the moment**
How to test:
* `docker-compose down --volumes`: to remove old data and database structure
* `docker-compose build` to build all services
* `docker-compose up` to start the instance
*  data-migration is not required
*  Navigate to organisation page in the menu on the top. The overview will be empty at the moment
*  Login to RSD, in …

160 organisations overview

---

data-migration/docker-compose.yml
data-migration/src/main/java/nl/esciencecenter/rsd/migration/Main.java
database/011-create-organisation-table.sql
database/100-create-api-views.sql
docker-compose.yml
frontend/utils/getOrganisations.ts

* Organisations are migrated from the legacy RSD to the SaaS version
* The script makes a relation between all software and projects to the eScience Center
* Small bugfix for a view so that logo ids are also returned for organisations without software packages
How to test:
* This change affects the database structure, so we need to rebuild everything:
* Go to the `data-migration` directory
* Build and run the migration script: `docker compose build && docker-compose up`
* At http://localhost/organisation you should see an overview of all organisations and their software package count
* Every software page you see should have in the "Participating organisations" section …

Migrate organisations

---

database/011-create-organisation-table.sql

* Organisations can now have one parent organisation
* Function for listing all parents and slugs of an organisation
* Function for mapping a full slug into an organisation id
How to test:
* This change affects the database structure, so we need to rebuild everything. We only need the database container:
* `docker-compose build database`
* `docker-compose up databasse`
* Run the following queries one by one and observe if the results match with what you expect:
```sql
INSERT INTO organisation VALUES
(NULL, 'parent', NULL, NULL, 'Parent organisation', NULL, NULL, FALSE, NULL, NULL);
INSERT INTO organisation VALUES
(NULL, 'child1', (SELECT id FROM organisation WHERE slug = 'parent'), NULL, 'Child 1 organisation', NULL, …
```

Organisation parent child structure

---

database/Dockerfile

Fixes #178 
* move file ownership for db initialization scripts to user `postgres` and group `postgres`
How to test:
* Clean-up first:  `docker-compose down -v` 
* Build database image:  `docker-compose build database`
* Start database container: `docker-compose up database`
PR Checklist:
*   [ ] Tests

Fix missing permissions for db initialization scripts

---

data-migration/docker-compose.yml
data-migration/src/main/java/nl/esciencecenter/rsd/migration/Main.java
database/005-create-project-table.sql
docker-compose.yml
frontend/utils/dateFn.ts

* Adapt the migration script so that empty images for projects from the legacy RSD are not saved in the database when migrating. These images were not stored as `null` but as empty strings instead in the legacy RSD database.
* Enforce in the database that image data and mime types are not null.
How to test:
* The database structure has changed:
* `docker-compose build database`
* `docker-compose up database`
* Build and run the new migration script:
* `cd data-migration && docker-compose build && docker-compose up`
* The following query should return zero rows:
* `SELECT * FROM image_for_project WHERE LENGTH(data) = 0 OR LENGTH(mime_type) = 0;`
Closes #188
PR Checklist:
*   [ ] Update …

188 no empty project images migration

---

authentication/src/main/java/nl/esciencecenter/rsd/authentication/Account.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/AccountInfo.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/JwtCreator.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Login.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Main.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/OpenIdInfo.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/PostgrestAccount.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/SurfconextLogin.java
docker-compose.yml

* Refactor the authentication module so that it is easier to add Helmholtz AAI and other OpenID providers
* A separate class for communicating with the PostgREST API that is independent of the OpenID provider
* Record classes for transferring data without assumptions on the underlying protocols or OpenID processes
* Provide the name in the RSD token (that is transferred in a cookie when logging in successfully)
How to test:
* Rebuild the authentication module:
* `docker-compose build auth`
* `docker-compose up --scale scrapers=0`
* Login, this should be successful
* Inspect the cookie called `rsd_token`, verify that the JWT token has a `name` claim
PR Checklist:
*   [ ] Tests

Helmholtz login preparation

---

docker-compose.yml
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/Utils.java
scrapers/src/main/resources/releases.py
scrapers/src/main/resources/zotero.py

* Scrapers don't generate errors if optional env variables are missing
How to test:
* From your `.env` file, comment out the variables `API_CREDENTIALS_GITHUB` and `MAX_REQUESTS_GITHUB`
* Rebuild the scraper module:
* `docker-compose build scrapers`
* Wait at least 6 minutes so that all scrapers have run at least once. 
* There should be no errors that have anything to do with the missing env variables
Closes #198
PR Checklist:
*   [ ] Tests

198 fix missing optional env variables create errors

---

database/002-create-software-table.sql
database/003-create-relations-for-software.sql
database/004-create-tags-for-software.sql
database/005-create-project-table.sql
database/006-create-relations-for-projects.sql
database/007-create-topics-for-projects.sql
database/008-create-mention-table.sql
database/009-create-release-table.sql
database/010-create-account-table.sql
database/011-create-organisation-table.sql
database/012-inter-relation-tables.sql
database/020-row-level-security.sql
docker-compose.yml

* Enforce slug rules in the database:
* Only lower case letters, digits and dashes
* Not two dashes in a row, starting or ending with a dash
* Add a trigger that prevents an organisation to become an (in)direct parent of itself
How to test:
* Rebuild the database module:
* `docker-compose down --volumes && docker-compose build database && docker-compose up database`
* Execute the following statements to test the slug rules:
```sql
-- the following should be correct
INSERT INTO software (slug, brand_name) VALUES ('abc', 'my sw');
INSERT INTO software (slug, brand_name) VALUES ('1234567890asdfghjkl', 'my sw');
INSERT INTO software (slug, brand_name) VALUES ('ab-c', 'my sw');
INSERT INTO software (slug, brand_name) VALUES ('a-bc', 'my sw');
INSERT INTO …
```

Database improvements

---

docker-compose.yml
frontend/__tests__/OrganisationsIndex.test.tsx
frontend/__tests__/ProjectItem.test.tsx
frontend/__tests__/ProjectsIndex.test.tsx
frontend/__tests__/SoftwareIndex.test.tsx
frontend/__tests__/SoftwareItem.test.tsx
frontend/auth/ProtectedContent.test.tsx
frontend/components/layout/AppFooter.tsx
frontend/components/layout/AppHeader.tsx
frontend/components/layout/DarkThemeSection.tsx
frontend/components/layout/UserMenu.test.tsx
frontend/components/software/CitationSection.test.tsx
frontend/components/software/MentionsByType.tsx
frontend/components/software/MentionsSection.test.tsx
frontend/components/software/MentionsSection.tsx
frontend/components/software/add/AddSoftwareCard.test.tsx
frontend/config/menuItems.ts
frontend/package.json
frontend/pages/_app.tsx
frontend/pages/_document.tsx
frontend/pages/index.tsx
frontend/pages/projects/[slug]/index.tsx
frontend/styles/README.md
frontend/styles/rsdMuiTheme.ts
frontend/styles/themeConfig.js
frontend/styles/themeDark.js
frontend/styles/themeDefault.js
frontend/tailwind.config.js
frontend/utils/jest/WrappedComponents.tsx
frontend/utils/postgrestUrl.ts

Closes #214 
Closes #218
Closes #62
* The mentions section on software and project page uses secondary theme color. Previously the color was hard coded
* The change required refactoring on mui theme loading and updating of existing tests
* The Organization title in the header is changed to Organisation to be in line with other titles and labels currently used in RSD
How to test:
* `docker-compose down --volumes`: remove old instances
* `docker-compose build`: build solution (you could also build only frontend if you have most recent db structure)
* `docker-compose up`: start solution
* run data migration: cd data-migration && docker-compose up
* navigate to xenon software page with mentions, the mention section should look like this
* navigate to …

#214 Fix mentions components

---

.env.example
database/100-create-api-views.sql
docker-compose.yml
frontend/components/form/ControlledAffiliation.tsx
frontend/components/keyword/FindKeyword.test.tsx
frontend/components/projects/edit/editProjectSteps.tsx
frontend/components/projects/edit/team/FindMember.tsx
frontend/components/projects/edit/team/TeamMemberList.tsx
frontend/components/projects/edit/team/TeamMemberModal.tsx
frontend/components/projects/edit/team/config.ts
frontend/components/projects/edit/team/editTeamMembers.ts
frontend/components/projects/edit/team/index.tsx
frontend/components/projects/edit/team/searchForMember.ts
frontend/components/software/ContributorsList.tsx
frontend/components/software/SoftwareCard.tsx
frontend/components/software/edit/contributors/EditContributorModal.tsx
frontend/components/software/edit/contributors/FindContributor.tsx
frontend/components/software/edit/contributors/FindContributorItem.tsx
frontend/components/software/edit/contributors/SoftwareContributorsList.tsx
frontend/components/software/edit/contributors/index.tsx
frontend/components/software/edit/editSoftwareConfig.ts
frontend/components/software/edit/editSoftwareSteps.tsx
frontend/components/software/edit/information/index.tsx
frontend/package.json
frontend/types/Contributor.ts
frontend/types/Project.ts
frontend/utils/editContributors.ts
frontend/utils/getDisplayName.ts
frontend/utils/getORCID.ts
frontend/utils/getProjects.ts

Closes #252
Closes #164
* Project maintainer add/edit/delete team members using find/add options
* We search in RSD and ORCID database
* If person extracted from ORCID has more than one affiliation we show them in drop-down. User still can type in completely different affiliation. Same solution is implemented the edit contributors modal.
How to test:
* `docker-compose down --volumes`: remove old
* `docker-compose build`: to build solution
* `docker-compose up`: to start
* data-migration is optional
* login using any of test users, eg. professor1
* create new project
* add team members using search on the right side of the screen, the section should look like in the example below
* when using information from ORCID, which might provide multiple …

252 edit project team

---

database/015-create-maintainer-tables.sql
database/020-row-level-security.sql
database/100-create-api-views.sql
docker-compose.yml
frontend/auth/api/authHelpers.ts
frontend/components/projects/edit/maintainers/ProjectMaintainerLink.tsx
frontend/components/software/edit/editSoftwareContext.tsx
frontend/components/software/edit/editSoftwareSteps.tsx
frontend/components/software/edit/maintainers/SoftwareMaintainerLink.tsx
frontend/components/software/edit/maintainers/index.tsx
frontend/components/software/edit/maintainers/useSoftwareMaintainer.tsx
frontend/components/software/edit/useSoftwareContext.tsx
frontend/package.json
frontend/pages/invite/software/[id].tsx
frontend/utils/fetchHelpers.ts

Fixes #258 
*   Software maintainer is able to create maintainer invite link for inviting additional maintainers 
How to test:
* `docker-compose down --volumes`: remove old instance and data
* `docker-compose build`: build all services
* `docker-compose up`: start new RSD
*  login to RSD using any account (eg. professor1)
*  create new software
*  in section maintainers create an maintainer invite link
*  try link, you will get message that you are maintainer
*  logout, try link again...you should see message that you need to sign in
*  logout using different test account (eg. professor2), you should see message
*  try link again, you should receive message that invitation 'expired'
*  open software and confirm in maintainer section that there are 2 …

258 edit software maintainers

---

docker-compose.yml
scrapers/src/main/resources/releases.py

* When the releases scraper found a syntax error in a single CITATION.cff file, it would skip all the releases of that software. Now it will print a message and continue with the next file.
How to test:
* Rebuild the project, it is the easiest to start with an empty database
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up`
* Create two software entries with the folling concept DOIs: 10.5281/zenodo.4592360 and 10.5281/zenodo.4818029
* Run the releases scraper: `docker-compose exec scrapers python3 releases.py`
* You should see error messages, but the scraper still reaches the end (it prints 1/2 and 2/2)
Closes #225
PR Checklist:
*   [x] Link to a GitHub …

225 improve releases scraper

---

data-migration/docker-compose.yml
data-migration/src/main/java/nl/esciencecenter/rsd/migration/Main.java

* The data migration script does a few simple checks to see if the code platform of a repo url is from GitHub, GitLab, Bitbucket or something else
How to test:
* Start with an empty database:
* `docker-compose down --volumes && docker-compose up --scale scrapers=0`
* Build and run data migration:
* `cd data-migration && docker-compose build && docker-compose up`
* Run the following query and check that the results are correct (there is only one row to check at the time of writing, which is a GitLab repo):
`SELECT * FROM repository_url WHERE url NOT ILIKE '%github%';`
* Also check that the rest is indeed GitHub:
`SELECT * FROM repository_url WHERE url ILIKE '%github%';`
Closes #270
PR Checklist: …

270 correct platform type migration

---

.env.example
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Config.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Main.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/PostgrestAccount.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Utils.java
database/010-create-account-table.sql
docker-compose.yml
frontend/auth/locationCookie.ts
frontend/components/login/LoginButton.tsx
frontend/next.config.js
frontend/pages/api/fe/auth/index.ts
frontend/pages/api/fe/auth/local.ts
frontend/pages/login/local.tsx

* Allow for local account creation when the value `LOCAL` is part of env variable `RSD_AUTH_PROVIDERS`
* These account are *not secure* and should be used for testing purposes only
* On the auth module, the endpoints are now disabled if the corresponding values are not a part of `RSD_AUTH_PROVIDERS`; in the case of a missing `RSD_AUTH_PROVIDERS`, SURFconext is enabled
How to test:
* Add `LOCAL` to the env variable `RSD_AUTH_PROVIDERS` (see also the new `.env.example`)
* Build and run
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --scale scrapers=0`
* Click on Sign in
* Click on Local account
* Fill in a username of your choice
* After some redirects, you should now be logged in
Closes #264
PR Checklist:
* …

264 simple test login

---

database/002-create-software-table.sql
database/009-create-release-table.sql
docker-compose.yml
scrapers/src/main/resources/releases.py

* Move the column `releases_scraped_at` from `software` to `release`
* Create a function in the database that allows (again) for sorting on `releases_scraped_at`
* The `releases_scraped_at` is updated first, so that even if an error occurs later, the entry is pushed back to the end of the scraping order
* A fix that sets `is_citable` and `latest_schema_dot_org` for the corresponding entry only instead of all entries
* Set `NULL` instead of the empty string for `latest_schema_dot_org` when it is missing
How to test:
* The database structure has changed, clear and build:
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up`
* Run data migration
* Scraping releases should work, you can speed it up by running …

271 fix scraping releases

---

Makefile
README.md
documentation/docs/.vuepress/config.js
frontend/components/layout/AppFooter.tsx

* Adding a Makefile with basic commands tha install, build and execute data migration in one go: make install
* Run development server with one command: made dev      
How to test:
* delete all docker images and volumes and run `make install` from the route
PR Checklist:
*   [ ] Tests

add makefile to ease the install, build process and run services in development mode

---

database/015-create-maintainer-tables.sql
database/100-create-api-views.sql
frontend/auth/api/authHelpers.ts
frontend/components/organisation/maintainers/OrganisationMaintainerLink.tsx
frontend/components/organisation/maintainers/OrganisationMaintainersList.tsx
frontend/components/organisation/maintainers/index.tsx
frontend/components/organisation/maintainers/useOrganisationMaintainer.tsx
frontend/pages/invite/organisation/[id].tsx

Closes #305
*  Maintainer of an organisation can invite others to become maintainers
*  Maintainer can remove other maintainers EXCEPT primary_maintainer (delete button is disabled on primary maintainer)    
How to test:
* `docker-compose down --volumes`: to remove old db
* `docker-compose build` to build 
*  login as professor1
*  create new software/project
*  add new organisation to RSD, for example `New Zealand eScience Infrastructure` in order to become primary maintainer of that organisation
* View software page, click on the organisation to go to organisation page
* You should see maintainer section
* Click on generate invite link button
* Click on send email invite, provide your second email address where invite …

305: Organisation maintainers management

---

CONTRIBUTING.md

Fixes #320
* Added a check that will detect merge commits and abort the pre-commit
hook.
How to test:
* create `.git/hooks/pre-commit` as described in `CONTRIBUTING.md`
* optionally, after line 33 of the pre-commit script, you may add an `echo "Aborting pre-commit hook"` to see the terminal output:
```bash
merge_check=$(git rev-parse -q --verify MERGE_HEAD)
if [[ ${merge_check} ]]; then
echo "Aborting pre-commit hook"
exit 0
fi
```
* to test we need to create a merge conflict, e.g. 
* From the `320-fix_pre-commit_merges` branch, create a new branch and make some additions
```bash
git checkout -b 320_TEST
echo "Some string" >> CONTRIBUTING.md
git add CONTRIBUTING.md
git commit -n -m "320_TEST additions"
```
* Now switch back and add a conflict
```bash …
```

Fixes: pre-commit hook alters files in merge-commit

---

authentication/Dockerfile
data-migration/Dockerfile
data-migration/docker-compose.yml
docker-compose.yml
scrapers/Dockerfile
scrapers/jobs.cron
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/PostgrestMentionRepository.java

* Upgrade OpenJDK images to fix the security bug as described in #235
* Small fix to mentions scraper to correctly deserialize timestamps
How to test:
* Build and test that eveything still works, especially the authentication module, the scrapers and the data-migration script, as those are the only modules that use Java
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --detach && cd data-migration && docker-compose build && docker-compose up`
* You can speed up the scrapers with the following commands repsectively:
* `docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.doi.MainProgrammingLanguages`
* `docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar …

235 upgrade openjdk

---

.env.example
CONTRIBUTING.md
backend-postgrest/tests/docker-compose.yml
database/000-fill-authenticator-password.sh
database/001-setup-basic-roles.sql
database/Dockerfile
docker-compose.yml

* The PostgREST backend uses the authenticator role instead of the superuser role to connect to the database
* The authenticator password is set in an env variable now instead of being hardcoded 
* Fix `reusee` typo in pre-commit hook
* When the organisation is set in the pre-commit hook, use it in the copyright line of the author
How to test:
* Copy the new `.env.example` to `.env` (or just the lines with `POSTGRES_AUTHENTICATOR_PASSWORD`) and set a value for `POSTGRES_AUTHENTICATOR_PASSWORD`
* Build and test that eveything still works: 
* `docker-compose down --volumes && docker-compose build database backend && docker-compose up database backend`
* The backend should successfully connect to the database
Closes #329
PR Checklist:
*   [x] Increase …

329 authenticator role

---

docker-compose.yml
frontend/components/form/ControlledTextField.tsx
frontend/components/layout/FlexibleGridSection.tsx
frontend/components/layout/NoContent.tsx
frontend/components/organisation/OrganisationGrid.tsx
frontend/components/organisation/project/index.tsx
frontend/components/organisation/settings/OrganisationLogo.tsx
frontend/components/organisation/software/index.tsx
frontend/components/organisation/units/ResearchUnitModal.tsx
frontend/components/projects/ProjectsGrid.tsx
frontend/components/projects/edit/information/ProjectImage.tsx
frontend/components/projects/edit/team/TeamMemberModal.tsx
frontend/components/software/ContributorsList.tsx
frontend/components/software/PersonalInfo.tsx
frontend/components/software/SoftwareGrid.tsx
frontend/components/software/edit/contributors/EditContributorModal.tsx
frontend/components/software/edit/information/ValidateConceptDoi.tsx
frontend/components/software/edit/organisations/EditOrganisationModal.tsx
frontend/package.json
frontend/pages/projects/[slug]/index.tsx
frontend/pages/software/[slug]/index.tsx
frontend/utils/fetchHelpers.ts
frontend/utils/getDataCite.ts

Closes #288
Closes #337 
* When there are no results/items to be returned we show "no content" message
* Developer can use this component and pass custom message, the default message is "nothing to show"
* Uploading image on project page, has in message < 2MB notification
* If user tries to upload large image the warning is shown that will disappear after 5 sec. or so 
How to test:
* `docker-compose build`: to build frontend
* navigate to software or project page. If there is content (items to show), use search to modify term until no results is shown (see example image)
* create new project, try to upload image larger than 2MB, the warning will be shown
PR Checklist:
*   [x] Increase version numbers in …

288 & 337: Nothing to show/no content (animated) message and warning on large file upload

---

Makefile
README.md

Fixes #333
* Add a single command to run the application locally withput other dependencies rather than docker-compose
How to test:
* run `make start` you your terminal, after the build process and database migrations you will be able to see the application running on `http://localhost/`
PR Checklist:
*   [ ] Tests

make start command

---

database/100-create-api-views.sql
frontend/components/home/getHomepageCounts.ts
frontend/pages/index.tsx
frontend/utils/getOrganisations.ts

Closes #238 
*   The counters on home page load the counts from api using SSR
How to test:
* `docker-compose down --volumes`: to remove
* `docker-compose build`: to build all
* `docker-compose up`: to start
*  perform data migration
*  visit homepage you should have these counts*
PR Checklist:
*   [ ] Tests

238 counters homepage

---

database/100-create-api-views.sql
docker-compose.yml
frontend/auth/permissions/isMaintainerOfOrganisation.ts
frontend/components/organisation/project/index.tsx
frontend/components/organisation/software/index.tsx
frontend/components/organisation/units/index.tsx
frontend/components/software/edit/information/SoftwareLicenses.tsx
frontend/components/user/organisations/index.tsx
frontend/components/user/software/index.tsx
frontend/package.json
frontend/pages/projects/index.tsx
frontend/pages/software/index.tsx
frontend/utils/editOrganisation.ts
frontend/utils/editRelatedSoftware.ts
frontend/utils/getOrganisations.ts
frontend/utils/getProjects.ts
frontend/utils/getSoftware.ts
frontend/utils/useOrganisationProjects.tsx
frontend/utils/useOrganisationSoftware.tsx

Consolidate project and software counts on all pages for different types of users: public, logged in user and maintainer of organisation.
Fixes #346
* The software and project counts on home page, software, projects and in the organisation card should be identical. These include only published and approved software and projects.
* When user is maintainer of an organisation, the count in the organisation card remains identical to what other users see (count of published and approved items only). The counts on the organisation page, in the menu on the left and in the pagination component at the top, are different and represent count of all items linked to the organisation (including access denied and not published items).
* On the user specific page, …

346 improve counts on project, software and organisation pages

---

Makefile
README.md

Here is a minor suggestion to improve the `Makefile` by @ctwhome:
* Use the `Makefile` to auto-generate the file `frontend/.env.local` from `.env`
* Uses `sed` to replace `POSTGREST_URL`
How to test:
* delete (or make a backup) of your `frontend/.env.local`
* `make dev-frontend`
* Should now tell you that it creates `frontend/.env.local` and then starts `yarn dev`
* shutdown the dev server
* `make dev-frontend`
* starts the server without recreating `.env.local`
* shutdown the dev server again
* edit the `.env`, e.g. `echo "# just a comment" >> .env`
* `make dev-frontend` should detect the change and regenerate `.env.local`
* shutdown the dev server one more time
* edit the `.env.local`, e.g. `echo "# another comment" >> frontend/.env.local`
* `make dev-frontend` should start the dev …

minor: auto-create .env.local

---

frontend/components/form/Searchbox.tsx

Fixes #378 
*   When using enter the search request will be issued with the proper value instead of the object.   
How to test:
* `docker-compose build frontend` to build frontend
*  type value in searchbox and use enter key. It should work. You can validate search term in the url `search=res&page=0&rows=12`
PR Checklist:
*   [ ] Tests

fix:pass search value when enter key is pressed.

---

docker-compose.yml
frontend/components/software/PersonalInfo.tsx

* Show ORCID of present, even if role or affiliation is missing
How to test:
* Build and add software and a contributor with any combination of role, affiliation and ORCID. Any of those three fields present should be shown.
Closes #381
PR Checklist:
*   [ ] Tests

381 missing orcid

---

docker-compose.yml
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/MainCommits.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/MainLicenses.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/MainProgrammingLanguages.java

* When scraping from GitHub or GitLab fails, still update the `*_scraped_at` so that it will be pushed back in the scraping order
How to test:
* `docker-compose build scrapers && docker-compose up`
* Add two software packages, both with repository url https://www.example.com, one with GitHub as platform provider and one with GitLab
* Let the scrapers run or do it manually:
* `docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainProgrammingLanguages`
* `docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainLicenses`
* `docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainCommits`
* Check that the `*_scraped_at` …

398 git scapers robust

---

deployment/docker-compose.yml
docker-compose.yml

Fixes #407 
* Use a named volume to store Let's Encrypt certificates to facilitate easier updates in production
How to test:
* This was tested on the dev vm
PR Checklist:
*   [ ] Tests

build: use volume for let's encrypt certificates

---

frontend/pages/login/failed.tsx

(No relevant issue number)
* just fixed a small typo
How to test:
* trigger a failure during login process
PR Checklist:
*   [ ] Tests

Correct typo in 'Login failed' message

---

LICENSES/MIT.txt

Fixes #425
PR Checklist:
*   [ ] Tests

fix: added MIT license

---

frontend/components/projects/edit/information/config.ts

Fixes #427
* Fix typo on edit page 
PR Checklist:
*   [x] Update documentation (config.ts)
*   [ ] Tests

fix useful typo in projects edit

---

.env.example
docker-compose.yml

Fixes #429 
Allow using project names for docker-compose, so the same containers and volumes will not be used for different versions of the RSD. Example: you have the origin repo in `~/git/RSD-as-a-service`, and a fork in `~/git/fork-project/RSD-as-a-service/`, they will share the same volumes, networks and containers (because `container_name` is defined). In case there are differences in the DB structure or elsewhere, this might cause some troubles.
This approach makes use of the `COMPOSE_PROJECT_NAME` environment variable (see [docs](https://docs.docker.com/compose/reference/envvars/#compose_project_name=)). Since the property `container_name` is specified for each container in the `docker-compose.yml`, this property would override `COMPOSE_PROJECT_NAME`. This is why I removed the …

feat: enable docker-compose project names

---

database/100-create-api-views.sql
docker-compose.yml
frontend/__tests__/OrganisationsIndex.test.tsx
frontend/__tests__/ProjectsIndex.test.tsx
frontend/components/form/Searchbox.tsx
frontend/components/keyword/KeywordFilter.tsx
frontend/package.json
frontend/pages/organisations/index.tsx
frontend/pages/projects/index.tsx
frontend/pages/software/index.tsx
frontend/utils/extractQueryParam.test.ts
frontend/utils/extractQueryParam.ts
frontend/utils/getSoftware.ts
frontend/utils/postgrestUrl.test.ts
frontend/utils/postgrestUrl.ts

Closes #418 
* User can filter on keywords on the software overview page. As the keywords are "free" values user needs fist to search for keywords he wants to add to filter
* Filtering on keywords is using AND "binding" between selected keywords.
* The filters are applied to url and can be saved or used to let other user land on the filtered software page.
How to test:
* `docker-compose down --volumes`: to remove old data structure
* `docker-compose build` to build new solution
* optional: run data migration
* on the software overview page you should see filter icon next to search input
* to add keyword you first type at least one letter of the keyword, a for example. The list of available keywords will be shown and you …

418 software keywords filter

---

docker-compose.yml
frontend/components/form/AsyncAutocompleteSC.tsx
frontend/components/projects/edit/related/RelatedProjectsForProject.tsx
frontend/components/software/edit/organisations/FindOrganisationItem.tsx
frontend/next.config.js
frontend/package.json
frontend/utils/getProjects.ts
frontend/utils/sortFn.ts

Closes #465 
Closes #458
*  User is able to remove related project and the item will be removed from UI
* When searching for organisation we show website and ror_id below the name and "missing" message when this info is not provided
How to test:
* `docker-compose build` to build new solution
* confirm you are able to remove related project on software edit page and project edit page
* confirm search for organisation returns following output
PR Checklist:
*   [ ] Tests

465 remove related project

---

Makefile
README.md
data-migration/README.md
database/002-create-software-table.sql
database/006-create-keyword.sql
database/008-create-mention-table.sql
database/009-create-release-table.sql
docker-compose.yml
documentation/docs/getting-started.md
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/MainMentions.java

* Columns in the database that store a DOI now use the case insensitive variable type `CITEXT` (see https://www.postgresql.org/docs/14/citext.html)
* Fix the mentions scraper to be case insensitive with respect to DOI's
* This update breaks the data-migration script, so we deprecate it and update the documentation
How to test:
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up`
* Add a software page, add a mention with doi `10.4230/DagMan.6.1.1`. The mention should be found in Datacite.
* Add another software page, add a mention with doi `10.4230/dagman.6.1.1` (note that it's the same DOI but with different casing). It should find this mention in the RSD instead of Datacite. You should be able to add this mention …

464 case sensitive doi

---

frontend/components/projects/edit/impact/ImpactByType.tsx
frontend/components/projects/edit/output/OutputByType.tsx

Fixes #468
I am unsure about the specific texts, maybe you have a more appropriate description for the sections.
* this adds information boxes to the impact and output section of the project edit pages
How to test:
* add or edit a project, on the impact and output sections there should be an info box with further explanations
PR Checklist:
*   [ ] Tests

Add explanations for impact and output sections

---

frontend/components/software/AboutLanguages.tsx

* change the color of the programming language bars to a more visible color (primary)
Before:
Now with this change:
How to test:
* have a software entry with scraped programming languages
* the bars for the programming languages should have the primary color
PR Checklist:
*   [ ] Tests

Improve visibility of programming language bars

---

frontend/pages/organisations/index.tsx
frontend/pages/projects/index.tsx
frontend/pages/software/index.tsx

Fixes #446
We may change the look of the pagination or we may also hide it completely it if there are only 12 or less entries to show (so there is no next page)...
* add an additional pagination component at the bottom of each grid view (software, projects, organisations)
How to test:
* build the feature branch and add some entries (software, projects, organisations) to the DB
* the grids should have a pagination component at the bottom allowing the user to select a different page
PR Checklist:
*   [ ] Tests

Improve visibility of pagination for grids

---

docker-compose.yml
frontend/components/layout/InvitationList.tsx
frontend/components/organisation/maintainers/OrganisationMaintainerLink.tsx
frontend/components/projects/edit/maintainers/ProjectMaintainerLink.tsx
frontend/components/software/edit/maintainers/SoftwareMaintainerLink.tsx
frontend/types/Invitation.ts
frontend/utils/getUnusedInvitations.ts

* It is now possible for maintainers to see and delete unused invitations
How to test:
* `docker-compose build frontend && docker-compose up`
* Login, add a software page, create some invite links. You should see a list with all unused invitations. You can copy them to the clipboard and delete them.
* Do the same for a project and an organisation.
Closes one of the items in #260
PR Checklist:
*   [ ] Tests

Allow maintainer to see and delete unused invitations

---

docker-compose.yml
frontend/components/form/AsyncAutocompleteSC.tsx
frontend/components/projects/edit/team/FindMember.tsx
frontend/components/projects/edit/team/config.ts
frontend/components/projects/edit/team/searchForMember.ts
frontend/components/software/edit/contributors/FindContributor.tsx
frontend/components/software/edit/editSoftwareConfig.tsx
frontend/utils/editContributors.ts
frontend/utils/getORCID.ts

* When entering a (syntactically correct) ORCID in the search field for contributors or team members, both the RSD and ORCID databases will be searched for on the ORCID field only
* It is now always possible to add a contributor or team member, even when results with a matching name have been found
How to test:
* `docker-compose build frontend && docker-compose up`
* Login, add a software page
* Search for an orcid, e.g. `0000-0003-4803-7411`. Only one result from the ORCID database should show up. Add this person as contributor. Search again with this ORCID, two results should show up (one from ORCID, one from the RSD)
* Search for a full name with results, e.g. `Jan Jansen`. Even though matches are found, it is still possible to manually add a …

433 team members

---

database/004-create-project-table.sql
database/100-create-api-views.sql
frontend/components/layout/ImageAsBackground.tsx
frontend/components/projects/ProjectCard.tsx
frontend/components/projects/ProjectDescription.tsx
frontend/components/projects/ProjectInfo.tsx
frontend/components/projects/add/AddProjectCard.tsx
frontend/components/projects/edit/information/ProjectImage.tsx
frontend/pages/projects/[slug]/index.tsx
frontend/types/Project.ts

Fixes #452 
I think this also fixes #443 
* add another switch to the project information page, so that the user can decide how the project image is displayed: cropped of (an zoomed in) or showing the whole image within the extend of the image container
How to test:
* ```
docker-compose down --volumes # there are db changes
docker-compose build database
make dev
docker-compose build --parallel
docker-compose up
```
* create a new project and upload a wide image for it
* the image should be cut off by default
* setting the switch "Always show the whole image" does not crop the image and instead lets it show contained fully in the surrounding image container
* other components showing projects also use this new value to show the image cropped or …

Add option to disable cropping of project images

---

docker-compose.yml
frontend/auth/index.tsx
frontend/components/page/edit/EditMarkdownPage.tsx
frontend/components/page/edit/PageEditorBody.tsx
frontend/components/page/edit/SortableNav.tsx
frontend/components/page/edit/index.tsx
frontend/components/software/add/AddSoftwareCard.tsx
frontend/components/software/edit/testimonials/SortableTestimonialList.tsx
frontend/package.json

Closes #475 
*  When editing markdown pages, when input is changed by not saved after for max 60min the refresh token process will run and the page will rerender which leads to lost of changed but not saved input.    
How to test:
* if you do not have latest version of database
*  `docker-compose down --volumes`: to remove old data
* `docker-compose build` to build complete solution
* if you have latest db changes
* `docker-compose build frontend` to build frontend only
* login as rsd_admin
*  in .env file add this definition: `RSD_ADMIN_EMAIL_LIST=isaacnewton@university-example.org`
*  then login as professor3, which with this settings will get rsd_admin role
* open adminstration section from the user menu
* create one …

475 fix markdown pages

---

docker-compose.yml
frontend/components/projects/edit/information/index.tsx
frontend/package.json
frontend/types/Project.ts

Closes #500 
*  User can edit project link values and save
How to test:
* `docker-compose build`: to build solution
* `docker-compose up` to start services
* login and create project
* add link, save and preview page
* edit page, change link title or url BUT JUST 1 charater. The save button will be enabled 
* use save and view the page, the change you made should be shown. 
* Go back to edit page, the url with latest changes is loaded
PR Checklist:
*   [ ] Tests

500 fix edit project link

---

database/012-inter-relation-tables.sql
database/100-create-api-views.sql
docker-compose.yml
frontend/components/projects/edit/organisations/index.tsx
frontend/utils/editProject.ts

* Organisations can now be both funding and participating for a project, while before they were mutually exclusive
How to test:
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --scale scrapers=0`
* Login and create a project
* Add a funding organisation to that project (in the "Information" tab) and save
* Add the *same* organisation to that project as a participating organisation (in the "Organisations tab")
* The funding organisation should still be there in the admin interface
* View the project and check that the organisation is shown both as funding and as participating
* Delete the organisation as a funding organisation, check it's still a participating organisation
* Add again and now delete it as …

498 allow organisations multiple roles for projects

---

frontend/components/projects/edit/impact/FindImpact.tsx
frontend/components/projects/edit/output/FindOutput.tsx
frontend/components/software/edit/mentions/FindSoftwareMention.tsx

* Mentions can now be searched for with a full URL, and leading and trailing whitespace is allowed as well
How to test:
* `docker-compose build frontend && docker-compose up --scale scrapers=0`
* Create software, search for a mention (but don't add it) with each of the variants below, in the devtools you should see a request to `localhost`, `doi.org` and `api.datacite.org`, but not to Crossref, the result should show up quickly
* `10.5281/zenodo.7010594`
* `doi.org/10.5281/zenodo.7010594`
* `https://doi.org/10.5281/zenodo.7010594`
* `http://doi.org/10.5281/zenodo.7010594`
* `https://dx.doi.org/10.5281/zenodo.7010594`
* `http://dx.doi.org/10.5281/zenodo.7010594`
* `dx.doi.org/10.5281/zenodo.7010594`
* `www.doi.org/10.5281/zenodo.7010594`
* …

fix: add functionality to find a mention by its full DOI URL

---

frontend/components/layout/EditSectionTitle.tsx
frontend/components/projects/ProjectSidebar.tsx
frontend/components/projects/ProjectTags.tsx
frontend/components/projects/edit/information/ResearchDomains.tsx
frontend/components/projects/edit/information/config.ts

* On both the public project pages and the project admin pages, add an info link (as an info icon) to https://erc.europa.eu/news/new-erc-panel-structure-2021-and-2022 for research domains
How to test:
* `docker-compose build frontend && docker-compose up --scale scrapers=0`
* If there is no project yet, create one
* On the project admin page, on the right sidebar, look of the info icon and verify where it links to
* Go to the view page, the icon is there as well on the right sidebar
Closes #447
PR Checklist:
*   [ ] Tests

447 link research domains

---

frontend/components/software/edit/contributors/index.tsx
frontend/components/software/edit/editSoftwareContext.tsx
frontend/components/software/edit/information/SoftwareLicenses.tsx
frontend/components/software/edit/information/index.tsx
frontend/components/software/edit/information/useSoftwareToEdit.tsx
frontend/components/software/edit/organisations/index.tsx
frontend/types/SoftwareTypes.ts
frontend/utils/editSoftware.ts
frontend/utils/getInfoFromDatacite.test.ts
frontend/utils/getInfoFromDatacite.ts
frontend/utils/useSpdxLicenses.tsx

Closes #259 
Closes #518 
*  Import license from DOI will import all licenses provided by DOI api
*  Contributors import will deduplicate creators and contributors information on name
How to test:
* `docker-compose build frontend` to build frontend solution
* login as user and create project if you do not have any to edit
* paste this concept DOI: 10.5281/zenodo.597993
* It should import 2 licenses
* try with another DOI: 10.5281/zenodo.6900341
* multiple import attempts should not import same licenses 2 times
* use DOI: 10.5880/riesgos.2021.003
* go to contributors and import contributors. 
* previously it imported same person twice if the person was defined in creators and contributors array. Now it should import one …

518 fix: extract licenses without rightsIdentifier from DOI

---

database/020-row-level-security.sql

* Enable row level security for oaipmh
How to test:
* Execute the same steps as in #529
* The data should still be visible, regardless if you're logged in or not
* If you're not an admin, any change requests to the table should return status code 401
PR Checklist:
*   [ ] Tests

fix: enable row level security for oaipmh

---

data-generation/main.js
database/100-create-api-views.sql
deployment/docker-compose.yml
docker-compose.yml

* Fix slow database function
* Fix data-generation bug that would cause no organisation images to be saved
* Add missing env variable to the deployment `docker-compose.yml`
How to test:
* If you want more test data, change the values in `data-generation/main.js`
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --scale scrapers=0 --scale data-generation=1`
* Check that the organisation pages ase faster now (eventually change back the old function via a direct query in the database to compare)
PR Checklist:
*   [ ] Tests

Fix slow organisation pages

---

docker-compose.yml
frontend/__tests__/Home.test.tsx
frontend/components/home/rsd/index.tsx
frontend/package.json

*  After introducing dynamic homepage the counts were lost. This fix ensures the counts are shown on RSD home page (incl. additional test).
How to test:
* `docker-compose build frontend` to build frontend
* `docker-compose up` to start solution
PR Checklist:
*   [x] Tests

fix: show homepage counts, align count props with api.

---

docker-compose.yml
frontend/utils/editOrganisation.ts

* When searching to add a participating/funding organisation, we first query the ROR database, then we search the RSD database, where we also query for ROR-ids found in the first search
* The search to the RSD db does only one query for name, website and ROR-ids, not multiple queries
How to test:
* `docker-compose build --parallel && docker-compose up --scale scrapers=0`
* Login as an admin
* If necessary, create a software and project page
* On the sw page, add organisation by searching for `Vrije Universiteit`, add the `Vrije Universiteit Amsterdam` one from ROR.
* Go to the Vrije Universiteit Amsterdam page, edit the name to be `Free University` (or something completely random if you want)
* Go to the project page, search for `Vrije Universiteit` …

442 duplicate ror organization

---

Makefile

* fixes issue that when running `make frontend`, the file `frontend/.env.local` was not automatically updated
How to test:
* create a change in `.env` (e.g. remove or add a login provider)
* `make frontend`
* the first lines should now be:
```
Creating frontend/.env.local
cp .env frontend/.env.local
sed -i 's/POSTGREST_URL=http:\/\/backend:3500/POSTGREST_URL=http:\/\/localhost\/api\/v1/g' frontend/.env.local
sed -i 's/RSD_AUTH_URL=http:\/\/auth:7000/RSD_AUTH_URL=http:\/\/localhost\/auth/g' frontend/.env.local
```
PR Checklist:
*   [ ] Tests

Add makefile frontend dependency to .env.local

---

frontend/components/AppFooter/index.tsx

Closes #552 
*    The static footer title 'Research Software Directory" on the right side of the footer is removed (requested by Maaike).
How to test:
* `docker-compose build frontend` to build frontend
* navigate to home page, or any other page, the right section of the footer should contain only links
PR Checklist:
*   [ ] Tests

fix: remove static rsd title from the footer

---

.env.example
frontend/next.config.js
frontend/next.headers.js
frontend/next.rewrites.js
frontend/pages/_app.tsx
frontend/pages/_document.tsx
frontend/styles/createEmotionCache.ts
frontend/utils/contentSecurityPolicy.ts

Closes #563 
*  We add security headers required to pass audit by AMC for enabling SURFconnect authorization. We have A grade with one warning and one red point (we allow embeding RSD pages) that cannot be addressed at the moment.
* Load tests showed no significant impact on the website performance after implementing security headers and using matomo instead of hotjar.
How to test:
*  Cannot be tested locally. The headers are applied to dev. Hotjar does not work properly ;-(
*  We allow EMBED of website and have one warning. But A grade should be sufficient!
*  The results can be viewed [here](https://securityheaders.com/?q=https%3A%2F%2Fresearch-software.dev%2F&followRedirects=on)
**There is no significant change in the website performance after …

fix: add security headers based on advice from securityheaders.com

---

frontend/styles/createEmotionCache.ts

Closes #572 
*  Applies MUI color on the buttons     
How to test:
* `docker-compose build frontend` to build solution
* login as rsd_admin or user and create software/project
* add contributor/team member/organisation
* then try to delete item. The popup will apprear for confirmation. The button background color should be red
PR Checklist:
*   [ ] Tests

fix: mui contained button color should be applied

---

Makefile
README.md
docker-compose.yml
frontend/Dockerfile.dev
frontend/README.md
frontend/package.json
nginx/nginx.conf

Fixes #549 
Approach number three: I would like to propose a way to run the frontend in development mode without having to build the whole `frontend` container first to save some time. This PR now adds:
**Update 3**
* substituted the `proxy_pass = http://frontend:3000` in nginx with a variable `$frontend` pointing to the same url. This trick stops nginx from checking the availability of the `frontend` container on startup, meaning it will not exit when it is not found. This way, we do not need a separate nginx image for `frontend-dev`
* use the docker resolver in nginx to discover the frontend container
* mount the nginx conf via docker-compose so the container does not have to be rebuilt every time one changes the configuration
* `frontend-dev` …

More convenient frontend-dev configuration

---

frontend/components/organisation/maintainers/OrganisationMaintainerLink.tsx
frontend/components/organisation/maintainers/index.tsx
frontend/components/projects/edit/maintainers/ProjectMaintainerLink.tsx
frontend/components/projects/edit/maintainers/index.tsx
frontend/components/software/edit/editSoftwareContext.tsx
frontend/components/software/edit/maintainers/SoftwareMaintainerLink.tsx
frontend/components/software/edit/maintainers/index.tsx
frontend/config/userMenuItems.tsx

* Add the name of the software/project/organisation in the invite email template
How to test:
* `docker-compose build frontend && docker-compose up --scale scrapers=0`
* Login as an admin
* Create invites for software, projects and invitations
* Check that the email templates contain the names of the unit
Closes #451
PR Checklist:
*   [ ] Tests

fix: more information in invitation email templates

---

.gitignore
frontend/components/projects/edit/impact/EditImpactProvider.tsx
frontend/components/projects/edit/impact/impactForProjectApi.ts
frontend/components/projects/edit/output/EditOutputProvider.tsx
frontend/components/projects/edit/output/outputForProjectApi.ts
frontend/components/software/edit/mentions/EditMentionsProvider.tsx
frontend/components/software/edit/mentions/mentionForSoftwareApi.ts
frontend/utils/editMentions.ts
frontend/utils/getCrossref.ts
frontend/utils/getDOI.ts
frontend/utils/getDataCite.ts
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/CrossrefMention.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/DataciteMentionRepository.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/MainMentions.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/PostgrestMentionRepository.java

Closes #578 
*  Support search using encoded doi url. Additional check in crossref request is removed because it does not match encoded and doi value from api when search uses encoded values and api returns "decoded" value    
How to test:
* `docker-compose build frontend scrapers` to build solution
* `docker-compose up` to start solution
* login as rsd_admin or any other user and go to edit project - impact (or output)
* search for publication using encoded url like thisone `https://doi.org/10.1175/1520-0469(2003)60%3C1201:ALESIS%3E2.0.CO;2`
* Search should return one value.
* Use not valid value like `10.1147/2996913.2997004`, you should see "Nothing found..." message
* Now we test the scrapers
* `docker-compose down --volumes && docker-compose up …

Search by doi using encoded url

---

frontend/components/charts/d3LineChart/NoDataAvailableChart.tsx
frontend/components/charts/d3LineChart/formatData.ts
frontend/components/home/getHomepageCounts.ts
frontend/components/software/CommitsChart.tsx
frontend/components/software/GetStartedSection.tsx
frontend/pages/software/[slug]/index.tsx
frontend/types/SoftwareTypes.ts
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/ResponseException.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/Utils.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/AggregateContributionsPerWeekSIDecorator.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/GithubSI.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/git/AggregateContributionsPerWeekSIDecoratorTest.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/git/GithubSITest.java

Fixes #419
* Adds a commit graph replacement if the graph cannot be rendered
* If `commit_history_scraped_at` is `null` display "We did not scrape the commit history of this repository yet."
* If a repository was scraped, and there is no commit history display
"We cannot display this graph because we cannot read the commit history."
To do
How to test:
* add a new software with a closed source repository (e.g. `https://git.gfz-potsdam.de/moose/lynx`)
* add the same url (or another) to get-started url
* Save it and view the page. It should show this message:
* wait until the scrapers ran, or run
```
docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainCommits
```
* software page should now display
* …

419 no commits graph

---

frontend/components/form/AutosaveControlledMarkdown.tsx
frontend/components/organisation/OrganisationNav.tsx
frontend/components/organisation/OrganisationNavItems.tsx
frontend/components/organisation/about/index.tsx
frontend/components/organisation/maintainers/index.tsx
frontend/components/organisation/organisationConfig.ts
frontend/components/organisation/project/ProjectCardWithMenu.tsx
frontend/components/organisation/settings/AutosaveOrganisationTextField.tsx
frontend/components/organisation/settings/AutosaveOrgnisationMarkdown.tsx
frontend/components/organisation/settings/OrganisationSettings.test.tsx
frontend/components/organisation/settings/RorIdWithUpdate.tsx
frontend/components/organisation/settings/RsdAdminSection.tsx
frontend/components/organisation/settings/index.tsx
frontend/components/organisation/settings/updateOrganisationSettings.tsx
frontend/components/organisation/software/SoftwareCardWithMenu.tsx
frontend/components/projects/edit/information/AutosaveFundingOrganisations.tsx
frontend/components/projects/edit/information/index.tsx
frontend/components/projects/edit/information/useProjectToEdit.tsx
frontend/components/projects/edit/organisations/useParticipatingOrganisations.ts
frontend/components/software/edit/information/AutosaveRepositoryUrl.tsx
frontend/components/software/edit/information/AutosaveSoftwareMarkdown.tsx
frontend/components/software/edit/information/patchSoftwareTable.ts
frontend/components/software/edit/organisations/useParticipatingOrganisations.ts
frontend/pages/organisations/[...slug].tsx
frontend/types/Organisation.ts
frontend/utils/editOrganisation.ts
frontend/utils/getOrganisations.ts
frontend/utils/getROR.ts

Closes #482
Closes #582
*  I implemented autosave feature and removed Save button similar to edit software and projects page
*  The markdown section is added to the settings. Organisation admin can add the about text in markdown format to enable additional menu option (about section)
*  About section is allowed at all levels, the top organisation and the research units (children)
How to test:
* `make start` to completely reset and rebuild your local rsd (to stop use `docker-compose down` when you are done)
* login as rsd_admin or maintainer of an organisation
* you will always see about section as maintainer. If there is no content, the info will be shown. You can click on bold text to open settings section
* add markdown in the settings (About page …

482 about organisation section

---

backend-postgrest/Dockerfile
database/017-create-narcis-table.sql
deployment/docker-compose.yml
docker-compose.yml
frontend/types/Project.ts
frontend/types/SoftwareTypes.ts
frontend/utils/editSoftware.ts
frontend/utils/getProjects.ts
nginx/nginx.conf

* Upgrade from PostgREST 9.0.0 to  10.0.0
* Change the column `data` of the `oaipmh` table from `VARCHAR` to `XML`
* Small fix in the frontend to adapt to [one-to-one embedding](https://postgrest.org/en/stable/releases/v10.0.0.html#resource-embedding)
How to test:
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --scale data-generation=1`
* Check that everything still works, both as a visitor and as an admin
* Check the [oaipmh endpoint](http://localhost/oaipmh?metadataPrefix=datacite4&verb=ListRecords) after having added a real concept DOI and having run the scraper (`docker-compose exec scrapers python3 -u /usr/myjava/oaipmh.py`)
* Check that the API endpoints return JSON again (e.g. …

588 postgrest update

---

frontend/components/organisation/metadata/OrganisationLogo.tsx
frontend/components/organisation/metadata/index.tsx
frontend/components/organisation/metadata/useOrganisationMetadata.ts
frontend/pages/organisations/[...slug].tsx
frontend/tailwind.config.js
frontend/utils/getROR.ts

Closes #395 
* Show more information about the organisation available from ror api (based on ror_id). In this PR we only show additional information from ROR for the organisations that have ror_id.     
*  The additional information we show:  
*  Type: COMPANY, NONPROFIT, EDUCATION, HEALTHCARE etc. The type values are provided by ROR api
*  Location based on city and country provided by ROR api. The location is clickable and opens google maps based on query parameters: name, city, country
* Links: ror api provides links to organisation website and in some cases wikipedia page
Currently we do not offer entering this information for organisations that are manually created. If there is a need for this in the future we can expand settings property. The …

395 show organisation metadata using ror api

---

authentication/Dockerfile
authentication/pom.xml
data-generation/main.js
docker-compose.yml
scrapers/Dockerfile
scrapers/pom.xml
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/CrossrefMention.java

* Upgrade the libraries that we use on the backend to new major versions (Javalin 5 and Java JWT 4)
* Some small upgrades as well
* Remove Inkscape as an example repo for GitLab in the data-generation script, because it takes too long to scrape its commits
How to test:
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --scale data-generation=1`
* Login with every provider, this should work
* Wait until the Java scrapers have run (programming languages, licenses, commits and mentions), this should work
Is related to #588
PR Checklist:
*   [ ] Tests

588 java updates

---

database/006-create-keyword.sql
database/020-row-level-security.sql
frontend/components/form/AsyncAutocompleteSC.tsx
frontend/components/keyword/FindKeyword.tsx
frontend/components/layout/TagChip.tsx
frontend/components/projects/edit/information/AutosaveProjectKeywords.tsx
frontend/components/software/edit/information/AutosaveSoftwareKeywords.tsx
frontend/components/software/edit/information/ImportKeywordsFromDoi.tsx
frontend/utils/editKeywords.ts

Closes #596 
Closes #597
* We do not allow leading & trailing spaces or multiple spaces between the words. The database will reject these entries
* On input side we improved search (without leading/trailing spaces) and deduplication of imported keywords
* The keywords are trimmed before send to api
* On the presentation side we use capitalized value in the "chips", this does not impact accronims, for example GPU is still shown in capitals
How to test:
* `make start` to reset and rebuild
* login as rsd_admin or create new software or project
* navigate to software and try to add Python and python with some spaces before or after the keyword. All the results should produce one python entry which in "chip" will be shown with capital P.
PR Checklist:
* …

597 sanitise keywords and improve checks

---

frontend/components/organisation/metadata/OrganisationLogo.tsx
frontend/components/organisation/units/index.tsx
frontend/components/projects/edit/information/AutosaveProjectImage.tsx
frontend/components/projects/edit/team/editTeamMembers.ts
frontend/utils/editContributors.ts
frontend/utils/editOrganisation.ts

*  The page reload is needed with current setup to invalidate cached image when new image is uploaded
*  This is required on project and organisation page. However same (shared) method is used on software/project page organisation section, which resulted in page reload and   
How to test:
*  login to RSD, as rsd_admin
*  Edit software, add new organisation and upload the logo. This should not result in page reload
*  Edit project, add image. This should result in page reload
*  Add organisation to project with an logo (upload logo). This should not result in page reload
*  Navigate to an organisation as rsd_admin. Change organisation logo. This should result in page reload.
PR Checklist:
*   [ ] Increase version numbers …

fix: image cache reload on organisation page but not on the software page

---

data-generation/main.js
database/008-create-mention-table.sql
frontend/components/mention/EditMentionModal.tsx
frontend/components/mention/MentionItemBase.tsx
frontend/components/mention/MentionNote.tsx
frontend/components/mention/MentionViewItem.tsx
frontend/components/mention/config.ts
frontend/pages/_document.tsx
frontend/types/Mention.ts
frontend/utils/editMentions.ts
frontend/utils/getCrossref.ts
frontend/utils/getDataCite.ts
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/DataciteMentionRepository.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/MentionType.java

Closes #609 
Closes #559 
Closes #514 
Closes #513 
* The classification of data cite mention type is updated to new version 4.4 for the scrapers and in initial frontend import      
* Unrelated change: use next Script component to lazy load matomo script
How to test:
* login as rsd_admin 
* edit software, go to mentions and add these 2 DOI's: 
* https://doi.org/10.4233/uuid:92565bdb-cf5a-4110-abf3-1b4298720466
* https://doi.org/10.4233/uuid:6d18abba-a418-4870-ab19-c195364b654b
* both mentions should be placed under Thesis mention section. This classification remain after the scrapers made updates of these mentions.
* Create a manual mention with a note. The note should be visible both in the admin section and the public …

609: Mention improvements

---

frontend/components/cookies/CookieConsentMatomo.tsx

Closes #612
*     On mobile the cookie banner takes full width on the bottom of the screen
How to test:
* `make start` to rebuild all (docker-compose down where you done)
*  validate you have matomo env variables active:
```env
MATOMO_URL=https://matomo.research.software/
MATOMO_ID=1
```
* remove matomo cookies and settings from cookies and local storage (F12 -> Application tab)
* local storage variable: rsd_cookies_consent
* cookies
PR Checklist:
*   [ ] Tests

612: fix cropped cookie banner on mobile

---

docker-compose.yml
frontend/components/feedback/FeedbackPanelButton.tsx
frontend/components/login/LoginButton.tsx
frontend/components/login/LoginDialog.tsx
frontend/config/rsdSettingsReducer.ts
frontend/package.json
frontend/pages/api/fe/auth/helmholtzaai.ts
frontend/pages/api/fe/auth/index.ts
frontend/pages/api/fe/auth/local.ts
frontend/pages/api/fe/auth/orcid.ts
frontend/pages/api/fe/auth/surfconext.ts
frontend/public/data/settings.json
frontend/styles/global.css

Closes #619 
*  Additional property is added to provider object in order to show additional information about the provider and who can make use of this provider. To accommodate additional text the layout of the button is changed. Additional info text is added into service provider api (not in env file). 
* The quote is moved at the bottom of the modal
* In SURFconext text link to IdP listing of RSD service is added
* In ORCID text mailto link is added to contact rsd team
* At the bottom of the login modal a link to sign in page of RSD documentation is added. The link is added into settings as `host.login_info_url`
How to test:
* Ensure you have proper env definitions for login providers (contact me for values of env file)
* Ensure you enabled the …

619: additional explanation login options

---

frontend/components/form/AsyncAutocompleteSC.tsx
frontend/components/keyword/FindKeyword.test.tsx
frontend/components/keyword/FindKeyword.tsx
frontend/components/keyword/KeywordFilter.tsx
frontend/components/mention/FindMention.test.tsx
frontend/components/organisation/project/index.tsx
frontend/components/organisation/software/index.tsx
frontend/components/projects/edit/information/config.ts
frontend/components/projects/edit/information/searchForKeyword.ts
frontend/components/software/SoftwareKeywordFilter.tsx
frontend/components/software/SoftwareKeywords.tsx
frontend/components/software/edit/editSoftwareConfig.tsx
frontend/components/software/edit/information/searchForSoftwareKeyword.ts
frontend/pages/organisations/index.tsx
frontend/pages/projects/index.tsx
frontend/pages/software/index.tsx
frontend/styles/global.css
frontend/utils/getOrganisations.ts
frontend/utils/postgrestUrl.ts

Closes #496
* Filter icon moved infront the "Find" input to indicate that filtering is used in combination with find term. When filter is active the find input is limited to filtered content (see screenshot 1)
* The info text in the filter dropdown is extended. **Please check and deliver improvement suggestions**
* The input placeholder is changed to "Find software", when filter is activated message is changed to "Find within selection"
* When filter is not applied the input search by title (partial value), short_description (partial value) and in the keywords (complete value). Note that keyword match is not the wildcard match (it requires complete keyword value)
* Search keywords component is pre-loaded with top 30 items to assist the user during …

496 keyword filter inital list

---

authentication/README.md
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Main.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/PostgrestCheckOrcidWhitelistedAccount.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/RsdAuthenticationException.java
frontend/auth/locationCookie.ts
frontend/pages/login/failed.tsx

* When logging in, if this fails, we show a custom error, e.g. that your ORCID is not whitelisted
* This message is passed from the auth module to the frontend using a cookie
How to test:
* `docker-compose build --parallel && docker-compose up`
* Make sure your sandbox ORCID is not on the whitelist, login with this ORCID, this should fail and you should see a custom error message in red
* In your `.env`, set a value for `RSD_AUTH_USER_MAIL_WHITELIST`, restart the containers
* Login with either SURFConext or Helmholtz AAI with an account with a different email address, you should see a custom error message again
Closes #617
PR Checklist:
*   [x] Update …

fix: show a custom error message when logging in fails

---

docker-compose.yml
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/RsdResponseException.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/Utils.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/GithubSI.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/MainCommits.java

* If we get status 202 from GitHub when scraping commits, wait 3 seconds and try again
* If we then still get 202, we treat it as if we could not scrape it and reuse the old data
How to test:
* This is hard to test, since you need a 202 response from GitHub and we don't print to console when this happens, I manually tested this (also with prints)
* Check that it builds at least
* `docker-compose build auth && docker-compose up`
* Make sure to have some repos in the database and manually run the commit scraper a few times to see no unexpected errors occur:
* `docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainCommits`
Closes #620
PR Checklist:
* …

620 retry commit scraper on 202

---

frontend/components/mention/MentionEditFeatured.tsx
frontend/components/mention/MentionEditSection.tsx
frontend/components/organisation/metadata/OrganisationLogo.tsx
frontend/components/software/edit/information/ImportKeywordsFromDoi.tsx
frontend/utils/editKeywords.ts

* Import keywords on software edit page from concept DOI was failing due to last changes in keyword component.
* Rsd admin was not able to edit highlighted (manual) item while it was able to edit other types of manually created mentions
* Svg logo (some) was not visible in the organisation card (noticed with Bayer svg logo from their website).
How to test:
* login as rsd_admin to be able to edit software
* edit or create software item. Provide a valid concept DOI (10.5281/zenodo.6379973) and use import keywords button. This should work properly
* edit or create project. Create new impact item of type highlight. After saving you should be able to edit the item if you are logged in as rsd_admin role
* Navigate to …

Minor bug fixes

---

frontend/components/AppFooter/index.tsx
frontend/components/AppHeader/index.tsx
frontend/components/keyword/KeywordFilter.tsx
frontend/components/layout/MainContent.tsx
frontend/components/organisation/OrganisationCard.tsx
frontend/components/projects/ProjectCard.tsx
frontend/styles/global.css

Closes #369
* Logo/Avatar is shown on mobile in organisation card      
How to test:
*  navigate to organisation overview page
*  switch to mobile view (chrome: F12, on the right select diferent views - see printscreen)
* confirm that image/logo is visible
PR Checklist:
*   [ ] Tests

369: show logo on mobile

---

.env.example
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Config.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/OrcidLogin.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/SurfconextLogin.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Utils.java
authentication/src/test/java/nl/esciencecenter/rsd/authentication/UtilsTest.java
docker-compose.yml

* Remove the `*_TOKEN_URL` env variables and adapt the auth module so that the token URL is queried from the well known URL on every request
* Give the reason when you login with e.g. GitHub through Helmholtz AAI and `HELMHOLTZAAI_ALLOW_EXTERNAL_USERS=false`
How to test:
* Remove `*_TOKEN_URL` values from your `.env` (see `env.example`)
* `docker-compose build auth && docker-compose up`
* Set `HELMHOLTZAAI_ALLOW_EXTERNAL_USERS=true`
* Login with all three providers, this should work
* Set `HELMHOLTZAAI_ALLOW_EXTERNAL_USERS=false`
* Login with Helmholtz AAI through GitHub or ORCID, you should see in red text `You are not allowed to login`
Maybe we should cache the token URL instead of querying it on every login. On my tests, ORCID was slow, taking 200 …

589 token url

---

frontend/pages/admin/orcid-whitelist.tsx

* On the ORCID whitelist page, a button is added that, when clicked, fetches all the names of the whitelisted ORCIDs and shows them.
How to test:
* `docker-compose build frontend && docker-compose up`
* Login as admin
* Add some ORCIDs to the whitelist, both real and fake
* Click the button, it should be replaced by a spinner
* When fetching is done, the names should be displayed and the button should be back
PR Checklist:
*   [ ] Tests

Whitelist names

---

frontend/components/software/SoftwareCard.tsx

*  Based on @ctwhome suggestion for UI improvements, I added icons and the tooltip to show mention and contributor counts in the software card
How to test:
* `make start` to rebuild everything (when done use docker-compose down)
* navigate to software overview, the card should look like in the example 1
* on mouseover the message should shown with counts, like `3 mentions`  or `3 contributors` 
* navigate to organisation, software cards should have similar functionality
* login as rsd_admin in order to feature and block software. These action are also shown in example 2
PR Checklist:
*   [ ] Tests

Use icons in software card

---

.github/workflows/_ghcr.yml

Fixes #618 
* Updated deprecated set-ouput command in ghcr action. However, we also depend on some other actions that need to perform this update.       
How to test:
* As far as I know it can be only tested by creating a new release draft. I propose to wait until next release and confirm improvements (as mentioned other gh actions we use also need to make this update)
PR Checklist:
*   [ ] Tests

ci: update set-output in ghcr action

---

documentation/docs/getting-started.md

Due to an unforeseen downtime of the dev instance of Helmholtz AAI, I was forced to use other login methods. I used the opportunity and updated the docs accordingly.
* adds a section about 'Logging in with admin rights'
How to test:
```
cd documentation
yarn install
yarn dev
```
or `make dev-docs`
Open http://localhost:3030 and navigate to "Getting Started" -> "Running locally" -> "Logging in with admin rights"
PR Checklist:
*   [ ] Tests

docs: adds info about logging in with admin rights

---

database/100-create-api-views.sql
frontend/utils/getOrganisations.ts

The order of organisation on organisation overview page is changed to officially registered organisation first, then by software + projects count and last by name (ascending). In addition we only show organisation with at least one published software or project.
**The organisation count on the homepage and on the organisations overview page are identical.**
How to test:
* `make start` to rebuild everything
*  visit organisations page. Officially registered organisations (is_tenant=true) should be listed as first
*  organisation without software and projects (score=0) are not shown in the overview
PR Checklist:
*   [ ] Tests

Change organisation order to officially registered first

---

frontend/components/AppFooter/ContactEmail.tsx
frontend/components/AppFooter/index.tsx
frontend/components/home/rsd/OrganisationSignUp.tsx
frontend/components/home/rsd/PersonalSignUp.tsx
frontend/components/home/rsd/index.tsx
frontend/public/data/settings.json

*  Homepage title changed to "Show your research software to the world"    
*  Few other textual changes on the homepage and in the footer
How to test:
*  `make start` to rebuild everything
*  navigate to home page and confirm title change
PR Checklist:
*   [ ] Tests

Change homepage title

---

frontend/public/data/settings.json

*  Link to getting access page from login modal for more information     
How to test:
* use Sign in button, the login modal should appear
* At the bottom of the login the documentation link should open getting access page in new tab
PR Checklist:
*   [ ] Tests

Link to getting access documentation page in login modal

---

frontend/components/software/ContactPersonCard.tsx

* On software and project pages, if the contact person has an ORCID, we show it on the contact person card
How to test:
* `docker-compose down --volumes && docker-compose build frontend && docker-compose up --scale data-generation=1`
* View some software and project pages
* Pages with a contact person with an ORCID should show this ORCID in the contact person card, as a link to the ORCID webpage
Closes #661
PR Checklist:
*   [ ] Tests

661: show ORCID in contact person card

---

.env.example
deployment/docker-compose.yml
docker-compose.yml

Related to #671
* introduces two env variables for docker-compose.yml in order to change the Postgres DB Host and Port
How to test:
* copy `.env.example` to `.env`
* change `POSTGRES_DB_HOST` and enter the database hostname
* change `POSTGRES_DB_HOST_PORT` and specify the port under which the DB host is available
* Start the services: `docker-compose up`
PR Checklist:
*   [ ] Tests

feat: add env vars to specify db host and port

---

frontend/components/software/AboutLanguages.tsx
frontend/utils/getSoftware.ts
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/PostgrestSIR.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/git/PostgrestSIRTest.java

* Store programming language and commit history as proper JSON objects instead of strings
How to test:
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --scale data-generation=0`
* Add two software pages, with repo URLs https://github.com/research-software-directory/RSD-as-a-service and https://gitlab.com/cyber5k/mistborn respectively
* Make sure the two relevant scrapers have run: 
* `docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainProgrammingLanguages`
* `docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainCommits`
* View the two software pages
* The commit history and languages should be properly displayed …

fix: commit and programming languages scraper now store unescaped JSON

---

scrapers/src/main/java/nl/esciencecenter/rsd/scraper/RsdRateLimitException.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/GitLabSI.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/GithubSI.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/MainCommits.java

Fixes #686 
* if the response code indicates that the API rate limit is exceeded (403 for github, 429 for GitLab), do not update the entry so that it will still be listed as a repo that has not been scraped yet
How to test:
* make sure that `API_CREDENTIALS_GITHUB` in `.env` is unset
* `docker compose build scrapers && docker compose up`
* reach the rate limit by running
```
for i in {1..60}; do curl -I https://api.github.com/users/octocat ; done
```
* If the rate limit is reached, create a new software with url `https://github.com/research-software-directory/RSD-as-a-service`
* Run the scrapers `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainCommits`
* Open the corresponding software page, the …

Do not set scrapedAt if rate limit is exceeded

---

.vscode/settings.json
database/003-create-software-table.sql
frontend/components/layout/CardTitle.tsx
frontend/components/layout/ImageWithPlaceholder.tsx
frontend/components/organisation/OrganisationGrid.tsx
frontend/components/projects/edit/information/config.ts
frontend/components/software/AboutSection.tsx
frontend/components/software/SoftwareLogo.tsx
frontend/components/software/add/AddSoftwareCard.test.tsx
frontend/components/software/add/AddSoftwareCard.tsx
frontend/components/software/edit/editSoftwareConfig.tsx
frontend/components/software/edit/information/AutosaveSoftwareLogo.tsx
frontend/components/software/edit/information/index.tsx
frontend/components/software/edit/information/useSoftwareToEdit.tsx
frontend/pages/software/[slug]/index.tsx
frontend/pages/software/index.tsx
frontend/types/SoftwareTypes.ts

Fixes #644
* allow uploading logos for software
* display software logo in the About Section
I decided to treat the uploaded image as logo, because I think uploading regular images, e.g. screenshots or diagrams, may have more implications (e.g. how many could be uploaded, how should they be integrated).
How to test:
* ```
docker compose down --volumes && docker compose build --parallel && docker compose up --scale data-generation=1 --scale scrapers=0
```
* login as administrator
* edit an existing software and upload a logo in the information section
* view the page, the logo shows in the about section
* remove the logo, and view page again
* no logo is shown in the about section
PR Checklist: …

644 logos for software

---

database/012-create-organisation-table.sql
database/100-create-api-views.sql
frontend/components/layout/CardTitle.tsx
frontend/components/layout/StatCounter.tsx
frontend/components/organisation/OrganisationCard.tsx
frontend/components/projects/edit/information/index.tsx
frontend/components/projects/edit/organisations/index.tsx
frontend/components/software/SoftwareCard.tsx
frontend/components/software/edit/organisations/EditOrganisationModal.tsx
frontend/components/software/edit/organisations/index.tsx
frontend/tailwind.config.js

Closes #696 
Based on the test from HMZ the organisation card did not show all values. See image
*  limited card title to 2 lines, the complete name is show on mouseover
*  reduced font size of the score to 3.5 from 4.5
*  reduced line height of the score from 1.5 to 1.25
*  set the image object fit to contain complete logo 
Unrelated fixes:
* The project status when the start date is in the future should be "Starting"
* The character counter on the inputs of the edit project info section should show input length while typed (as in software edit info)
* The organisation name input is additionally validated on modal load because it can contain invalid value taken over from the search input
How to test:
* `make start` to rebuild everything
* navigate …

Organisation card fix, incl. 2 other fixes

---

docker-compose.yml
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/Utils.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/GithubSI.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/git/CommitsPerWeekTest.java

* The GitHub scraper now properly pushes an empty JSON object when the commit history is empty
How to test:
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --scale data-generation=0`
* Add one software page with repo URL https://github.com/cmeessen/empty
* Wait or run the commit scraper manually: 
* `docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainCommits`
* The commit graph should say `We cannot display this graph because the repository is empty.`
* You can check that in the db an empty JSON object (`{}`) is stored under the commit history (`SELECT commit_history, url FROM repository_url;`)
PR Checklist:
*   [x] Increase version numbers in …

Fix commit scraper no commits

---

docker-compose.yml
frontend/components/projects/edit/team/EditProjectTeamIndex.test.tsx
frontend/components/projects/edit/team/TeamMemberModal.tsx
frontend/components/projects/edit/team/index.tsx
frontend/components/software/edit/contributors/EditContributorModal.tsx
frontend/components/software/edit/contributors/EditSoftwareContributorsIndex.test.tsx
frontend/components/software/edit/contributors/__mocks__/softwareContributors.json
frontend/components/software/edit/contributors/index.tsx
frontend/jest.setup.js
frontend/package.json
frontend/package.json.license

Closes #677 
* In the contributor section of edit software, the user can cancel avatar removal in the Edit contributor modal
* In team member section of edit project, the user can cancel avatar removal in the Edit team member modal
* unit test are extended
How to test:
* `make start` to build everything and create test cases
* login as rsd_admin to be able to edit existing software/project, or create new software and project where you are admin of
* navigate to edit software, contributors section. If there are contributors with image, edit the contributor
* click on remove image button and then use CANCEL instead of SAVE. The avatar should not be removed
* repeat the process but when using SAVE the avatar image should be removed
* adding new …

677 cancel image delete

---

frontend/components/projects/edit/maintainers/ProjectMaintainersList.tsx
frontend/components/software/AboutLanguageItem.tsx
frontend/components/software/AboutLanguages.tsx
frontend/components/software/AboutSection.tsx

Closes #663 
* User with rsd_admin role is able to delete last maintainer of software or project
* Fix programming language link for GitHub and Other categorie, 
How to test:
* `make start` to build everything
* Login as professor 1 and create new software to become maintainer of the software
* Now login as rsd_admin. Check env variable RSD_ADMIN_EMAIL_LIST. In **env.example** professor3 is defined as rsd_admin
* Edit software you created, as rsd_admin you will be able to remove first maintainer
* The same should work with project maintainers
Use https://github.com/umple/umple as example:
PR Checklist:
*   [ ] Tests

663 delete last maintainer

---

database/100-create-api-views.sql
frontend/components/organisation/OrganisationNavItems.tsx
frontend/components/organisation/releases/ReleaseItem.tsx
frontend/components/organisation/releases/ReleaseNavButton.tsx
frontend/components/organisation/releases/ReleaseYear.tsx
frontend/components/organisation/releases/ScrollToTopButton.tsx
frontend/components/organisation/releases/index.tsx
frontend/components/organisation/releases/useSoftwareReleases.tsx
frontend/components/projects/edit/related/RelatedProjectList.tsx
frontend/components/projects/edit/related/RelatedSoftwareList.tsx
frontend/styles/global.css
frontend/types/Organisation.ts

Closes #708 
*  Additional section "Releases" is added to organisation page. It shows total release count, release count per year and list all releases .
* Each release contains two links that open in new tab: 
* link to software page on RSD, by clicking on software name
* link to DOI page of the relase (usually Zenodo page)
How to test:
* `make start` to build everything and create test cases
* `docker-compose down && docker-compose up` to restart with scrapers. We need release scraper to scrape info about releases
* After scraper is done it's work there will be releases listed. Before that the count will be 0 and page will message 'Nothing to show"
- The information used is provided by "release scraper". The contributors information is extracted …

Software release section for organisations

---

frontend/components/layout/ContributorPrivacyHint.tsx
frontend/components/projects/edit/team/EditProjectTeamIndex.test.tsx
frontend/components/projects/edit/team/SortableTeamMemberList.tsx
frontend/components/projects/edit/team/index.tsx
frontend/components/software/edit/contributors/EditSoftwareContributorsIndex.test.tsx
frontend/components/software/edit/contributors/SortableContributorsList.tsx
frontend/components/software/edit/contributors/index.tsx

Fixes #707
* Add an info box above the search form for adding team members (projects) or contributors (software)
* Example for contributors (same text for project team members):
* ![image](https://user-images.githubusercontent.com/14222414/216029104-59a37790-a00b-4ce1-984f-db6a2622af25.png)
Note: this PR depends on #712 and will be set to ready once #712 is merged.
How to test:
* Build and run
```
docker compose down --volumes && docker compose build --parallel && docker compose up
```
optionally add data
```
make data
```
* Login as a user
* Add or edit a software and go to Contributors, verify the info box above the search form
* Add or edit a project and go to team members, verify the info box above the search form
PR Checklist:
*   [ ] Increase …

707 Add terms of service info box

---

frontend/components/layout/ContributorPrivacyHint.tsx
frontend/components/software/CitationDoi.tsx
frontend/components/software/CitationDownload.tsx
frontend/components/software/CitationSection.test.tsx
frontend/components/software/CitationSection.tsx

Closes #719
* Labels changed as proposed in #719    
* Link to DOI page (opens in new tab) added as proposed in #719    
How to test:
* `make start` to rebuild everything
* `docker-compose down && docker-compose up` to start scrapers
* wait ca. 10min. to have release scraper do its job
* navigate to software page that has releases
* validate: 
* Copy DOI button works
* Download citation button works
* DOI link works
PR Checklist:
*   [x] Tests

Add link to release page of doi.org

---

frontend/components/cookies/CookieConsentMatomo.tsx

Closes #724 
*   Validate access to localStorage for Matomo consent cookie. If localStorage is not available Matomo tracking is disabled by default   
How to test:
* `make start` to build everything
* open RSD on localhost
* disable all cookies via browser settings
* RSD should still work. The info message will be generated in the console log
PR Checklist:
*   [ ] Tests

Fix: RSD crashing when all cookies are disabled

---

frontend/components/AppHeader/index.tsx
frontend/components/organisation/OrganisationNav.tsx
frontend/components/organisation/metadata/UnderlinedTitle.tsx
frontend/components/seo/getOrganisationSitemap.ts
frontend/components/seo/getProjectsSitemap.ts
frontend/components/seo/getSitemap.ts
frontend/components/seo/getSoftwareSitemap.ts
frontend/config/rsdSettingsReducer.ts
frontend/pages/organisations/[...slug].tsx
frontend/pages/organisations/index.tsx
frontend/pages/projects/index.tsx
frontend/pages/robots.txt.tsx
frontend/pages/sitemap/organisations.xml.tsx
frontend/pages/sitemap/projects.xml.tsx
frontend/pages/sitemap/software.xml.tsx
frontend/pages/software/index.tsx
frontend/public/robots.txt
frontend/public/robots.txt.license
frontend/utils/getDomain.ts

Closes #723
* Robots.txt uses host property to automatically determine current domain name. The default value is "localhost". The robots.txt file specifies the location of sitemap files
* The sitemap files are created for software, projects and organisations. Maximum length is set to 50.000 items per file. The location is:
* software: /sitemap/software.xml
* projects: /sitemap/projects.xml
* organisations: /sitemap/organisations.xml  
* The following props are included for each entry in sitemap.xml: 
* loc: location of the page
* lastmod: last modified date is based on `updated_at` 
*  Organisation page SEO: I added description to page head. Few other SEO suggestion were fixed based on Lighthouse page SEO audit.
How to test:
* `make start` to restart …

Create dynamic robots.txt and sitemaps

---

database/009-create-mention-table.sql
frontend/components/mention/EditMentionModal.tsx
frontend/components/mention/MentionEditFeatured.tsx
frontend/components/mention/MentionItemBase.tsx
frontend/components/mention/MentionItemFeatured.tsx
frontend/components/mention/MentionPublisherItem.tsx
frontend/components/mention/MentionViewItem.tsx
frontend/components/mention/config.ts
frontend/components/projects/edit/impact/EditProjectImpactIndex.test.tsx
frontend/components/projects/edit/output/EditProjectOutputIndex.test.tsx
frontend/components/software/edit/mentions/EditSoftwareMentionsIndex.test.tsx
frontend/tailwind.config.js
frontend/types/Crossref.ts
frontend/types/Mention.ts
frontend/utils/editMentions.ts
frontend/utils/getCrossref.ts
frontend/utils/getDataCite.ts
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/CrossrefMention.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/MentionRecord.java

* We collect, if it exists, the journal/book/book series a mention is published in and show it
How to test:
* Run the mention scraper a few times: `docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.doi.MainMentions`
* On http://localhost/api/v1/mention?select=journal some of the entries should have non-null values
* Login, create a software page and add mentions with the following DOIs: `10.1007/978-3-030-14350-3_5`, `10.1109/escience.2018.00013`, `10.1016/j.diin.2018.09.002`
* Look at the mentions both on the admin view as on the public view, all three should have a journal (`Published in …

feat: collect and show journal/book/book series of mentions

---

frontend/components/login/LoginButton.tsx
frontend/config/menuItems.ts
frontend/config/userMenuItems.tsx

Here are some minor improvements that I added to #630 a while ago. From my perspective it makes sense to merge them in a separate PR.
* do not show the "ORCID whitelist" in the admin user menu, if the RSD instance does not use ORCID as a login provider
How to test:
* `docker compose down --volumes && docker compose build --parallel`
* add `ORCID` to `RSD_AUTH_PROVIDERS` in your `.env`
* `docker compose up --scale scrapers=0`
* login as an administrator
* verify that the ORCID Whitelist menu entry appears
* `docker compose down`
* remove `ORCID` from `RSD_AUTH_PROVIDERS` in your `.env`
* `docker compose up`
* login as an administrator
* verify that the ORCID whitelist menu entry is not present anymore
PR Checklist: …

Hide ORCID Whitelist if ORCID is not used as a login provider

---

database/100-create-api-views.sql
frontend/components/organisation/releases/useSoftwareReleases.tsx

* Change some functions in Postgres, to improve their performance.We changed the functions form having a parameter, and thus only showing data for the given argument, to having no parameter, and thus showing all data, which is then restricted by an `ON` clause when joining.
How to test:
* Run the releases scraper a few times: `docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.doi.MainReleases`
* Visit some organisation pages and look at the releases. The correct number of releases should be shown on the left and per year. These pages should not be slow anymore.
* We will now test it out …

fix: improve performance of the slow function

---

database/009-create-mention-table.sql
database/100-create-api-views.sql
frontend/components/software/__mocks__/softwareReleases.json
frontend/utils/getSoftware.ts
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/DataCiteReleaseRepository.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/DataciteMentionRepository.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/MentionRecord.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/PostgrestMentionRepository.java

* For releases, we scrape the DOI registration timestamp, so that releases can be properly sorted, even if multiple releases were made on the same day
How to test:
* Login and add a software page with concept DOI `10.5281/zenodo.7638662`
* Run the releases scraper a few times: `docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.doi.MainReleases`
* http://localhost/api/v1/mention?select=doi_registration_date should have some non-null values
* Visit some organisation pages and look at the releases, they should be shown correctly
* Visit some software pages, including the one you made manually, …

fix: get DOI registration timestamp instead of date only for releases

---

authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java
authentication/src/test/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLoginTest.java

We have an issue where the home organisation of a user is not correctly determined. The reason is that we are looking for organisations in `eduperson_entitlement` where not necessarily the first organisation in the list represents the user's actual home organisation.
* fixes detection by comparing the organisation list delivered by the AAI with a list of known VOs/Centres
* sets the organisation to `Null` if no known organisation could be found
* sets the organisation to `Helmholtz` if user is a Helmholtz member but no known centre could be found in the entitlements
* adjust corresponding tests
How to test:
* `docker compose build auth`
* `docker compose up --scale scrapers=0`
* set `HELMHOLTZAAI_ALLOW_EXTERNAL_USERS=true` and login using a social …

fix: organisation detection for Helmholtz AAI

---

frontend/components/GlobalSearchAutocomplete/index.tsx
frontend/components/layout/ContributorPrivacyHint.tsx
frontend/components/projects/edit/team/index.tsx
frontend/components/software/edit/contributors/index.tsx

Closes #737
*   Placeholder text is changed from 'Search in RSD or jump to' to 'Search or jump to'. I believe we explicitly added RSD word to distinct between searches for organisation or contributors which do use external sources beside RSD.
*  Privacy hint info box, which previously was above input box of contributors/team members is moved below the input. I think this is more in line with other pages: mentions, output and impact.
How to test:
* confirm that global search placeholder is `Search or jump to...`
* navigate to software edit page, contributors. Confirm that info is below input box.
* navigate to project edit page, team. Confirm that info is below input box.
PR Checklist: …

Change global search placeholder text and privacy hint position

---

database/009-create-mention-table.sql
database/012-create-organisation-table.sql
database/100-create-api-views.sql
frontend/utils/getOrganisations.ts

* Change language of the function `organisations_overview`, and all its dependencies, from `PL/pgSQL` to `SQL`, so they can be inlined. This increases performance when only a subset of the columns or rows is requested.
* Adapt the frontend organisation overview page so that it only requests the columns it needs, in particular, don't request `release_cnt`, since this is an expensive operation.
How to test:
* Check http://localhost/organisations, and check various organisation pages
* Navigation should be quicker than on https://research-software.dev/organisations, which you can also see on the network tab of your browser's devtools.
PR …

fix: change RPCs to use SQL instead of PL/pgSQL to increase performance

---

Makefile
frontend/components/software/AboutLanguages.tsx

Fixes #754 
* do not display the "Programming language" if the stats array is empty (i.e. no information on languages exist)
* distinguish between one or multiple languages and adjust title (plural/singular)
* minor: adds a `clean` stage to the make fiel that runs `docker compose down --volumes`
How to test:
* create a new software A with repo url `https://git.gfz-potsdam.de/igmas/igmas-releases` (GitLab)
* create a new software B with repo url `https://github.com/wadpac/GGIR`
* create a new software C with repo url `https://github.com/research-software-directory/RSD-as-a-service`
* run the scraper `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar …

Improve display of "Programming languages" info

---

frontend/components/mention/MentionEditList.tsx
frontend/components/mention/MentionViewList.tsx

Closes #751 
* The mentions/output/impact item count per categorie shown in the badge is increased to 999. By default max is set to 99.     
How to test:
* Difficult to test, because tester needs to add 1000 items of same mention type to see `999+` label.
* See printscreen bellow, which is created by passing fake value in the state
PR Checklist:
*   [ ] Tests

fix: set maximum item count in the badge to 999

---

frontend/components/GlobalSearchAutocomplete/globalSearchAutocomplete.api.ts
frontend/utils/sortFn.test.ts
frontend/utils/sortFn.ts

Closes #749
*   Improved sort fn to order items by exact match first, then partial match closer to the left position in the string
How to test:
* create four additional software items: 'Xenon', 'Xenon gRPC server', 'Xenon command line interface' and 'PyXenon', then publish these items to be able to search for these
* use global search with the term `xenon`
* The order returned should be: Xenon (exact match), Xenon command line interface,  Xenon gRPC server, PyXenon, etc...
**Discussion point**
I reused JavaScript sort function to order items returned from api. In this case we might consider to extend RPC with order as we do not use this endpoint to dynamically change order.
PR Checklist:
*   [ ] Increase version numbers …

fix: order global search results by search term

---

data-generation/main.js
database/100-create-api-views.sql

For our RSD instance to be listed in helmholtz.cloud, we need to provide a couple of statistics to a public gitlab repository. Amongst these statistics, we need to know how many user accounts exist per centre. For this use case, we need a publicly available API endpoint that delivers this data.
* adds a `VIEW` named `user_count_per_home_organisation` that lists the amount of users by `home_organisation`
* create fake accounts and login_for_account in `data-generation` (one `login_for_account` per `account`)
How to test:
* `docker compose down --volumes && docker compose build --parallel && docker compose up --scale scrapers=0 --scale data-generation=1`
* open http://localhost/api/v1/user_count_per_home_organisation and verify that it returns a json …

Adds API view for user count by home_organisation

---

database/100-create-api-views.sql

* Change the `releases_by_organisation` function in the database so that it deduplicates releases
How to test:
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --scale data-generation=0`.
* Login as admin, create a software page with concept DOI `10.5281/zenodo.6379973`, add it to some organisation
* Run the releases scraper once: `docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.doi.MainReleases`
* Create a research unit of the organisation you added above
* Add the software to that research unit as well
* Visit the releases of the parent organisation, each release should only be listed once
* If you want, you can (using DBeaver for example), replace the new function …

fix: select distinct releases per organisation

---

frontend/styles/rsdMuiTheme.ts

We are using different button capitalization across the application. Some buttons have capitalized text, and some others do not. This PR sets to non-capilazied buttons by default in the MUI theme provider.
PR Checklist:
*   [ ] Tests

Remove default for capitalized buttons

---

.github/workflows/e2e_tests_macos.yml
.github/workflows/e2e_tests_ubuntu.yml
Makefile
docker-compose.yml
e2e/.dockerignore
e2e/Dockerfile
e2e/docker-compose.yml
e2e/helpers/userAgreement.ts
e2e/helpers/utils.ts
e2e/mocks/mockOrganisation.ts
e2e/package-lock.json
e2e/package.json
frontend/package.json

* Playwright upgrade to v1.31
* PR action to run e2e test in chrome only
* Original  e2e tests ubuntu action can be runned manually on any branch (see Actions)
* Additional e2e tests firefox action can be runned manually on any branch (see Actions) 
* Local e2e tests (make e2e-tests) are runned in chrome, firefox and msedge
* MacOS e2e tests action is extended to cache playwright browser installation. Note! MacOS e2e tests run RSD on dev server (not local)
How to test:
* `make e2e-tests` the test should run without errors in chrome, firefox and msedge
* Github action runned e2e tests in chrome only on this PR already (see Checks)
* You can try running some of e2e tests actions manually
PR Checklist: …

Upgrade playwright to 1.31

---

database/100-create-api-views.sql

Related to #763, this PR adds one more RPC call that will return the number of new accounts since a given date.
* adds `new_accounts_count_since_timestamp(timestmp)` that can be queried via a POST request without authentication
How to test:
* `docker compose down --volumes && docker compose build --parallel && docker compose up --scale scrapers=0 --scale data-generation=1`
* Make a POST request with curl, e.g.
```
curl "http://localhost/api/v1/rpc/new_accounts_count_since_timestamp" \
-X POST -H "Content-Type: application/json" \
-d '{"timestmp":"2023-03-03 00:00:00.0000"}'
```
Which should return 100, that is equal to the amounts of accounts created with the data-generation script
PR Checklist: …

feat: add rpc new_accounts_count_since_timestamp

---

frontend/components/AppFooter/ContactEmail.tsx
frontend/components/AppFooter/index.tsx
frontend/config/rsdSettingsReducer.ts
frontend/public/data/settings.json

To optimise the handling of mails we receive in our helpdesk, we would like to add default subjects to the mail links in our RSD instance.
This PR adds the ability to add headers to the eMail link in the app footer.
* adds an optional `emailHeaders: []` to `settings.json` that will be used to construct the mailto link in the app footer
How to test:
* `docker compose build --parallel && docker compose up --scale scrapers=0`
* open http://localhost and verify that the email link in the app footer does not contain any extra headers
* add headers to `emailHeaders`, e.g.
```yml
"emailHeaders": ["subject=Default subject", "body=Default body"`],
```
* `docker compose down && docker compose build frontend && docker compose up --scale scrapers=0`
* verify …

feat: configurable headers for mailto links

---

frontend/components/admin/orcid-users/AddOrcidUser.tsx
frontend/components/layout/EditPageButton.tsx
frontend/components/layout/ViewPageButton.tsx
frontend/components/organisation/units/ResearchUnitModal.tsx
frontend/components/projects/edit/impact/AddImpact.tsx
frontend/components/projects/edit/impact/EditProjectImpactIndex.test.tsx
frontend/components/projects/edit/information/AutosaveFundingOrganisations.tsx
frontend/components/projects/edit/information/AutosaveProjectLinks.tsx
frontend/components/projects/edit/information/AutosaveResearchDomains.tsx
frontend/components/projects/edit/output/AddOutput.tsx
frontend/components/projects/edit/output/EditProjectOutputIndex.test.tsx
frontend/components/projects/edit/team/EditProjectTeamIndex.test.tsx
frontend/components/projects/edit/team/TeamMemberModal.tsx
frontend/components/software/edit/contributors/EditContributorModal.tsx
frontend/components/software/edit/contributors/EditSoftwareContributorsIndex.test.tsx
frontend/components/software/edit/information/AutosaveConceptDoi.tsx
frontend/components/software/edit/information/AutosaveRemoteMarkdown.tsx
frontend/components/software/edit/mentions/AddMention.tsx
frontend/components/software/edit/mentions/EditSoftwareMentionsIndex.test.tsx
frontend/components/software/edit/organisations/EditOrganisationModal.tsx
frontend/pages/logout.tsx

* We decided to remove "uppercase" button formatting from mui button component.
* Some of the button labels were not starting with the capital letter (as it was not required)
* By further inspection of pages, I discovered that funding organisation chip with very long organisation name would break the layout. This is also fixed in this PR
How to test:
* login as rsd_admin (proferssor3 if you have same definitions in .env file as I have). 
* Create software, examine buttons on add software page
* On edit software page confirm all buttons in all sections have desired "casing".
* Create project, examine buttons on add project page
* On edit project page confirm all buttons in all sections have desired "casing".
* Navigate to …

Correct lower case button labels

---

frontend/Dockerfile.dev

This commit by @seth0r fixes some issues when detecting ownership in the frontend Docker container.
This PR changes:
- excludes /sys, somtimes there are io errors
- if group id already used, changing the primary group of user
How to test:
* `make frontend-docker` and verify that the files that are generated by this container have the owner of the currently logged in user of the host system
PR Checklist:
*   [ ] Tests

fix: ownership changes

---

database/100-create-api-views.sql
frontend/components/software/edit/information/AutosaveRepositoryUrl.tsx

Fixes #781 
* automatically suggest a code platform based on currently publicly visible software entries
* if there exist several repositories referring to the same host, but set to different code platforms, the code platform with the most references will be suggested
How to test:
* `docker compose down --volumes && docker compose build --parallel && docker compose up --scale scrapers=0`
* login as normal user
* create a new software entry, e.g. using url `https://something.com/test1` and specifiy GitLab; publish the software entry
* create a new software entry and type (not copy paste) `https://something.com/test2` into the url field. The platform should be suggested as soon as `https://something.com/` is typed into the field; publish the entry
PR …

feat: suggest code platform based on existing entries

---

README.md
documentation/docs/getting-started.md

Fixes https://github.com/research-software-directory/RSD-as-a-service/issues/796
* Update the README and the Getting Started section of the documentation to include `make` and `yarn` as dependencies.
* Documentation gets built correctly with `make dev` but I had to run `yarn install` in the docs folder, first. This updated `yarn.lock` and created a couple of other `yarn` related files. I've not committed those files, but let me know if you want them.
How to test:
* Just check if the documentation is there.
PR Checklist:
*   [x] Tests

Specify required dependencies in documentation

---

frontend/__tests__/SoftwareEditPage.test.tsx
frontend/components/projects/add/AddProjectCard.test.tsx
frontend/components/projects/add/AddProjectCard.tsx
frontend/components/projects/add/addProjectConfig.ts
frontend/components/software/add/AddSoftwareCard.test.tsx
frontend/components/software/add/AddSoftwareCard.tsx
frontend/components/software/add/addConfig.ts
frontend/components/software/edit/editSoftwareConfig.tsx

Closes #798
* Use null for missing value when creating software
* Use null for missing value when creating project
* Subtitle is not required prop for software
* Min value is set to 3 charts
* Tests are updated
How to test:
* login as user 
* create new software without subtitle and verify that `short_statement` property has null value instead of ""
* create new project without subtitle and verify that `project_subtitle` property has null value instead of ""
PR Checklist:
*   [x] Tests

fix: add software, project use null instead of empty string

---

frontend/components/mention/BulkImport.tsx
frontend/components/projects/edit/impact/BulkImportImpact.tsx
frontend/components/projects/edit/impact/FindImpact.tsx
frontend/components/projects/edit/impact/index.tsx
frontend/components/projects/edit/output/BulkImportOutput.tsx
frontend/components/projects/edit/output/FindOutput.tsx
frontend/components/projects/edit/output/index.tsx
frontend/components/software/edit/mentions/BulkImportMentions.tsx
frontend/components/software/edit/mentions/FindSoftwareMention.tsx
frontend/components/software/edit/mentions/index.tsx
frontend/components/software/edit/mentions/utils.ts
frontend/utils/editMentions.ts
frontend/utils/getCrossref.ts
frontend/utils/getDOI.ts
frontend/utils/getDataCite.ts

* When a search term contains a DOI anywhere (URL or not), it is detected and we will search on that DOI only (#745)
* Bulk import of mentions with a DOI, up to 75 a time (#786)
* Remove double spaces when searching for a mention title (#795)
How to test:
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --scale data-generation=0`.
* Login, create a software page, go to mentions and add the following list:
```
https://doi.ieeecomputersociety.org/10.1109/PMBS56514.2022.00010
10.5281/zenodo.3734289doesnotexist
not a DOI
10.5281/zenodo.3734289   
10.5281/zenodo.5604609
10.1016/j.sleep.2019.02.008   
10.2139/ssrn.4090562
10.1109/eScience.2016.7870882
10.3389/fmars.2021.667591
10.5281/zenodo.3993242 …
```

Mention feedback

---

frontend/pages/organisations/[...slug].tsx

Fixes #821
* Meta data description on the organisation page:
* uses the value from organisation description (later should be updated to short_description)
* if description is null then the following text is generated:
`{OrganisationName} participates in the RSD with X software package(s) and Y project(s).`
How to test:
* navigate to organisation page and paginate until you find an organisation with 0 software items.
* navigate to page, open developer tools (usually F12), Elements tab (see printscreen). Confirm that html head has meta tag description with the appropriate content (uses 0 instead of null) 
PR Checklist:
*   [ ] Update …

fix: meta description of organisation uses 0 instead of null when no software packages

---

frontend/components/projects/edit/__mocks__/editProjectState.ts
frontend/components/projects/edit/editProjectContext.tsx
frontend/components/projects/edit/editProjectReducer.tsx
frontend/components/projects/edit/information/AutosaveProjectImage.test.tsx
frontend/components/projects/edit/maintainers/index.tsx
frontend/components/projects/edit/team/useTeamMembers.tsx
frontend/components/projects/edit/useProjectContext.tsx
frontend/components/software/edit/editSoftwareContext.tsx
frontend/components/software/edit/editSoftwareReducer.tsx
frontend/components/software/edit/information/AutosaveSoftwareTextField.tsx
frontend/components/software/edit/useSoftwareContext.tsx
frontend/pages/projects/[slug]/edit/[page].tsx
frontend/pages/software/[slug]/edit/[page].tsx

Closes #825
* When concept_doi is changed it should be shared among edit pages using the software context
* Software and project edit context state is slightly refactored to beter reflect dynamic edit page routes we recently applied
How to test:
* create new software and provide concept_doi
* navigate to contributors, import button should be shown
* navigate back to information and change concept_doi
* navigate back to contributors and import again...the contributors of new concept_doi should be imported
* "briefly" validate that all other software edit page features work properly (we did slight refactor)
* "briefly" validate that all edit project page feature work properly (same refactor is applied on share edit project …

825 fix: update concept_doi in software context

---

database/100-create-api-views.sql
database/103-software-views.sql
database/105-project-views.sql
e2e/helpers/userAgreement.ts
frontend/pages/projects/index.tsx
frontend/pages/software/index.tsx
frontend/utils/postgrestUrl.test.ts
frontend/utils/postgrestUrl.ts

Closes #828
* The card order on project overview page is set on start date and project status by default etc. When search term is applied this order is not logical. More logical order is "best match" of used search term in project title or subtitle.
* The card order on software overview page is set on mentions and contributors count by default. When search term is applied this order is not logical. More logical order is "best match" of used search term in project title or subtitle.
* To facilitate logical order when search is used we introduced new rpc with built in order when search is used.
How to test:
* navigate to project overview page. Use search for `project: a`, the software with matching title should be listed …

828 fix: change order to title when search value is provided

---

.github/workflows/all_tests.yml
.github/workflows/e2e_tests_chrome.yml
.github/workflows/e2e_tests_firefox.yml
.github/workflows/e2e_tests_ubuntu.yml
frontend/pages/software/index.tsx

We created rpc for software search which implements order on the best match of used search term.
* Remove FE order from software overview page
* Update all_test CI action to use only e2e tests in chrome (improved performance and reliability)
* Do not install firefox in e2e chrome action (not needed)      
How to test:
* navigate to software and use search. The order of "cards" should be by best match on used search term
* manually run all_test action from github actions
PR Checklist:
*   [ ] Tests

Remove order from software overview FE code

---

authentication/src/main/java/nl/esciencecenter/rsd/authentication/PostgrestAccount.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Utils.java
database/020-row-level-security.sql
docker-compose.yml

* On every login, we update the `name`, `email` and `home_organisation` fields on the `login_for_account` table
* Remove update and insert rights on the `login_for_account` table
How to test:
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --scale data-generation=0`  
* Login in your preferred way (or try them all out)
* Using something like DBeaver, run `SELECT * FROM login_for_account;`
* Now remove the values: `UPDATE login_for_account SET name = NULL, email = NULL, home_organisation = NULL;`
* Login again with the same credentials, the values should be restored (see the `SELECT` statement above)
Closes #607
PR Checklist:
*   [X] Increase version numbers in `docker-compose.yml`
*   [X] Link to a GitHub …

607 profile name

---

data-generation/main.js
database/105-project-views.sql
frontend/components/user/UserNavItems.tsx
frontend/components/user/project-quality/FullScreenTable.tsx
frontend/components/user/project-quality/SortableTable.tsx
frontend/components/user/project-quality/apiProjectQuality.tsx

* Implement all requested features in #804 except column reordering and an overview for software
* The data generation script now only assigns a grant ID in 80% of the time
How to test:
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --scale data-generation=1`  
* Login as an admin and visit http://localhost/user/project-quality
* Check that the columns with `Start date`, `End date`, `Grant ID`, `Related software`, `Related projects` are correct
* Check that numerical values that were `0` now have a red cross
Related to #804
PR Checklist:
*   [ ] Tests

804 project overview improvements

---

.github/workflows/all_tests.yml
.github/workflows/backend_tests.yml
.github/workflows/e2e_tests_chrome.yml
.github/workflows/e2e_tests_firefox.yml
.github/workflows/e2e_tests_ubuntu.yml
Makefile
README.md
backend-postgrest/tests/README.md
backend-postgrest/tests/docker-compose.yml
data-generation/main.js
data-migration/README.md
deployment/.gitignore
deployment/README.md
deployment/docker-compose.yml
docker-compose.yml
documentation/docs/getting-started.md
e2e/README.MD
frontend/README.md

* Switch from `docker-compose` to the `docker compose` CLI plugin, see #830 for more info
* Some small textual improvements in the documentation
How to test:
* Follow the installation instructions linked in #830 to install the `docker compose` CLI plugin
* Check that the various commands in the `Makefile` still work, e.g. `make e2e-tests` and `make start`
* Check that I updated the documentation and scripts everywhere, by e.g. doing a global regex-enabled search on `docker-compose(?!\.yml)` (this finds `docker-compose` but not if it is `docker-compose.yml`). I skipped the `data-migration` directory on purpose since it is deprecated.
Closes #830
PR Checklist:
* …

build: replace docker-compose with the docker compose CLI plugin

---

frontend/components/admin/software-highlights/apiSoftwareHighlights.tsx
frontend/components/software/overview/SearchInput.tsx
frontend/components/software/overview/SoftwareCard.tsx

Closes #841
* When image_id is not provided the image section of software card is not used
* Order descending is also fixed in rsd-v2-release branch during rebasing
* Input delay increased from 400 to 700 ms in order to avoid request (and page jump) when "slow" typing :-)
* Removed unused import
How to test:
* login as rsd_admin
* navigate to admin page software-highlights. Edit one of the highlight items and remove image/logo
* visit [highlights page](https://localhost/highlights). The card should be displayed without image section (see example)
* search for that same software in overview. The card should also be displayed without image section (see example)
* validate order is descending when using filter on highlights …

fix: support software card without image

---

frontend/components/organisation/projects/index.tsx
frontend/components/organisation/software/OrganisationSoftwareCards.tsx
frontend/components/organisation/software/index.tsx
frontend/pages/organisations/index.tsx
frontend/pages/projects/index.tsx
frontend/pages/software/index.tsx
frontend/utils/usePaginationWithSearch.tsx

Closes #829
* Adding pagination at the bottom of software and project pages on organisation page.
* Use same bottom margin on software, projects and organisation overview pages    
How to test:
* navigate to organisation overview
* select one of organisations and confirm that:
- software page has pagination at the bottom of the page
- projects page has pagination at the bottom of the page
PR Checklist:
*   [ ] Tests

Add pagination for software and projects on organisation page

---

frontend/pages/invite/organisation/[id].tsx
frontend/utils/editOrganisation.test.ts
frontend/utils/editOrganisation.ts

Closes #859
*  Provides direct link to organisation page after maintainer is added to list of organisation maintainers    
How to test:
* login as rsd_admin (professor3 if you use same .env file as me) 
* navigate to organisation and create maintainer invite link. Send or copy link to use it and next step.
* Logout from rsd. Paste link in the addressbar. You will receive message that you need to login first.
* Login as professor1 now. 
* You will see confirmation page with the working link to a organisation page
* Click the link and confirm that organisation page is loaded and you are the maintainer.
PR Checklist:
*   [ ] Update …

Fix: missing organisation slug on maintainer invite confirmation page

---

frontend/components/organisation/settings/RsdAdminSection.tsx
frontend/components/organisation/settings/index.tsx

Closes #855
*  The organisation maintainer can edit about page of the organisation. Previously this was only possible for rsd_admin role   
How to test:
* login as rsd_admin (professor3 if you have same settings as I do)
* navigate to settings. You should see about page in settings. 
* navigate to organisation maintainers and create an invite. Copy link and then logout.
* paste link and login as professor1
* navigate to settings. You should see About page section.
* Add some text to About page. 
* Log out and visit organisation as public user. You should see the content of about page.
PR Checklist:
*   [ ] …

feat: organisation maintainer can edit about page

---

frontend/components/mention/__mocks__/mentions.json
frontend/components/mention/__mocks__/mentions.json.license
frontend/components/software/edit/information/ValidateConceptDoi.test.tsx
frontend/components/software/edit/information/ValidateConceptDoi.tsx
frontend/utils/getDataCite.ts
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/DataCiteReleaseRepository.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/DataciteMentionRepository.java

* The frontend uses `relatedIdentifiers` instead of `versionOfCount` to detect if an entered DOI is a concept or version DOI
* The scraper uses the same to scrape the versions
How to test:
* `docker compose down --volumes && docker compose build --parallel && docker compose up --scale data-generation=0`  
* Login and create software pages with the following concept DOIs (they should also be validated properly):
* 10.5281/zenodo.7137566
* 10.5281/zenodo.5751860
* 10.5281/zenodo.1404735
* Let the scraper run (`docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.doi.MainReleases`)
* Check that the first two have one version, and that the third has 14 versions (especially `1.3.0` and `1.4.0`)
* Try to validate the …

782 version dois

---

backend-postgrest/Dockerfile
docker-compose.yml

* Upgrade to version [v11.0.1](https://github.com/PostgREST/postgrest/releases/tag/v11.0.1) of PostgREST
How to test:
* Check that the end to end tests still work: `make e2e-tests`
* Check that the backend tests still work, see [here](https://github.com/research-software-directory/RSD-as-a-service/blob/main/backend-postgrest/tests/README.md)
* Login as an admin, create a maintainer invite for an organisation
* Login as a regular user and accept the invite
* Browsing sections on that page should have normal speed again
* Since this is a major upgrade of PostgREST, check that other functionality still works
Closes #863
PR Checklist:
* …

863 slow org page

---

data-generation/main.js

* Data generation now makes an about page
How to test:
* http://localhost/page/about should exist
Closes #863
PR Checklist:
*   [ ] Tests

fix: data generation now makes an about page

---

.env.example
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Config.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Main.java
authentication/src/test/java/nl/esciencecenter/rsd/authentication/MainTest.java
deployment/docker-compose.yml
docker-compose.yml

Fixes #857 
* fixes handling of `eduperson_entitlement`
* adds an allow list for Helmholtz AAI via env variable `HELMHOLTZAAI_ALLOW_LIST`
* users in allow list are identified via email address
* enable usage of allow list via `HELMHOLTZAAI_USE_ALLOW_LIST`
* enable external debugging in auth container
How to test:
* enable Helmholtz AAI login provider and in `.env` set
* `HELMHOLTZAAI_ALLOW_EXTERNAL_USERS=false`
* `HELMHOLTZAAI_USE_ALLOW_LIST=false`
* `docker compose build --parallel && docker compose up --scale scrapers=0`
* login via Helmholtz AAI using a social IdP (Google, ORCID or GitHub)
* check that auth does not log any errors
* the user will be presented the error message: "You are not allowed to login."
* `docker compose stop`
* in `.env` …

fix: Helmholtz AAI handling if only one eduperson_entitlement is returned

---

frontend/components/software/edit/organisations/EditOrganisationModal.tsx

When users in the Helmholtz RSD add new organisations, they usually add them without uploading logos. We would like to add a hint so that they are aware that they have the chance to add a logo once while adding the organsiation.
* Adds a hint to `EditOrganisationModal` so that users understand that they can upload a logo now, but not later
How to test:
* `docker compose build && docker compose up --scale scrapers=0`
* reference a new organisation in a software entry
PR Checklist:
*   [ ] Tests

feat: add a hint to upload organisation logos

---

database/012-create-organisation-table.sql
e2e/helpers/citations.ts
e2e/helpers/utils.ts
frontend/components/software/edit/organisations/FindOrganisationItem.tsx
frontend/utils/editOrganisation.ts

Closes #876 
* Show organisation path in the find organisation list item
* Remove source RSD/ROR
* Show website if present
* Show ROR id (url) if present   
How to test:
* `make start` to build app and generate data
* login as rsd_admin in order to be able to change items
* select first organisation and create some research units
* select first software and edit organisations. Search for the unit. The find organisation list should be in new layout showing the organisation parents separated by `>` to indicate level
PR Checklist:
*   [ ] Tests

876: New layout add organisation list

---

frontend/components/software/ParticipatingOrganisation.tsx
frontend/components/software/edit/organisations/FindOrganisationItem.tsx

Closes #875 
*   Show research unit name below logo on the software and project page   
How to test:
* login as rsd_admin in order to be able to change existing data
* navigate to organisation and add few research units
* select one of its software and add research units
* view the software page and confirm unit name is shown next to logo as in picture above
PR Checklist:
*   [ ] Tests

875: show research unit name on software/project pages

---

scrapers/src/main/java/nl/esciencecenter/rsd/scraper/Utils.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/GitlabScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/DockerHubScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/PackageManagerScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/PypiScraper.java

* All HTTP requests of the scrapers now have a timeout, which is triggered when the headers of the request have not been received by that time.
How to test:
* Check that the scrapers still work
* Check in the code that I didn't forget to add a timeout somewhere
PR Checklist:
*   [ ] Tests

fix: add a request timeout on all HTTP requests

---

database/100-create-api-views.sql

Closes #898
*  Global search shows only top level organisations not children (research units)    
How to test:
* login as rsd_admin in order to manipulate organisations
* select first organisation from the overview and add 1 or 2 research units
* try to find these units using global search. These should not be found.
* try top level organisation. It should be found. Open the page and confirm that organisation has research unit with the name used during search
PR Checklist:
*   [ ] Tests

fix: search only for top level organisation in global search

---

frontend/components/form/AutosaveControlledTextField.tsx
frontend/components/form/ControlledTextField.tsx
frontend/components/organisation/settings/AutosaveOrganisationTextField.tsx
frontend/components/projects/edit/information/AutosaveProjectPeriod.tsx
frontend/components/projects/edit/information/AutosaveProjectTextField.tsx
frontend/components/software/edit/information/AutosaveRemoteMarkdown.tsx
frontend/components/software/edit/information/AutosaveRepositoryUrl.tsx
frontend/components/software/edit/information/AutosaveSoftwareTextField.tsx

Closes #897
* Show warning under start and end date input when end date is before start date
* Save both values at the same time when input is valid (on lost focus)
How to test:
* `make start` to build app create test data
* login as rsd_admin to be able to manipulate existing project
* select first project from overview and edit project period
* select end date which is before start date. The error should appear (see image)
* correct end date and error should be removed
* select start date to be after end date. The error on end date should appear
PR Checklist:
*   [ ] Tests

fix: warn when project end date is before start date

---

.github/workflows/all_tests.yml
.github/workflows/backend_tests.yml
Makefile
backend-postgrest/tests/README.md
backend-tests/.gitignore
backend-tests/Dockerfile
backend-tests/README.md
backend-tests/docker-compose.yml
backend-tests/pom.xml
backend-tests/src/test/java/nl/esciencecenter/AuthenticationIntegrationTest.java

* Postman tests are replaced by full code tests written in Java as a Maven project
* Main libraries are [REST Assured](https://rest-assured.io/) and [JUnit 5](https://junit.org/junit5/)
* Not all tests were migrated
* Add deprecation note on the old README but keep the folder so the old tests can still be found
How to test:
* Read the new `README.md` and check if the instructions are clear enough for you to be able to run the new tests 😉
* Check if any essential tests are missing
Closes #813
PR Checklist:
*   [x] Tests

Replace postman tests

---

database/003-create-software-table.sql

As part of the ongoing discussions to contribute to the RSD, here is the first step towards adding explicit support for open/close source software.
Fixes https://github.com/ImperialCollegeLondon/RSD-as-a-service/issues/12
* In this case, it is a simple flag in the DB to indicate if a piece of software is open source or not. This flag could then be used in the front end (down the line) to require mandatory fields for open/close source or to show/hide certain parts of the page.
How to test:
* (Not testable, yet)
PR Checklist:
*   [ ] Tests
I understand that there should be a migration in the dB in order to apply these changes. However, …

Add closed_source flag to database

---

frontend/components/layout/ContentContainer.tsx
frontend/components/software/overview/SoftwareHighlights.tsx
frontend/components/software/overview/cards/SoftwareMasonryCard.tsx

Closes #932 
Closes #935 
* Improved alignment of stats of masonry card (bottom right) - see image
* Added "Software Highlights" - see image
How to test:
* visit software overview page, select masonry layout (if not selected)
* Confirm alignment of stats at the bottom right of the card
* If highlights are defined, confirm that Software Hightlights has title. Then login as rsd_admin and remove all highlights. The highlights section including the title should not be shown
* If highlights are not defined, eg. highlights section is not visible: Login as rsd_admin and define highlights in the admin section first. Then confirm section including the title is visible
PR Checklist:
*   [ ] Increase version …

932 & 935 Software overview page improvements

---

database/Dockerfile
docker-compose.yml

* Upgrade from Postgres 14.2 to 15.3
How to test:
* We will first create some data on 14.2:
* `git switch main && docker compose down --volumes && docker compose build --parallel && docker-compose up --scale data-generation=1`
* Login as a regular user, make a software and project page
* Make a backup (if you changed your `.env`, substitute the correct values):
* `docker compose exec database pg_dump --format=tar --file=rsd-backup.tar --username=rsd --dbname=rsd-db`
* Copy over the backup to your local file system:
* `docker compose cp database:rsd-backup.tar rsd-backup.tar`
* Now we will delete the old database and switch to the new version:
* `docker compose down --volumes && git switch 943-postgres-15 && docker compose build --parallel && …

feat: upgrade to postgres 15

---

.github/workflows/frontend_tests.yml

* Adding linter check to CI to run on PR when fe code changed
How to test:
*  After merging into main the linter check for frontend will run on each PR
PR Checklist:
*   [ ] Tests

ci: run separate eslint check before unit tests and build test

---

frontend/assets/logos/logo-orcid.svg
frontend/components/GlobalSearchAutocomplete/index.tsx
frontend/components/feedback/FeedbackPanelButton.tsx
frontend/components/form/Searchbox.tsx

This PR implements a number of minor tweaks to improve accessibility based on analysis carried out using [pa11y](https://github.com/pa11y/pa11y) with the default runner. This flagged a number of minor issues that . The majority changes related to aria attributes that were missing or possibly not kept up to date. The changes to the svg remove the embedded id attribute to prevent html elements with duplicate ids being rendered on the page.

Accessibility Improvements

---

frontend/sonar-project.properties

* Do not analyse test, mocks and assets folders
* Define all test files   
How to test:
* De sonar analyses should now exclude large number of irrelevant files from it's analyses.
PR Checklist:
*   [ ] Tests

chore: exclude test and mock files from sonar code analyses

---

database/002-create-image-table.sql
docker-compose.yml
frontend/Dockerfile
frontend/auth/api/useLoginProviders.tsx
frontend/components/AppHeader/index.tsx
frontend/components/layout/ImageWithPlaceholder.tsx
frontend/components/layout/LogoAvatar.tsx
frontend/components/login/LoginButton.tsx
frontend/components/projects/edit/impact/EditProjectImpactIndex.test.tsx
frontend/components/projects/edit/impact/ImportProjectImpact.tsx
frontend/components/projects/edit/impact/useImpactForProject.tsx
frontend/components/projects/edit/output/EditProjectOutputIndex.test.tsx
frontend/components/projects/edit/output/ImportProjectOutput.tsx
frontend/components/projects/edit/output/useOutputForProject.tsx
frontend/components/projects/overview/list/ListImageWithGradientPlaceholder.tsx
frontend/components/projects/overview/list/ProjectListItemContent.tsx
frontend/components/software/edit/mentions/ImportSoftwareMentions.tsx
frontend/components/software/edit/mentions/useMentionForSoftware.tsx
frontend/components/software/overview/cards/SoftwareMasonryCard.tsx
frontend/components/software/overview/highlights/HighlightsCard.tsx
frontend/components/software/overview/highlights/HighlightsCarousel.tsx
frontend/components/software/overview/list/SoftwareListItemContent.tsx
frontend/package.json
frontend/pages/api/fe/auth/index.ts
frontend/pages/projects/[slug]/index.tsx
frontend/pages/software/[slug]/index.tsx
frontend/utils/editMentions.ts
frontend/utils/getProjects.ts

Closes #955
* loading mentions on the software and project page api is changed to more performant api requests. (reduced from ~300ms to ~50ms)
* auth endpoint response is improved to cache the list of login providers on initial load instead of reading it on each request (reduced from ~500ms to ~10ms after initial request).
* fix cumulative layout shift on software overview page when highlights section is used
* bump the node version to v20 in the fe image. Node v20 is going to be LTS version from October 2023, so we should switch from v18 to v20 asap. Advice to FE developers, use [nvm](https://github.com/nvm-sh/nvm) to manage multiple node versions on your machine. 
* apply fixes advised by Lighthouse audit: increase image cache to 1yr and provide …

955 improve performance

---

frontend/components/GlobalSearchAutocomplete/index.tsx
frontend/components/menu/IconBtnMenuOnAction.tsx
frontend/components/organisation/metadata/OrganisationLogoMenu.tsx

Closes #976
*  Add aria labels to admin buttons on organisation page
How to test:
*  `make start` to build complete solution
*  login as rsd-admin role. If you use same .env as mine you can login as `professor3`
*  navigate to organisation page as admin
*  run Lighthouse audit on the page. The score should be improved and there will be no messages about buttons missing accessible name (see image bellow).
* Note! the score will probably not be that high on your local machine because ssl + http2  is not enabled at localhost.
PR Checklist:
*   [ ] Tests

lighthouse: add arial labels to admin buttons.

---

database/118-backend-logs-views.sql
frontend/components/AppHeader/index.tsx
frontend/components/admin/AdminNav.tsx
frontend/components/admin/AdminPageWithNav.tsx
frontend/components/admin/logs/DeleteOldLogsBtn.tsx
frontend/components/admin/logs/ErrorInfoCell.tsx
frontend/components/admin/logs/LogsTable.tsx
frontend/components/admin/logs/__mocks__/apiLogs.ts
frontend/components/admin/logs/apiLogs.ts
frontend/components/admin/logs/config.tsx
frontend/components/admin/logs/index.tsx
frontend/components/admin/logs/useLogs.tsx
frontend/components/admin/rsd-contributors/config.tsx
frontend/components/table/EditableTable.tsx
frontend/components/table/TableBody.tsx
frontend/components/table/TableHeader.tsx
frontend/pages/admin/logs.tsx
frontend/styles/rsdMuiTheme.ts
frontend/utils/dateFn.ts

Related to #171 
* Created error logs page in the admin section
* Page lists all error logs
* Admin can order and search logs
* Admin can refresh table using reload icon
* Admin can remove each item separately
* Admin can remove logs older than 30 days.
* Error info column shows error message, response data (icon {}), stack trace (! icon), reference key and the link to edit software page where error can be fixed. The user can copy response data and stack trace.
How to test:
* Let scrapers run for some time. You need to restart with scrapers enabled `docker compose down && docker compose up -d`
* Wait for 15-30 minutes for scrapers to generate some errors.
* Login as admin `professor3` if you have same settings in .env …

171 add scraper error logs page to admin section

---

frontend/components/organisation/overview/card/OrganisationCard.tsx

*   Prevent enlarging of organisation images/logo's with very small dimensions. See examples from [live RSD on dev](https://research-software.dev/organisations?page=4&rows=12)
* The similar scaling is applied to software card logo's previously. The look of "larger" images in the card remains unchanged.
How to test:
* `make start` to build
* login as rsd admin
* navigate to organisations overview. the logos should look nice.
* change the organisation logo to a very small image. The logo in the card should be sharp but small, not large and blurry (see example).
PR Checklist:
*   [ ] Tests

fix: prevent blurry logo image in the organisation card

---

frontend/components/software/edit/editSoftwareConfig.tsx
frontend/components/software/edit/information/AutosaveRepositoryUrl.tsx
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/GithubScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/MainBasicData.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/MainCommits.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/MainContributors.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/MainProgrammingLanguages.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/git/GithubScraperTest.java

* The scrapers now only attempt to scrape a GitHub repo if the URL points to the root of a single repository, reducing the amount of error logs generated.
* Add a warning to the maintainer page if a GitHub repo URL seems not to be valid.
How to test :
* Create a software page, publish it, and enter `https://github.com/research-software-directory/RSD-as-a-service/issues` as repo URL. This should generate a warning in orange text but should succeed.
* Run the varous Git scrapers (or wait for them to run):
* `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainProgrammingLanguages`
* `docker …

949 GitHub url check

---

frontend/auth/locationCookie.test.ts
frontend/auth/locationCookie.ts

Closes #1005
* Save redirect link to include order on mentions on the software overview page   
* Update the test
How to test:
* navigate to homepage
* use sign in to login
* your should be redirected to software page and order should be applied (mentions)
PR Checklist:
*   [x] Tests

fix: redirect to ordered software overview on login

---

frontend/components/software/edit/editSoftwareConfig.tsx
frontend/components/software/edit/information/AutosaveRepositoryPlatform.tsx
frontend/components/software/edit/information/AutosaveRepositoryUrl.tsx

* Always show the correct helper text when updating the repository URL or the Git platform.
How to test :
* Test out the use cases in #999 and try out other variations as well.
Closes #999
PR Checklist:
*   [ ] Tests

Fix helper text for Git platform

---

frontend/components/admin/organisations/OrganisationItem.test.tsx
frontend/components/admin/organisations/OrganisationItem.tsx
frontend/components/home/rsd/OrganisationSignUpDialog.tsx

Closes #1014
* The link to documentation to register organisation is updated to https://research-software-directory.github.io/documentation/register-organisation.html
* Edit organisation link from admin page updated to open settings tab
How to test:
* visit home page, click on register organisation button. Try documentation link, it should open the page in new tab
* login as rsd-admin, navigate to admin section, the organisations page. Use edit button and confirm that opens organisation page on the settings tab
PR Checklist:
*   [ ] Tests

fix: update broken documentation link

---

frontend/utils/__mocks__/dataciteItem.json
frontend/utils/__mocks__/dataciteItem.json.license
frontend/utils/getInfoFromDatacite.test.ts
frontend/utils/getInfoFromDatacite.ts

* moved example response into separate file in `__mocks__` folder
* included fallback to `name` prop if any of props `givenName` or `familyName` are not provided.
How to test:
* create new software item
* use RSD concept DOI 10.5281/zenodo.6379973
* confirm that import does work. In the old version the import fails with an error message
PR Checklist:
*   [ ] Tests

refactor: harden contributors import process

---

frontend/components/projects/edit/team/EditTeamMemberModal.tsx
frontend/components/software/edit/contributors/EditContributorModal.tsx

Closes #1022
*  Add leading/trailing spaces error detection to email in contributor and team member modals 
How to test:
* `make start` to build app and create data
* login as rsd-admin and open software to edit
* navigate to contributors and try to create email with leading/trailing spaces. Confirm correct error message is
* open project page for edit. Navigate to team members. Add team member and try adding some spaces into email. Confirm error messages are correct
PR Checklist:
*   [ ] Tests

fix: show error message when spaces in email of contributor and team

---

frontend/package.json
frontend/yarn.lock

*  Upgrading frontend next.js lib to v13.5.6.  in the old version if you would run yarn build locally in frontend folder there would be number of messages in the console logs about write after close ... This is solved in [the new release](https://github.com/vercel/next.js/releases/tag/v13.5.6)
How to test:
* `make start` to build app and generate data
* the build should work and the app too :-). Also local build should work without these log messages in console
PR Checklist:
*   [ ] Tests

chore: upgrade next to 13.5.6 to fix warning during the build

---

.github/workflows/all_tests.yml
.github/workflows/authentication_tests.yml
.github/workflows/scrapers_tests.yml
authentication/Dockerfile
authentication/pom.xml
backend-postgrest/Dockerfile
backend-tests/Dockerfile
backend-tests/pom.xml
data-generation/Dockerfile
data-migration/pom.xml
database/Dockerfile
docker-compose.yml
nginx/Dockerfile
scrapers/Dockerfile
scrapers/jobs.cron
scrapers/pom.xml

* Update various backend dependencies as described in #1020
* Disable the old Python OAI-PMH scraper (the table will be deleted in a different branch)
How to test:
* Browse the website, see if everything works
* Login as a regular user, create some pages, see if everything works
* Login as admin, create some pages, check out the admin pages, see if everything works
Closes #1020
PR Checklist:
*   [ ] Tests

Update backend dependencies

---

database/010-create-release-table.sql
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/PostgrestReleaseRepository.java

* When you change or delete the concept DOI from a software page, a database trigger will now delete all associated released of that software.
* Fix the releases scraper so that it can handle multiple software entries having the same concept DOI.
How to test:
* Login as regular user, create two software pages with the same concept DOI (e.g. `10.5281/zenodo.6379973`).
* Run the releases scraper: `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.doi.MainReleases`
* Both pages should have the releases now
* Delete or edit the concept DOI from one page, the release should now also be gone
* Repeat …

1021 clear releases

---

scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/MainPackageManager.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/PostgrestConnector.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/PypiScraper.java

* Remove PyPI downloads scraper that uses https://api.pepy.tech/, since that API now requires a paid API key.
How to test:
* Login as admin and create a software page. Add https://pypi.org/project/cffconvert/ as a package manager
* Run the package manager scraper: `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.package_manager.MainPackageManager`
* This should create no errors in the console and in the error logs and the reverse dependency count should have been scraped
Note that this will not delete already scraped download counts.
We can look later into replacing this with a different …

Remove PyPI downloads scraper

---

deployment/rsd/data/settings.json
frontend/components/admin/software-highlights/index.tsx
frontend/components/software/overview/SoftwareHighlights.tsx
frontend/config/defaultSettings.json
frontend/config/getSettingsServerSide.ts
frontend/config/rsdSettingsReducer.ts

Fixes #626 
* make the "Software Highlights" configurable via `settings.json`
* if `software_highlights_title` is not defined in `data/settings.json`, use the value from `frontend/config/defaultSettings.json`
How to test:
* mount the `deployment/rsd` folder in the frontend via `docker-compose.yml`:
```yml
volumes:
- ./deployment/rsd:/app/public
```
* change the variable `software_highlights_title` in `deployment/rsd/data/settings.json` to something else and verify it is shown on the software page
* remove `software_highlights_title`from `deployment/rsd/data/settings.json` and verify that the title is now "Software Highlights"
PR Checklist: …

feat: configurable software highlights title

---

frontend/components/software/ContributorsList.tsx
frontend/components/software/useContributorList.tsx

Based on the feedback from initial approach the feature is changed to:
- if there are less than 12 items, all items are shown
- if there are more than 12 items we initially show first 12 items and the `Show all` button (see image 1). Click on the button will load all items
- when more than 12 items are loaded, `Show less` button is displayed. Click on the button will reduce list to first 12 items
How to test:
* create new software item. Use this concept DOI 10.5281/zenodo.3401363 on info page
* import contributors
* view software page. Confirm that 12 contributors and the button is shown. Load more by clicking on the button.
* reduce list by clicking on `Show less` button
* visit the software with less than 12 contributors, no buttons should be shown
* note …

feat: show top 12 contributors initially

---

.env.example
database/009-create-mention-table.sql
database/118-backend-logs-views.sql
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/Utils.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/CrossrefMention.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/DataciteMentionRepository.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/MainMentions.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/PostgrestMentionRepository.java

* The max size of the `authors` column in the `mention` table has been increased from `15000` to `50000`, in order to facilitate e.g. [10.1038/s41586-022-04893-w](https://doi.org/10.1038/s41586-022-04893-w).
* The mention scraper now saves error messages in the database and will try to update the `scraped_at` field for failed mentions.
* Add a warning to `.env.example` about special characters.
How to test:
* Login as admin and create a software page. Add `10.1038/s41586-022-04893-w` as a mention and add a few others.
* Run the mention scraper: `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar …

1039 author size

---

scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/CranScraper.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/package_manager/CranScraperTest.java

* The CRAN scraper now also allows for URLs in the form of `https://cran.r-project.org/package=packageName`
* The CRAN scraper now treats the URL as case insensitive, so `https://CRAN.R-project.org/package=packageName` will also work
How to test:
* Login as admin, create a software page, make it public and add the following package managers: `https://CRAN.R-project.org/package=TIMP` and `https://cran.r-project.org/package=splithalfr`
* Run the package manager scraper: `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.package_manager.MainPackageManager`
* Check that there are no errors in the …

More cran urls

---

data-generation/main.js
docker-compose.yml

* Within a single run, use a fixed pool of randomly generated ORCIDs to use for contributors and team members.
* Generate fake login credentials for those ORCIDs.
* With 80% chance, accounts will agree to display their public profiles.
How to test:
* Check various software and project pages and visit various profiles.
PR Checklist:
*   [ ] Tests

fix: better data generation to create profiles

---

.env.example
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Config.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/PostgrestAccount.java
deployment/docker-compose.yml
docker-compose.yml

* Add a new environment variable `RSD_ENVIRONMENT` that when set to the value `dev`, allows the first user that logs in to become an admin. With any other value, this env variable does nothing.
**Note:** This is a feature for local development only and is therefore not safe in production. When two people login at the same time, they might both become admin for example.
How to test:
* Add the new env variable to your `.env` and set its value to `dev`.
* Log in in any way you like, you should be an admin. Repeatedly logging in and out with this account should not change this. Repeatedly logging in and out with other accounts should *not* make those admin.
* Run …

Easily become admin when developing locally

---

docker-compose.yml
frontend/components/software/AboutPackageManagers.tsx
frontend/components/software/AboutSection.tsx
frontend/components/software/edit/package-managers/apiPackageManager.ts
frontend/package.json
frontend/pages/software/[slug]/index.tsx

Closes #1053 
*  The software packages are shown on the software page.    
How to test:
* thanks to last update, if you have `RSD_ENVIRONMENT=dev` in your .env file the first login user will become rsd_admin automatically in dev mode. Then you can edit existing software items, otherwise create new software item
* navigate to package mangers section and add few entries. You can use entries from old issue #791 
* confirm that packages section is shown on the software page and that the link points to proper software item
* note that data generation will also create some random package entries
PR Checklist:
*   [ ] …

feat: show package managers on software page

---

.vscode/settings.json
frontend/components/software/edit/editSoftwarePages.tsx
frontend/components/software/edit/package-managers/apiPackageManager.ts
frontend/components/software/edit/services/PackageManagerServices.tsx
frontend/components/software/edit/services/ServiceInfoAlert.tsx
frontend/components/software/edit/services/ServiceInfoListItem.tsx
frontend/components/software/edit/services/SoftwareRepoServices.tsx
frontend/components/software/edit/services/apiSoftwareServices.tsx
frontend/components/software/edit/services/config.ts
frontend/components/software/edit/services/index.tsx
frontend/pages/software/[slug]/edit/[page].tsx

**To test background services you will need to have properly defined service items in the .env file. Some might require secret to enable service to scrape information using "less restricted" quota.**
* The software maintainer can view status of the background services running for the software item
* The statuses reported are: 
*  `scheduled`: if the url is provided and last_error or last_run value is not present
* `not_active`: if the repository url or package manager url value is not present
* `error`: if the last_error value is present
* `success`: if the last_run value is present and the last_error value is NOT present. We show date/time of the last successful run
* Short description about the background services is added in the right panel of the …

Status report of background services for software

---

docker-compose.yml
frontend/components/admin/logs/apiLogs.ts
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/PostgrestConnector.java

* When scraping a package manager is succesful, clear the old error message
* When searching error logs, also search in the slug
How to test:
* Create a software page with a package manager pointing to e.g. https://pypi.org/project/ESMValTool/
* Run the package manager scraper (`docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.package_manager.MainPackageManager`), this should work without errors in the logs or in the "Background services" tab
* Manually set an error: `UPDATE package_manager SET reverse_dependency_count_last_error = 'Test error';`
* Check for the error on the "Background …

1078 clear package manager scraper errors

---

frontend/components/charts/d3LineChart/drawLineChart.tsx
frontend/components/software/AboutPackageManagers.tsx
frontend/components/software/edit/package-managers/PackageManagerItem.tsx
frontend/components/software/edit/package-managers/apiPackageManager.ts
frontend/components/software/edit/services/PackageManagerServices.tsx
frontend/components/software/edit/services/apiSoftwareServices.tsx

Closes #1077
* When link to a software package is provided to the package manager that are not "supported" with the logo we show first 3 letters of the hostname instead of the icon (see image below) 
* Increase margins in the commit line chart to show complete year at the first/last label
How to test:
* login as rsd_admin, use `RSD_ENVIRONMENT=dev` in .env file to promote first user logged into rsd_admin role
* select first software from the list and go to edit package manager section. Enter unknown package manager links like:
* https://packages.debian.org/search?keywords=libcdk-java
* https://central.sonatype.com/artifact/org.openscience.cdk/cdk-bundle/overview
* confirm that links are shown as squares …

fix: broken icon for other package managers

---

scrapers/src/main/java/nl/esciencecenter/rsd/scraper/Config.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/Utils.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/UtilsIT.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/UtilsTest.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/git/GithubScaperIT.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/git/GithubScraperTest.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/git/GitlabScraperIT.java

* Move (unused) tests that are actually integration tests to dedicated classes
* Cleanup the Config class (typos, unused code, etc.)
* Wrap forgotten HttpClient in try-with-resources
How to test:
* Wait for some scrapers to run
PR Checklist:

Cleanup scrapers

---

database/118-backend-logs-views.sql
frontend/components/admin/logs/apiLogs.ts
frontend/components/admin/logs/useLogs.tsx
frontend/utils/extractCountFromHeader.ts

* Change the return type of `slug_from_log_reference()` to be a `VARCHAR` instead of a `TABLE`, to allow for inlining
* Change the frontend to only request the amount of results on the first page of the logs
How to test:
* Run the following query to create 30000 fake log entries:
```sql
DO
$$
BEGIN
FOR i IN 1..30000 LOOP
INSERT INTO backend_log(service_name, table_name) VALUES ('scraper', 'table');
END LOOP;
END;
$$
```
* Log in as admin and browse through te backend logs. It should be fast after the first page. When filtering, the count should be updated.
Closes #1092
PR Checklist:

1092 slow backend logs function

---

backend-tests/README.md
backend-tests/pom.xml
backend-tests/src/test/java/nl/esciencecenter/AuthenticationIntegrationTest.java
backend-tests/src/test/java/nl/esciencecenter/SetupAllTests.java
backend-tests/src/test/java/nl/esciencecenter/User.java
backend-tests/src/test/java/nl/esciencecenter/UserIntegrationTest.java
database/011-create-account-table.sql

* Silently reset the `agree_terms_updated_at` and `notice_privacy_statement_updated_at` columns when a user changes this in the `account` table.
* Add a test for this and refactor some older tests
* Update dependencies of the backend tests
* Add a line to the docs explaining to add the setup class
How to test:
* Inspect the test to see if it does what it is supposed to
* Build and run the tests: `make run-backend-tests`
I'm not entirely sure if silently overwriting is better than generating an error. If someone has a good argument for the latter, I might change it.
PR Checklist:

Don't allow user to set updated_at columns for account

---

frontend/components/organisation/settings/maintainers/useOrganisationMaintainers.tsx
frontend/components/projects/edit/maintainers/useProjectMaintainer.tsx
frontend/components/software/edit/maintainers/useSoftwareMaintainers.tsx

* Deduplicate maintainers by using the login info with most present fields of name, email and affiliation
How to test:
* Log in with a non-ORCID account and create a software page, project page and organisation (make sure you're a maintainer of this organisation)
* Couple an ORCID to this account
* Check the maintainers of the pages you created above; only one maintainer should be visible on each
Closes #1091
PR Checklist:

fix: deduplicate maintainers on frontend

---

frontend/auth/api/authHelpers.ts
frontend/components/user/settings/LinkOrcidButton.tsx
frontend/components/user/settings/apiLinkOrcidProps.ts
frontend/pages/api/fe/auth/orcid.ts
frontend/pages/user/[section].tsx

* Only call ORCID well known endpoint on section page
* Replace string `'MISSING'` with `null` if coupling URL is missing
* Wrap code in try-catch statement to always be able to show the settings page
How to test:
* Log in with a non-ORCID account
* Navigate various user pages, like http://localhost/user/projects and http://localhost/user/settings. There should only be a noticable delay on the settings page
**Note:** It would be better to only fetch the data when needed when clicking the button, or asynchronously in the background. It might also be good to use caching. However, this PR only implements the minimum necessary, as this code …

fix: only call ORCID well known endpoint on settings page

---

.env.example
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Config.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Main.java
deployment/README.md
deployment/docker-compose.yml
docker-compose.dev.yml
docker-compose.yml
documentation/docs/03-rsd-instance/02-configurations.md
documentation/docs/03-rsd-instance/02-configurations.md.license
frontend/components/user/settings/apiLinkOrcidProps.ts

Fixes #1095 #1097
* Distinguish between auth providers used for login and for account coupling. This allows couple an ORCID account to an RSD account without having to allow ORCID login simultaneously
* :exclamation: This PR adds a new environment variable `RSD_AUTH_COUPLE_PROVIDERS`
* contains minor fix: removed the port mapping for the frontend dev mode because this was not necessary
How to test:
* in `.env`, set:
```
RSD_AUTH_PROVIDERS="SURFCONEXT;LOCAL"
RSD_AUTH_COUPLE_PROVIDERS=ORCID
```
* `docker compose build --parallel && docker compose up --scale scrapers=0`
* open login dialogue and verify that providers are Surf and Local only
* login
* navigate to user profile and link an ORCID account to the rsd account
* `docker compose down`
* add …

1095 distinguish openid providers

---

frontend/components/AppHeader/JavascriptSupportWarning.tsx
frontend/components/AppHeader/index.tsx
frontend/components/mention/MentionViewList.tsx
frontend/components/mention/MentionsSection.tsx
frontend/components/mention/useListPagination.tsx

Closes #1107 
* Render only first 50 mention items per group. Show all button is displayed at the bottom of the list to load all items.
* Loading first 50 items applies to all "mention" sections: reference papers, mentions, output and impact because this component is shared.
* All items are (still) loaded server side. I did not move api request to the frontend because when Javascript is disabled the mentions will not be loaded at all.
* The Javascript support message is moved below other header elements (search & nav). The notification message was not properly shown on the smaller screens (tablet & smartphone).
How to test:
* `make start` to build an create test data. This example is better tested without many data, so remove test data `docker …

1107 mentions performance

---

database/100-create-api-views.sql
documentation/docs/01-users/02-navigation.md
documentation/docs/01-users/02-navigation.md.license
frontend/components/GlobalSearchAutocomplete/GlobalsSearchAutocomplete.test.tsx
frontend/components/GlobalSearchAutocomplete/globalSearchAutocomplete.api.ts
frontend/components/GlobalSearchAutocomplete/index.tsx

* Use SQL instead of PL/pgSQL as the language for the `global_search` function
* Only search on slug and title (not keywords, research domains or short descriptions anymore)
* Give each result a score, based on exact match on the slug or title, the query being a prefix of the slug or title, or the query appearing anywhere in the slug or title
* Adapt the frontend to use the new function
How to test:
* Test out the global search with the fake data
* Log in and create software pages with the following titles: `abc`, `abc def` and `ghi abc def`. Global search on `abc`, they should be returned in the order above.
**Discussion:** Should the …

Improve global search function

---

.gitignore

ignore all tar files to prevent backups from being committed

chore: ignore all tar files to prevent backups from being committed

---

data-generation/real-data.js
docker-compose.yml
frontend/components/software/edit/package-managers/PackageManagerItem.tsx
frontend/components/software/edit/package-managers/apiPackageManager.ts
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/MainPackageManager.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/MavenScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/PackageManagerType.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/PostgrestConnector.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/scrapers/AnacondaScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/scrapers/CranScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/scrapers/CratesScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/scrapers/DockerHubScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/scrapers/GoScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/scrapers/MavenScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/scrapers/NpmScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/scrapers/PackageManagerScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/scrapers/PypiScraper.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/package_manager/MavenScraperTest.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/package_manager/scrapers/CranScraperTest.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/package_manager/scrapers/CratesScraperTest.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/package_manager/scrapers/GoScraperTest.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/package_manager/scrapers/MavenScraperTest.java

* Add package manager scrapers for Sonatype, Go and Crates.io.
* Fix small bug where `0` is reported when `null` is returned from the database for package managers
* Improve package manager examples to data generation
* Move scrapers to dedicated package
How to test:
* Create a software page with the following package managers:
* https://central.sonatype.com/artifact/org.openscience.cdk/cdk-bundle/
* https://crates.io/crates/tokio
* https://pkg.go.dev/github.com/gin-gonic/gin
* https://pkg.go.dev/google.golang.org/grpc
* Run the scraper: `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar …

974 improve maven scraper

---

.github/workflows/codemeta_scan_build.yml
.github/workflows/e2e_tests_chrome.yml
.github/workflows/release.yml
Makefile
codemeta/Dockerfile
codemeta/README.md
codemeta/go.mod
codemeta/main.go
codemeta/sonar-project.properties
deployment/docker-compose.yml
docker-compose.yml
nginx/nginx.conf

* Add CodeMeta server that can serve for each public software page the CodeMeta data
How to test:
* Browse http://localhost/software to collect some slugs
* Visit http://localhost/codemeta/some-slug and check that the CodeMeta data corresponds to the software page
* Check for missing data that is crucial for this first version
* Check the README.txt
* The actions can only be tested when merged into main 🙁, but read the files to see if they seem reasonable
Closes #1128
PR Checklist:

Codemeta server

---

authentication/src/main/java/nl/esciencecenter/rsd/authentication/PostgrestAccount.java
database/011-create-account-table.sql
frontend/components/admin/rsd-users/RsdLoginList.tsx
frontend/components/admin/rsd-users/RsdUsersList.tsx
frontend/components/admin/rsd-users/apiRsdUsers.ts
frontend/components/admin/rsd-users/useRsdAccounts.tsx

* Add column `last_login_date` to `login_for_account` table that gets updated everytime a user logs in
* Show the last login date on the admin view
How to test:
* Login as admin and browse http://localhost/admin/rsd-users, all fake accounts should say `Last login date missing`; your own account should display the date
* Logging is as regular user, logging in again and coupling accounts should still work
Closes #1054
PR Checklist:

feat: add last login date to login table

---

codemeta/Dockerfile
codemeta/main.go
codemeta/overview.go
codemeta/overview.gohtml
codemeta/utils.go
docker-compose.yml

* Add a simple overview page where visitors can find links to all CodeMeta pages
How to test:
* Visit http://localhost/metadata/codemeta/ and check that the links work.
PR Checklist:

CodeMeta overview page

---

deployment/docker-compose.yml
frontend/components/mention/ImportMentions/apiImportMentions.tsx
frontend/types/Datacite.ts
frontend/utils/getDataCite.ts
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/DataciteMentionRepository.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/OpenAlexCitations.java

* Fix bug where an OpenAlex raw author was wrongly assumed to be not null
* Adapt to the changed DataCite GraphQL API, where the publisher now has sub fields
* Escape colons when searching in the DataCite GraphQL API on title
* Show DataCite instead of Crossref when DataCite was used as the source in bulk import
* Set the container names for Swagger and CodeMeta in production
How to test:
* Create a software or project page, publish it
* Add the following DataCite mentions directly, then remove them, then add them with bulk import:
* 10.48550/arxiv.2310.12084
* 10.5281/zenodo.1140396
* Search for the title `CellProfiler and KNIME: …

Scraper fixes

---

codemeta/main.go
docker-compose.yml

* Add programming languages to CodeMeta metadata
* Add reference papers to CodeMeta metadata
* Change description from a string to an array of strings, that can contain the short statement, description and description URL
How to test:
* Add a software page, publish it, add a reference paper, add a valid GitHub URL and let the scraper scrape its programming languages (`docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainProgrammingLanguages`)
* Visit http://localhost/metadata/codemeta and inspect the data of your page
* Play around with having a short statement, description and description …

More CodeMeta data

---

docker-compose.yml
frontend/components/organisation/projects/search/OrgSearchProjectSection.tsx
frontend/components/organisation/software/search/OrgSearchSoftwareSection.tsx
frontend/components/profile/projects/ProfileSearchProjects.tsx
frontend/components/profile/software/ProfileSearchSoftware.tsx
frontend/components/projects/overview/search/ProjectSearchSection.tsx
frontend/components/software/overview/search/SoftwareSearchSection.tsx
frontend/pages/software/index.tsx
frontend/utils/pagination.ts

* Switch from `Page <page number> of <total software/project entries>` to `<low-range>-<high-range> of <total software/project entries>`
How to test:
* Browse the RSD (http://localhost), and check the pagination on the various overview pages (also of profiles and within an organisation)
Closes #1098
PR Checklist:

Pagination ranges

---

database/004-create-relations-for-software.sql
docker-compose.yml
frontend/components/software/edit/editSoftwareConfig.tsx
frontend/components/software/edit/links/AutosaveRepositoryUrl.tsx
frontend/components/software/edit/links/EditSoftwareMetadataForm.tsx
frontend/components/software/edit/services/SoftwareRepoServices.tsx
frontend/components/software/edit/services/apiSoftwareServices.tsx
frontend/types/SoftwareTypes.ts
frontend/utils/editSoftware.ts
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/GithubScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/GitlabScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/PostgrestConnector.java

* Admins can disable the scraping of a Git repo, maintainers can see the reason why
How to test:
* Sign in as admin, create two software pages, set a repo for both, then fill the disallow scraping reason in for one of them
* Wait for the scrapers to run
* After a few minutes, the page without a reason should be scraped, the other one should not
* On the background services tab, you should be able to see a reason, both as admin and maintainer
* On the links & metadata tab, the edit reason field should only be visible for admins
Related to #1117 (we still need to do this for package managers)
PR Checklist:

1117 disable scraping

---

CONTRIBUTING.md

**Action required**
If you already have REUSE installed, you can upgrade it with `pip install --upgrade reuse`.
Furthermore, update `RSD-as-a-service/.git/hooks/pre-commit` (line 88 for me) with the change in this PR.
Closes #1129

docs: update pre-commit hook for reuse v3

---

frontend/components/layout/EditPageButton.tsx
frontend/components/layout/ViewPageButton.tsx
frontend/components/organisation/overview/useOrganisationOverviewParams.tsx
frontend/components/projects/overview/useProjectOverviewParams.ts
frontend/components/software/overview/useSoftwareOverviewParams.ts
frontend/components/user/settings/UserAgreementModal.tsx
frontend/pages/organisations/index.tsx
frontend/pages/projects/[slug]/edit/[page].tsx
frontend/pages/projects/index.tsx
frontend/pages/software/[slug]/edit/[page].tsx
frontend/pages/software/index.tsx

* Add anchor element to software, project and organisation pagination and to view/edit software/project buttons
* Admins don't get the modal with terms of service and privacy statement anymore
How to test:
* Paginate software, projects and organisation, it should still work without a full page reload, but you can also open them in a new tab
* Login as admin, check the view/edit software/project buttons, it should still work without a full page reload, but you can also open them in a new tab
* As admin, you don't get to see the modal where you have to accept the terms of service and privacy statement when you want to edit a page
PR …

Add anchor elements to links

---

frontend/components/software/edit/package-managers/EditPackageManagerIndex.test.tsx
frontend/components/software/edit/package-managers/EditPackageManagerModal.tsx
frontend/components/software/edit/package-managers/__mocks__/apiPackageManager.ts
frontend/components/software/edit/package-managers/apiPackageManager.ts

Fixes #1156 
* use `rpc/suggest_platform` to suggest the type for package registries
How to test:
* login
* create a new software or open an existing one in edit mode
* in the "Information" tab, add `https://codebase.helmholtz.cloud/research-software-directory/RSD-as-a-service` and set the repository type to GitLab
* open "Package managers" tab and add a new package manager with the same url as above
* GitLab should be detected as type and the GitLab logo will be shown
This approach is a very simple solution to achieve support for custom GitLab registries. On the other hand, existing package managers are not updated and must either be updated by the maintainers, or with a script by the …

fix: support for custom GitLab package and container registries

---

frontend/components/projects/edit/team/index.tsx
frontend/components/software/edit/contributors/index.tsx

* When a contributor or team member is made to be a contact person, the other contributors/team members are set *not* to be a contact person
How to test:
* Sign in as admin, edit a software contributor to be a contact person, the other contributors should not be a contact person anymore
* Repeat when adding a new contributor
* Try the same for the team members of a project
Closes #948
PR Checklist:

fix: update contact people when new contact person is set

---

frontend/components/organisation/releases/ReleaseList.tsx
frontend/components/organisation/releases/index.tsx

* Fix the key in a React component to prevent duplicate releases being shown
How to test:
* Sign in as admin, create two published software pages with the same concept DOI, e.g. `10.5281/zenodo.7614737`
* Link the two pages to the same organisation
* Run the releases scraper: `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.doi.MainReleases`
* Look at the releases of the org page, switch between years, no releases should 'stick'
Closes #1163
PR Checklist:

Prevent duplicate releases

---

.github/workflows/_cff.yml

This should allow the release workflow to push the `CITATION.cff` file without requiring us to disable branch protection. Followed instructions from [here](https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#push-to-protected-branches).

ci: add token for release workflow

---

authentication/pom.xml

* updates `oauth2-oidc-sdk` which is being used in HelmholtzID login
How to test:
* verify that login via Helmholtz ID still works
PR Checklist:
*   [ ] Tests

Update auth container dependencies

---

frontend/components/software/overview/SoftwareHighlights.tsx

Fixes #1167 
* hides the highlights carousel on second and consecutive pages of the software overview
How to test:
* `make start`
* navigate to software overview, highlights carousel is shown
* navigate to second and further pages and verify that carousel is hidden
PR Checklist:
*   [ ] Tests

feat: show highlights carousel only on first page

---

codemeta/main.go
docker-compose.yml

* Use `float64` instead of `uint64` for unmarshalling programming languages from the RSD
How to test:
* Create two *public* software pages, one with repo URL https://github.com/research-software-directory/RSD-as-a-service and one with https://gitlab.com/open-darts/open-darts
* Go to http://localhost/metadata/codemeta and check both entries before they are scraped
* Run `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainProgrammingLanguages`
* Check both entries again, they should display without an error
Closes #1173
PR Checklist:

fix: use floating points for programming languages

---

authentication/pom.xml
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Main.java
backend-postgrest/Dockerfile
database/002-create-image-table.sql
database/Dockerfile
docker-compose.yml
frontend/utils/editImage.ts
nginx/Dockerfile
scrapers/pom.xml

* Upgrade dependencies as in #1169
* Create a domain for images as described in the [documentation for PostgREST 12](https://postgrest.org/en/v12/how-tos/providing-images-for-img.html)
* Adapt to status code `200` instead of `201` being returned when uploading an existing image
How to test:
* Browse various pages, sign in and edit pages, check the [API](http://localhost/api/v1/) and [Swagger](http://localhost/swagger/)
Closes #1169
PR Checklist:

feat: upgrade backend dependencies

---

frontend/components/organisation/projects/index.tsx
frontend/components/organisation/settings/index.tsx
frontend/components/organisation/software/index.tsx
frontend/components/organisation/units/index.tsx
frontend/components/user/settings/UserAgreementModal.tsx
frontend/pages/projects/[slug]/edit/[page].tsx
frontend/pages/projects/add.tsx
frontend/pages/software/[slug]/edit/[page].tsx
frontend/pages/software/add.tsx

* Include user?.role in the dependency array of useEffect hook (fix linter warning)
* Fix typo in the name of UserAgreementModal  component
How to test:
* login with first user, that will be rsd-admin role. Confirm by seeing Adminstration option in user menu
* try to add software. As rsd admin you will not see UserAgreementModal
* login as different user, not rsd-admin.
* try to add software. You should see UserAgreementModal only once to accept user agreement
PR Checklist:
*   [ ] Tests

Add user.role to dependency and fix typo

---

.github/workflows/_cff.yml
.github/workflows/release.yml

In order for action to be able to push commit to protected branch during release we needed to add a secret to action.
- Create PAT token for an admin account in the repo
- Add this token to action/repository secrets. The action expects secret wit name `PAT_RELEASE`
* Add token to _cff.yml "reusable" action
* Pass token to _cff.yml  from "reselease" action
How to test:
* Not possible to test except for running release action
* I have tested this approach in a (personal) [test repo](https://github.com/dmijatovic/rsd-saas-test)
PR Checklist:
*   [ ] Tests

ci: use token to commit to protected branch

---

database/103-software-views.sql
deployment/rsd/data/settings.json
documentation/docs/03-rsd-instance/03-administration.md
documentation/docs/03-rsd-instance/03-administration.md.license
frontend/components/admin/software-highlights/AdminSoftwareHighlightsPage.test.tsx
frontend/components/admin/software-highlights/SoftwareHighlightInfo.tsx
frontend/components/admin/software-highlights/SortableHighlightItem.tsx
frontend/components/admin/software-highlights/SortableHighlightList.tsx
frontend/components/admin/software-highlights/apiSoftwareHighlights.ts
frontend/components/admin/software-highlights/index.tsx
frontend/components/admin/software-highlights/useSoftwareHighlights.tsx
frontend/components/software/SoftwareKeywords.tsx
frontend/components/software/overview/SoftwareHighlights.tsx
frontend/components/software/overview/filters/OrderSoftwareBy.tsx
frontend/components/software/overview/filters/index.tsx
frontend/components/software/overview/filters/softwareFiltersApi.ts
frontend/components/software/overview/useSoftwareOverviewParams.ts
frontend/config/defaultSettings.json
frontend/config/defaultSettings.json.license
frontend/config/getSettingsServerSide.ts
frontend/config/rsdSettingsReducer.ts
frontend/pages/software/index.tsx
frontend/pages/spotlights/index.tsx
frontend/public/data/settings.json
frontend/public/data/settings.json.license
frontend/utils/getSoftware.ts
frontend/utils/postgrestUrl.ts

Fixes #1170
* adds a dedicated page for software highlights
* the highlights are by default sorted "Latest featured", i.e. ascending position
* the filters in the sidebar show only properties of the highlights
* the software highlights page can be reached via a button below the highlights carousel
* note that the configuration for software highlights in `settings.json` changes slightly
How to test:
* optionally: define `software_highlights` title and description in `settings.json`
* in a second terminal window `docker compose run data-generation`
* navigate to software overview
* if there are no highlights, login as admin and add some
* click on the "Browse all …

1170 dedicated highlights page

---

data-generation/main.js
frontend/components/admin/rsd-users/RsdUsersList.tsx
frontend/components/admin/rsd-users/apiRsdUsers.ts
frontend/components/admin/rsd-users/index.tsx
frontend/components/admin/rsd-users/useRsdAccounts.tsx

* In the user overview of admins, you can choose to only see admins
* In the user overview of admins, you can filter on accounts that have a login method that hasn't been used in `n` days (or that never logged in since we kept track of the last login date)
* Add last login dates to data generation
How to test:
* Log in as admin, go to http://localhost/admin/rsd-users
* Assign some more admins, toggle the extra switch, you should only see admins
* Enter a positive number in the `Last login` input, you should only see accounts that have a login method where the last login date is either missing or older than the amount of days you entered …

See inactive accounts in admin interface

---

frontend/components/layout/UserMenu.tsx
frontend/components/user/UserNav.tsx

* Add anchor elements to drop-down menu when logged in
* Add anchor elements to tabs on user page
How to test:
* Log in, test out the items in the drop-down menu of your avatar. Clicking them normally should *not* trigger a full page reload. You can also right click them or open them in a new tab with the middle mouse button
* Go to e.g. http://localhost/user/software, test the same for the different tabs
* Check that the styling (especially on mouse hover) is ok
PR Checklist:

Add anchor tags to drop down menu and user page

---

scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/PostgrestMentionRepository.java

Store the DOI, external ID and source in the error logs when a mention couldn't be saved in the database for whatever reason.

store message with metadata in the error logs when saving a mention fails

---

frontend/utils/getCrossref.ts
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/CrossrefMention.java

* Prevent Crossref mentions form having undefined authors by checking if the fields are present first
* Try to use the `name` field if either `given` or `family` is missing
* Apply the same logic to the Crossref scraper
How to test:
* Create some page, add a mention with DOI `10.1103/physrevd.108.072003`
* Check the last author, this should be `ATLAS Collaboration`
* The words `undefined` or `null` should not be part of the authors
* Run the mention scraper: `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.doi.MainMentions`
* The last author should be unchanged
* The words `undefined` or …

fix: check if fields present in author before adding mention

---

documentation/docs/01-users/05-adding-software.md
frontend/components/software/edit/editSoftwareConfig.tsx

* Improve the help texts on the software edit page under the `Description` tab
* Improve the documentation page
How to test:
* Sign in as admin, edit a software page, check the helper text at when changing the description type to `Document URL`
* Check the question mark at the text `What {software} can do for you`
* Check the text at that link, including the warning box
* Alternatively, you can see the differences in the PR
Closes #249
PR Checklist:

Improve documentation for Markdown images

---

database/015-create-maintainer-tables.sql
documentation/docs/01-users/05-adding-software.md
documentation/docs/01-users/07-adding-projects.md
documentation/docs/01-users/09-organisation.md
documentation/docs/01-users/09-organisation.md.license
documentation/docs/03-rsd-instance/04-database.md
documentation/docs/03-rsd-instance/04-database.md.license
frontend/components/layout/InvitationList.tsx
frontend/types/Invitation.ts
frontend/utils/getUnusedInvitations.ts

* Maintainer invites now expire 31 days after creation; this is implemented by an automatically generated column in the database
* Show the remaining validity of invites in days on the frontend
* Add documentation on how to schedule repeated tasks in the database
How to test:
* Sign in as admin, create maintainer invites for a software page, project and organisation
* Each invitation should show that it will expire in 31 days
* You can run the following snippet in the database to experiment with different expiration dates for software invites to check if the frontend behaves correctly:
```sql
ALTER TABLE invite_maintainer_for_software …
```

Expire maintainer invites and scheduled tasks for the database

---

.github/workflows/fair_software.yml
README.md

This will enable the [howfairis-github-action](https://github.com/fair-software/howfairis-github-action). The action currently fails, because the README in our `main` branch does not match the badge we should have. This PR includes the correct badge, so *after* merging this PR, it should succeed again.
Closes #322

Enable `howfairis` GitHub action

---

frontend/components/cookies/useCookieConsent.tsx
frontend/components/filter/useFilterQueryChange.tsx
frontend/components/pagination/Pagination.tsx
frontend/components/pagination/PaginationContext.tsx
frontend/components/projects/overview/useProjectOverviewParams.test.ts
frontend/components/projects/overview/useProjectOverviewParams.ts
frontend/components/search/SearchContext.tsx
frontend/components/search/useSearchParams.test.tsx
frontend/components/search/useSearchParams.tsx
frontend/components/software/overview/useSoftwareOverviewParams.ts
frontend/components/user/communities/useUserCommunities.tsx
frontend/config/UserSettingsContext.tsx
frontend/config/__mocks__/UserSettingsContext.tsx
frontend/pages/_app.tsx
frontend/pages/admin/communities.tsx
frontend/pages/admin/keywords.tsx
frontend/pages/admin/logs.tsx
frontend/pages/admin/mentions.tsx
frontend/pages/admin/orcid-users.tsx
frontend/pages/admin/organisations.tsx
frontend/pages/admin/rsd-contributors.tsx
frontend/pages/admin/rsd-users.tsx
frontend/pages/organisations/index.tsx
frontend/pages/software/index.tsx
frontend/public/data/settings.json
frontend/utils/usePaginationWithSearch.tsx

Closes #1200
* Added user settings context to be shared in all components
* Use user settings across the app. Select rows per page is used on all pages where pagination is enabled      
How to test:
* `make start` to build app and create test data
* Navigate to software overview page, change items per page. Refresh the page and confirm there are no console log errors (like the ones in the issue)
* Navigate to projects overview page and perform similar check (change items per page, reload and check browser console)
* Navigate to organisations page and perform similar check (change items per page, reload and check browser console)
* Navigate to communities page and perform similar check
* Navigate to news overview page and perform similar check
* …

feat: same items per page on all pages with pagination (save user choice and reuse it)

---

frontend/components/admin/mentions/MentionsOverviewList.tsx
frontend/components/admin/organisations/OrganisationsAdminList.tsx
frontend/components/admin/organisations/index.tsx
frontend/components/category/CategoryEditTree.tsx
frontend/components/software/CommunitiesSection.tsx
frontend/components/software/CommunityItem.tsx
frontend/components/software/OrganisationsSection.tsx
frontend/components/software/edit/editSoftwarePages.tsx
frontend/pages/software/[slug]/index.tsx
frontend/public/data/settings.json
frontend/types/SoftwareTypes.ts
frontend/utils/getSoftware.ts

Closes #1223
*  Additional section "Member of community" is added after "Testimonials". The position of menu item in edit software is also placed at the same position (after testimonials)
* The section is not shown if communities module is not enabled.
* Minor layout changes in the admin section (no items messages)
How to test:
* enable communities module
* login as rsd-admin
* navigate to existing software, add community to software
* navigate to community and accept membership
* confirm that community is shown on software. Click to visit community page
* edit software and add 2 more communities
* navigate to community page and reject the request
* navigate to software page and confirm that …

feat: add community membership on the software page

---

frontend/auth/api/authEndpoint.ts
frontend/components/AppHeader/AppHeader.test.tsx
frontend/components/user/settings/apiLinkOrcidProps.ts
frontend/pages/api/fe/auth/azure.ts
frontend/pages/api/fe/auth/helmholtzid.ts
frontend/pages/api/fe/auth/index.ts
frontend/pages/api/fe/auth/orcid.ts
frontend/pages/api/fe/auth/surfconext.ts

Closes #1106
*   Cache requests to well known endpoint to obtain authorization endpoint url every **60 minutes**  
How to test:
* `make start` to build app and generate test data (not really required)
* observe console logs from the frontend. `docker compose logs frontend -f`
PR Checklist:
*   [ ] Tests

feat: cache auth endpoints for all providers

---

data-generation/main.js
database/003-create-image-table.sql
frontend/components/form/ControlledImageInput.tsx
frontend/components/news/edit/AutosaveNewsImage.tsx
frontend/components/organisation/units/ResearchUnitModal.tsx
frontend/components/person/AvatarOptions.tsx
frontend/components/projects/edit/information/AutosaveProjectImage.tsx
frontend/components/projects/edit/team/EditTeamMemberModal.tsx
frontend/components/software/edit/contributors/EditContributorModal.tsx
frontend/components/software/edit/information/AutosaveSoftwareLogo.tsx
frontend/utils/handleFileUpload.ts

* Restrict the allowed MIME types in the `image` table
* Adapt the frontend to show, by default, only allowed files when choosing an image
* Adapt the data generation script
* Remove an unused function from the data generation script
How to test:
* Upload some images in various places
* By default, the upload window will only show accepted files
* If you try to upload a non-accepted file, it should fail with an error
**Note**: you might have the non-existing MIME type `image/jpg` in the database. Before applying this in production, you should run the following SQL query:
```sql
UPDATE IMAGE SET mime_type = …
```

Restrict MIME types for image table

---

documentation/docs/01-users/05-adding-software.md
frontend/components/software/edit/links/AutosaveRepositoryUrl.tsx
frontend/components/software/edit/links/SoftwareLinksInfo.tsx
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/GithubScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/GitlabScraper.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/git/GithubScaperIT.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/git/GithubScraperIT.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/git/GithubScraperTest.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/git/GitlabScraperIT.java

Fixes #1244 
* scrapers recognise repository urls that end with `.git` and scrape them
* adds a sentence to the UI stating which URLs are supported
* update user documentation
* adds tests for the scrapers (disabled)
* rename GithubScaperTestIT to GithubSc**r**aperTestIT
* fix bug where `scraping_disabled_reason` text field shows number of characters of `repository_url`
How to test:
* ```
docker compose down --volumes && docker compose build --parallel && docker compose up
```
* create four software entries with the following repository URLs (or those of you choice) and set them visible:
* `https://github.com/research-software-directory/RSD-as-a-service.git`
* `https://github.com/research-software-directory/RSD-as-a-service`
* …

Support repository urls ending with .git

---

frontend/components/category/CategoriesWithHeadlines.tsx
frontend/components/category/CategoryEditTree.tsx
frontend/components/category/CategoryEditTreeNode.tsx
frontend/components/category/CategoryTable.tsx
frontend/components/category/CategoryTree.tsx
frontend/components/category/apiCategories.test.ts
frontend/components/category/apiCategories.ts
frontend/components/form/AutosaveControlledMarkdown.test.tsx
frontend/components/software/CategoriesSection.tsx
frontend/components/software/TreeSelect.tsx
frontend/components/software/edit/communities/CommunityAddCategoriesDialog.tsx
frontend/components/software/edit/links/AutosaveSoftwareCategories.tsx
frontend/components/software/edit/links/SoftwareLinksInfo.tsx
frontend/types/TreeNode.ts
frontend/utils/categories.ts
frontend/utils/jest/utils.js

* Force the TreeNode values to be non-null and adapt the calling code
* Add a test to check if `categoryEntriesToRoots` works correctly
* Fixed the type in an existing, not-related test
How to test:
* Check if categories still work correctly everywhere
Closes #1242
PR Checklist:

Remove `null` from TreeNode

---

frontend/components/communities/context/index.tsx
frontend/components/communities/metadata/CommunityLogo.tsx
frontend/components/organisation/metadata/OrganisationLogo.tsx
frontend/middleware.ts
frontend/next.config.js

* Visiting a community from the global search bar doesn't trigger a full page reload anymore
* Switching between organisations using the global search bar now always shows the correct (maybe missing) logo
* Switching between communities using the global search bar now always shows the correct metadata and (maybe missing) logo
How to test:
* Switch between various organisations through the global search bar, the correct logo should always be shown, also when the organisation doesn't have a logo
* Do the same for communities, also look at the short description
Closes #1253
Closes #1254
PR Checklist:

1253 communities redirect

---

frontend/auth/locationCookie.test.ts
frontend/auth/locationCookie.ts

* When signing in from the home page, you are redirected to "My software" istead of the global software overview page
How to test:
* Sign in from the home page
* You should be at "My software", not the the global software overview page
* When signing in from another page, you should still be redirected back to that page
Closes #1257
PR Checklist:

Redirect to "My software" after sign in from home page

---

data-generation/main.js
database/009-create-keyword-and-category.sql
database/010-create-research-domain.sql
database/011-create-mention-table.sql
database/012-create-release-table.sql
database/014-create-organisation-table.sql
database/015-inter-relation-tables.sql
database/100-create-api-views.sql
database/104-software-views.sql
database/106-project-views.sql
frontend/README.md

* Data generation script now generates more data by default
* Add indices to join tables
* Improve `GROUP BY` operations by only specifying necessary columns
* Improve `UNION`s by first first doing `UNION ALL` and then filter out duplicate columns based on only necessary columns
How to test:
* Check if everything still works
* This was tested to improve performance on some database calls
PR Checklist:

Database performance

---

authentication/Dockerfile
authentication/pom.xml
backend-postgrest/Dockerfile
backend-tests/Dockerfile
backend-tests/pom.xml
backend-tests/src/test/java/nl/esciencecenter/SetupAllTests.java
codemeta/Dockerfile
codemeta/template/overview.gohtml
data-generation/Dockerfile
data-generation/main.js
data-generation/package-lock.json
data-generation/package.json
database/Dockerfile
nginx/Dockerfile
scrapers/Dockerfile
scrapers/pom.xml

* Upgrade various dependencies used in the backend, including those described as in #1262
How to test:
* Check if everything still works
* `docker compose down --volumes`
* `make run-backend-tests` should report 15 tests with 0 failures, errors or skipped
Closes #1262
PR Checklist:

Backend dependency upgrades

---

database/005-create-relations-for-software.sql
documentation/docs/03-rsd-instance/03-administration.md
frontend/components/software/edit/package-managers/PackageManagerItem.tsx
frontend/components/software/edit/package-managers/apiPackageManager.ts
frontend/components/software/edit/services/PackageManagerServices.tsx
frontend/components/software/edit/services/ServiceInfoListItem.tsx
frontend/components/software/edit/services/SoftwareRepoServices.tsx
frontend/components/software/edit/services/apiSoftwareServices.tsx
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/package_manager/PostgrestConnector.java

* Admins can disable the harvesting of specific package managers statistics by supplying a reason as to why it is disabled
* Page maintainer can see if and why a harvester is disabled on the `Background services` tab
* Add documentation on this
How to test:
* Create a software page, publish it and add some package managers
* Disable those package managers
* Check that the reason is visible on the `Background services` tab
* Run the harvesters: `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.package_manager.MainPackageManager`
* Check that the `*_updated_at` fields are …

Option to disallow package manager harvesting

---

frontend/components/software/edit/links/AutosaveSoftwareCategories.tsx
frontend/components/software/edit/links/EditSoftwareMetadataInputs.tsx

* Don't show the categories dropdown when there are no categories to choose from
* Fix the font weight as described in #1251
How to test:
* Create a software page, go to the **Links & metadata** tab
* There should be no dropdown for the categories
* Add some categories as admin
* The dropdown should be there
* Mix and match with regular/highlighted categories being present or not and check if the drowdown(s) are as expected
Closes #1251
PR Checklist:

Don't show categories dropdown when there are no categories

---

database/104-software-views.sql
frontend/utils/postgrestUrl.ts

* Don't show empty software highlight cards on search by fixing database function
* Implement some SonarCloud fixes
How to test:
* Visit the highlights page (if necessary, sign in as admin and add more)
* Do various searches, combining different filters
* Check if the results are as expected
Closes #1267
PR Checklist:

 Don't show empty software highlight cards on search

---

authentication/src/main/java/nl/esciencecenter/rsd/authentication/AzureLogin.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/OrcidLogin.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/SurfconextLogin.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/Utils.java
authentication/src/test/java/nl/esciencecenter/rsd/authentication/UtilsTest.java

* Deduplicate and test some of the code in the authentication module
How to test:
* Sign in through various methods, including SURFconect, Azure and ORCID (put your ORCID on the allowlist first as admin)
PR Checklist:

Deduplicate and test some authentication code

---

frontend/components/form/ControlledImageInput.tsx
frontend/components/form/ImageInput.tsx
frontend/components/news/edit/AutosaveNewsImage.tsx
frontend/components/organisation/apiOrganisations.ts
frontend/components/organisation/units/ResearchUnitModal.tsx
frontend/components/person/AvatarOptions.tsx
frontend/components/person/AvatarOptionsPerson.tsx
frontend/components/projects/edit/information/AutosaveProjectImage.tsx
frontend/components/projects/edit/team/EditTeamMemberModal.tsx
frontend/components/software/edit/contributors/EditContributorModal.tsx
frontend/components/software/edit/information/AutosaveSoftwareLogo.tsx
frontend/utils/handleFileUpload.ts

Closes #1247 
* Create ImageInput component to be used in all other component for image upload
* Fixed organisation unit failed updates (after changing values from the parent organisation)   
How to test:
* `make start` to build and create test data
* login as rsd admin and test all image uploads:
* Software:
* upload software logo
* add/edit contributor
* add/edit organisation
* Project
* upload body image
* edit team member
* add organisation and upload logo
* Organisation
* add/edit logo
* add/edit research unit (error fixed)
* News: add/edit news images
* Administration:
* add/edit organisation image
* ads/edit community image
PR Checklist:
*   [ ] Update …

1247 image upload

---

deployment/docker-compose.yml
docker-compose.yml
frontend/components/mention/ImportMentions/apiImportMentions.tsx
frontend/pages/api/fe/mention/crossref.ts
frontend/utils/getCrossref.ts
frontend/utils/getDOI.ts
frontend/utils/promisePool.test.ts
frontend/utils/promisePool.ts

* Do requests to Crossref from the Next.js server instead of the browser, to that the polite pool (using email) can be used
* Use a promise pool (or semaphore) to limit the amount of parallel requests to Crossref.
How to test:
* Sign in, create a software page
* Bulk add Crossref mentions to the page, using the examples from #808; this should work without error
Closes #1270
PR Checklist:

Fix bulk import mentions from Crossref

---

database/009-create-keyword-and-category.sql

Fixes #1297 
* change column order of `category` table to match table structure of a migrated table
* explicitly specify `category_path` return types
How to test:
* create categories and assign them to a software
* verify that they are displayed on the software page and that the database container does not generate errors when viewing the page
* restore a database backup of a migrated database (or by checking out v2.18.0, generating data, applying migrations to v2.19.0)
* open database in terminal `docker compose exec -it database psql rsd-db rsd`
* run this in the db terminal
```sql
DROP FUNCTION category_path;
CREATE FUNCTION category_path(category_id UUID)
RETURNS TABLE (
id UUID,
parent …
```

fix: specify return types in category_path

---

frontend/components/admin/mentions/MentionsOverviewList.tsx
frontend/components/mention/EditMentionModal.tsx
frontend/components/mention/MentionEditSection.tsx

Closes #1304 
* The modals are conditionally rendered in order to properly load initial form data for editing
* When changing mention type from highlight to other type the rules are improved (required is set to false)
* Manually remove highlight specific error from the error object after type is changed
How to test:
* login as rsd admin and try to manually create or edit mentions
* When using `highlight` mention type you will need to provide image_url before save button is enabled (form is valid)
* Try changing the mention type from highlight to other types. You should be able to save mention without image_url (save button should be enabled)
PR Checklist: …

fix: mention form validation

---

frontend/config/RsdPluginContext.tsx
frontend/config/getPlugins.ts
frontend/config/rsdSettingsReducer.ts

Fixes connection issues when running nextjs in a docker container.
* changes the plugin settings in `frontend/public/data/settings.json` to also include the hostname of the plugin backend, which is required to make the requests inside the docker network
How to test:
* change plugins array in `settings.json` to:
```json
"plugins": [
{
"name": "dummyplugin",
"backend_hostname": "dummy-plugin-backend:8081"
}
]
```
* build and run the application and verify that backend is reached by next
@dmijatovic please review this solution. I will update the documentation after you will have accepted.
PR Checklist:
*   [ ] Tests

chore: add plugin hostname to plugin configuration

---

documentation/docs/01-users/05-adding-software.md
documentation/docs/01-users/11-scrapers.md
documentation/docs/01-users/11-scrapers.md.license
documentation/docs/01-users/99-faq.md
documentation/docs/01-users/99-faq.md.license

* Add more details on how software releases are harvested
* Add a FAQ entry on adding workshops as a software page
* Some other small fixes
* Read the new documentation on the "Data scrapers" and "Frequently Asked Questions" pages
Closes #1301
Closes #1307
PR Checklist:

Documentation on releases and workshops

---

scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/DataciteMentionRepository.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/MainMentions.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/OpenAlexConnector.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/doi/OpenAlexConnectorTest.java

* When trying to scrape zero mentions, return immideately with an empty response to prevent errors later on
* Added tests to test this
* Now that there are no mentions, run the mentions scraper:
* `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.doi.MainMentions`
* No errors should be reported
* Same for the citations scraper:
* `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.doi.MainCitations`
Closes #1317
PR Checklist:

OpenAlex scraper bug fix

---

frontend/components/person/AggregatedPersonModal.tsx

Closes #1313
*   Additional validation on email field is performed when contact person switch value changes
How to test:
* login as rsd admin
* edit software or project contributors or team members
* try to set contact person flag to true when no email is provided, the email field should signal an error
PR Checklist:
*   [ ] Tests

fix: use additional validation for email and contact person switch

---

.github/workflows/editorconfig-check.yml
authentication/.editorconfig
authentication/README.md
authentication/pom.xml
authentication/src/test/java/nl/esciencecenter/rsd/authentication/UtilsTest.java
backend-tests/.editorconfig
backend-tests/README.md
backend-tests/pom.xml
database/.editorconfig
database/104-person-views.sql
scrapers/.editorconfig
scrapers/README.md
scrapers/pom.xml
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/RsdResponseException.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/DataCiteReleaseRepository.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/DataciteMentionRepository.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/CommitData.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/MainBasicData.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/MainCommits.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/MainContributors.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/MainProgrammingLanguages.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/ror/BasicOrganisationData.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/ror/MainRor.java
scrapers/src/main/resources/logback.xml
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/doi/MainMentionsTest.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/ror/RorScraperTest.java

* Add a `.editorconfig` to some of the backend modules to ensure consistent basic formatting (as there is no [good formatter for Java](https://jqno.nl/post/2024/08/24/why-are-there-no-decent-code-formatters-for-java/))
* Add a GitHub workflow that checks if files are compliant with the EditorConfig settings
* Add some info on EditorConfig to the respective README files
* Check out the new info in the README files
Related to #915
PR Checklist:

Use EditorConfig

---

documentation/docs/01-users/05-adding-software.md
frontend/components/layout/PageErrorMessage.tsx
frontend/components/software/edit/editSoftwareConfig.tsx
frontend/components/software/edit/information/AutosaveRemoteMarkdown.tsx
frontend/components/software/edit/information/AutosaveSoftwareMarkdown.test.tsx
frontend/components/software/edit/information/AutosaveSoftwareMarkdown.tsx
frontend/pages/api/fe/markdown/raw.ts
frontend/utils/fetchHelpers.ts
frontend/utils/getSoftware.ts

Closes #494
* Changed label to "Markdown URL"
* created RSD api endpoint to validate url and avoid CORS error
* If provided url returns html page we raise error and suggest raw markdown url. Suggested url work properly for Github, Gitlab and Bitbucket.
* Allow url params in regex check
How to test:
* login as rsd admin and edit existing software or create new entry.
* try remote markdown with following urls:
* https://github.com/research-software-directory/RSD-as-a-service/blob/main/README.md
* https://raw.githubusercontent.com/research-software-directory/RSD-as-a-service/refs/heads/main/README.md
* https://gitlab.com/dmijatovic/nexter-demo/-/blob/master/README.md?ref_type=heads
* …

fix: remote markdown url validation and suggestions

---

frontend/components/software/edit/mentions/utils.ts

* When entering a DOI, allow for the first forward slash to be URL encoded (`%2F`)
* Sign in, create a software or project page
* When searching anywhere for the DOI `10.1186%2Fs40537-019-0194-3` (or `https://doi.org/10.1186%2Fs40537-019-0194-3`) using regular search or bulk import, a result should be found. The same when using the unescaped DOI `10.1186/s40537-019-0194-3`.
* Try out other DOIs from #808 to see if they still work
Closes #1309
PR Checklist:

fix: allow for escaped slash in DOI

---

docker-compose.yml
frontend/next-env.d.ts
frontend/package-lock.json
frontend/package.json

* Upgrade next js from v14.2.3 to v15.0.1
* Upgrade eslint to v8.57.1 as the "oldest" supported eslint version in next v15
How to test:
*  everything should work :-)
PR Checklist:
*   [ ] Tests

chore: upgrade to next v15.0.1

---

database/100-create-api-views.sql

Closes #1326
* Improve  homepage_counts RPC to use  mentions_by_software RPC for software mentions count
* We count unique combination of mention and software id's. In other words, if multiple software packages (registered in RSD) are referenced from one paper we count this reference multiple times (for each software registered in RSD).
How to test:
* Easier to validate is to start without test data. `docker compose build && docker compose up`
* Login and create 2 software packages and 1 project
* In the first software package in reference papers use this DOI 10.1186/s13321-017-0220-4
* In the second software package in reference papers use this DOI 10.5194/gmd-7-267-2014
* In the project output use this DOI 10.5194/gmd-10-3167-2017
* Let the …

fix: software mentions counts on homepage

---

database/106-project-views.sql
database/109-category-functions.sql
database/113-organisation-views.sql

* Fix the delete functions for projects and organisations to adapt to testimonials and categories
* This also fixes a bug that didn't allow organisations with multiple research units to be deleted
* Sign in as admin, deleting software, projects and organisations should always work without errors
* Create an organisation with multiple research units, deleting the parent should also work (this also deletes the research units)
Closes #1334
PR Checklist:

Fix delete functions

---

authentication/README.md
authentication/pom.xml
authentication/src/main/java/nl/esciencecenter/rsd/authentication/JwtCreator.java
authentication/src/main/java/nl/esciencecenter/rsd/authentication/PostgrestAccount.java
authentication/src/test/java/nl/esciencecenter/rsd/authentication/PostgrestAccountTest.java
docker-compose.yml

* Check the database for admin status when refreshing JWT
* Upgrade some auth dependencies
* To be able to test this, you need your cookies to expire in just slightly longer than 5 minutes (instead of an hour), so edit `JwtCreator.java` and set `ONE_HOUR_IN_MILLISECONDS` to `310_000L`
* Make sure to have `RSD_ENVIRONMENT=dev` in your `.env`
* Sign in, you should be admin
* Run in the database `DELETE FROM admin_account;`; within 10 seconds, you should not be admin anymore
* Run in the database `INSERT INTO admin_account VALUES ('some-uuid');`, where you can find your UUID in your settings; within 10 seconds, you should be admin again
* Don't forget to `git restore .` …

Auth refresh check admin

---

backend-postgrest/Dockerfile
database/014-create-keyword-and-category.sql
database/Dockerfile
docker-compose.yml

* Upgrade Postgres from 15.7 to 15.9
* Upgrade PostgREST from v12.2.2 to v12.2.3
* Add database functions that show all categories of software and projects (including categories that are not assigned directly but are a parent of an assigned category)
* Sign in as admin, create an organisation, add three levels of categories
* Create a project, publish it, add the organiation, add its lowest level category
* On http://localhost/api/v1/category_for_project?select=*,project(title),category(short_name,name), you should see only one entry
* On http://localhost/api/v1/rpc/projects_of_category?select=*,project(title),category(short_name,name) you should see three entries, as the …

1350 category overview database

---

database/005-create-relations-for-software.sql
frontend/components/software/edit/package-managers/EditPackageManagerModal.tsx
frontend/components/software/edit/package-managers/apiPackageManager.ts

* Add ghcr.io as package manager
* Sign in, create a software page, add `https://ghcr.io/research-software-directory/rsd-saas/frontend`, it should be recognised as `Github Container Registry`
Closes #1358
PR Checklist:

1358 GitHub container registry

---

.env.example
frontend/pages/api/fe/auth/azure.ts
frontend/pages/api/fe/auth/helmholtzid.ts
frontend/pages/api/fe/auth/index.ts
frontend/pages/api/fe/auth/orcid.ts
frontend/pages/api/fe/auth/surfconext.ts

* Do an extra null check to prevent crashes when an auth provider is down
* Have LinkedIn auth properly setup in your `.env`
* Simulate LinkedIn being down by adding `120.0.0.1 www.linkedin.com` to `/etc/hosts`
* Visit http://localhost/, because of the line in `/etc/hosts`, wait 10 seconds
* Click on Sign in, the LinkedIn option should not be there
* Remove the line from `/etc/hosts`
* Restart the RSD and refresh the page
* LinkedIn should be back as a signing in option
* (Optional): try this out with other auth providers as well
**Note:** In order to get this fix out, I skipped the "greying out" part I suggested in #1367.
Closes #1367
PR Checklist:

fix: prevent crashes by filtering out null auth providers

---

authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzIdLogin.java

* adds two missing VOs to the list of known Helmholtz VOs
How to test:
* `docker compose build` should build without errors
PR Checklist:
*   [ ] Tests

fix: add missing centres

---

frontend/components/software/AboutPackageManagers.tsx
frontend/components/software/AboutSourceCode.tsx
frontend/components/software/overview/search/SelectRows.tsx

Closes #1375 
Closes #1373
* Add aria label to select number of items on the overview pages
* Made logos of the same size. Note! The logo height is set to 3rem. This is best we can do due to various logo ratios.  
* Remove on hover color on source code logos
How to test:
*  visit software overview page and run Lighthouse audit, accessibility section (check accessiblity) - see image below
*  edit software page, add github as repository and package manager
PR Checklist:
*   [ ] Tests

Select accessibility and logo size

---

README.md
frontend/components/mention/FindMention.tsx
frontend/components/mention/FindMentionSection.tsx
frontend/pages/api/fe/mention/find_by_title.ts
frontend/utils/getCrossref.ts
frontend/utils/getDOI.ts

* When parsing a Crossref mention, check if the title exists
* Show an error message when something is wrong with a mention
* Remove the unused function `getUrlFromDoiOrg`
* Add a link to some lists of DOIs in the README for developers
* Sign in as admin, create a software or project page
* Add as mention `​https://doi.org/10.61686/GOLUA29851`, this should result in an error message concerning its missing title
* Bulk import wasn't changed, this should still result in `Unknown error`
* Check the README
Part of #1384
PR Checklist:

Prevent mention form from hanging forever

---

database/013-create-organisation-table.sql
database/100-create-api-views.sql
database/125-global-search.sql
frontend/components/organisation/apiOrganisations.ts
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/ror/RorData.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/ror/RorId.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/ror/RorPostgrestConnector.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/ror/RorScraper.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/ror/RorIdTest.java

* Add a column in the `organisation` table that stores extra ROR names
* Adapt the ROR scraper to harvest these names
* Adapt `global_search` and `organisations_overview` to use these names
* Fix a bug in `global_search` that didn't convert strings to the same case when doing a substring index lookup
* Sign in, create a software of project page, publish it and add the organisations `Amsterdam University of Applied Sciences` and `Vrije Universiteit Amsterdam`
* Wait for the ROR scraper to run or execute `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.ror.MainRor`
* In the global search bar, search for `VU Amsterdam` and …

Use alternative ROR names

---

database/100-create-api-views.sql
database/104-software-views.sql
docker-compose.yml
frontend/utils/postgrestUrl.ts

Closes #1404
*  Remove unused software filter rpc's. During introduction of remote rsd new aggregated filter rpcs where created and used on software overview page  
* This is BREAKING CHANGE, it should bump rsd to v3. I used `!` and BREAKING CHANGE in the commit.
How to test:
* try software overview page and filter including search
* try other pages
* try remote rsd scraper
PR Checklist:
*   [ ] Tests

Remove unused software filter rpc

---

frontend/components/admin/rsd-contributors/apiRsdContributors.ts
frontend/components/table/EditableCell.tsx

Closes #1409
*   When updating contributor data we convert empty string "" to null. This enables removing existing values. 
How to test:
* `make start` to build solution and create test data
* login as rsd admin and navigate to /admin/rsd-contributors page
* add ORCID to an contributor. The value should be saved
* remove ORCID value from the contributor, this should not produce error. You can also validate patch call passing null value.
* You can also remove other values from the contributor like email or affiliation
* Note! You cannot remove first name and last name because these are required values. If you try it you will get error.
PR Checklist:
*   [ ] Update …

fix: use null instead of empty string value when updating contributor

---

frontend/components/admin/rsd-contributors/AvatarOptions.tsx
frontend/components/admin/rsd-contributors/ContributorsTable.tsx
frontend/components/admin/rsd-contributors/RsdContributorsPage.test.tsx
frontend/components/admin/rsd-contributors/useContributors.tsx

Closes #1410
* Enable removing of avatar image of contributor on rsd contributors admin page
* Enable selection of avatar image when only one avatar image available 
* Do not remove changed avatar from RSD. Note! This will produce "dangling" avatar images in RSD database. We will address this by introducing background services in rsd admin section. New issue will be created for this.
How to test:
* `make start` to build app and generate data
* login as rsd admin and navigate to rsd contributors page of admin section
* select contributor with one image. Confirm you can remove avatar.
* find contributor without avatar which has one avatar option. Confirm you can assign avatar.
* find contributor with avatar and multiple options. Confirm you can remove …

feat: enable removing avatar and enable selection when single image available

---

frontend/components/software/AboutStatement.tsx
frontend/components/software/edit/editSoftwareConfig.tsx
frontend/components/software/edit/information/AutosaveSoftwareMarkdown.tsx

Closes #1422
* Change description title on software page from "What {software_name} can do for you?" to "Description"
* Change description title on software edit page too
How to test:
* `make start` to build solution and generate test data
* navigate to software page and confirm "Description" title
* login and create new software. Confirm on description page the title is "Description"
PR Checklist:
*   [ ] Tests

Change software description title

---

documentation/docs/01-users/05-adding-software.md
documentation/docs/01-users/05-adding-software.md.license
frontend/components/software/edit/mentions/reference-papers/ReferencePapersInfo.tsx

This PR attempts to solve #1204 by adding a definition of reference papers.
* adds a definition of reference paper to the software edit view and documentation
How to test:
* create a new software, go to mentions
* open the documentation and navigate to -> User Manual -> Adding software -> Reference papers
PR Checklist:
*   [ ] Tests

fix: add explanation about reference papers

---

frontend/components/category/CategoriesDialogBody.tsx
frontend/components/category/CategoryList.tsx
frontend/types/TreeNode.test.ts
frontend/types/TreeNode.ts

* When searching categories, we not only search in the leaves (i.e. categories without children), but all nodes
* Sign in as admin, add an organisation
* Create categories for that organisation as in #1421 (enable it for software)
* Create a software page and add the organisation
* When searching for `international` in the category list, the respective node, its parent and children should be visible
Closes #1421
PR Checklist:

feat: better category search

---

documentation/docs/01-users/05-adding-software.md
frontend/components/software/edit/services/ServiceInfoListItem.tsx
frontend/components/software/edit/services/SoftwareRepoServices.tsx
frontend/components/software/edit/services/apiSoftwareServices.tsx
frontend/components/software/edit/services/config.ts
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/BasicRepositoryDataWithHistory.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/CommitsPerWeek.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/GitlabScraper.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/MainCommits.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/PostgrestConnector.java
scrapers/src/test/java/nl/esciencecenter/rsd/scraper/git/CommitsPerWeekTest.java

**This is the successor of #1374**
Fixes #777
* optimise gitlab scrapers so that they do not scrape the entire commit history every time they run
* scraper uses the last timestamp in `commit_history` to query the GitLab APIs
* the commit history could become incorrect if
* if the entire commit history was rewritten
* if the default branch changed
* added delete buttons to reset scraped metadata (commit history, programming languages, repository statistics)
How to test:
* login and create a new software that uses a gitlab repository url, e.g.
```
https://codebase.helmholtz.cloud/research-software-directory/RSD-as-a-service
```
* publish the software entry
* start …

777 optimise gitlab scraper new

---

frontend/components/category/CategoriesDialogBody.tsx
frontend/components/category/CategoryTree.tsx
frontend/components/category/TreeSelect.tsx
frontend/components/software/CategoriesSection.tsx
frontend/components/software/edit/links/AutosaveSoftwareCategories.tsx
frontend/components/software/edit/links/AutosaveSoftwareLicenses.test.tsx
frontend/components/software/edit/links/AutosaveSoftwareLicenses.tsx
frontend/components/software/edit/mentions/reference-papers/ReferencePapersInfo.tsx
frontend/types/TreeNode.test.ts
frontend/types/TreeNode.ts

Closes #1430
* Enable deletion of higher level category item(s) if these are present in the data. The 
How to test:
* create new software entry
* select custom category and confirm it is shown on software page
* now add additional leaf item to category you selected in the admin section of categories
* navigate to software page. Old values are shown. Now go to edit categories page and confirm that delete button is present and you can remove this entry. Note! If you select new item there will be 2 delete buttons because you will need to remove two entries.
PR Checklist:
*   [ ] Tests

fix: enable delete of parent categories after tree is changed

---

CONTRIBUTING.md

I am assuming that a simple typo fix doesn't need test cases, doc updates, etc... hope that's ok!

Fix URL to code of conduct

---

frontend/auth/api/getLoginProviders.tsx
frontend/auth/api/useLoginProviders.tsx
frontend/auth/locationCookie.ts
frontend/components/login/LoginDialog.tsx
frontend/components/login/LoginProviders.tsx
frontend/pages/login/failed.tsx
frontend/pages/login/index.tsx

Closes #1417
Closes #1438 
* create a dedicated login page at pages/login
* refactor login dialog content to be used in both situations
* login page working: 
* if you are already logged in we redirect you to last "saved" RSD page or homepage 
* if one provider we redirect directly to login page of the provider
* if more providers we show the content similar to login modal
* if no providers returned we shown 404 page
How to test:
* `make start` to build and generate some test data (test data is not required)
* set RSD_AUTH_PROVIDERS in env to multiple providers and test both login button and login page. The working of both approaches should produce similair results. You should be able to login/logout and land on the page you left before starting …

feat: create separate login page

---

scrapers/src/main/java/nl/esciencecenter/rsd/scraper/aggregator/RemoteRsdConnector.java

* Use a select list to prevent errors for the remote RSD harvester when extra columns are added to the RPC `software_overview()`
* Sign in as admin, add a remote RSD like https://research-software-directory.org/
* Wait or run `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.aggregator.MainAggregator`
* The remote software should have been added successfully
Closes #1455
PR Checklist:

Fix remote RSD harvester

---

database/004-create-software-table.sql
database/005-create-relations-for-software.sql
database/006-create-project-table.sql
database/011-create-mention-table.sql
frontend/components/mention/config.ts
frontend/components/organisation/settings/general/generalSettingsConfig.ts
frontend/components/projects/edit/information/config.ts
frontend/components/projects/edit/organisations/config.ts
frontend/components/software/edit/editSoftwareConfig.tsx
frontend/components/software/edit/links/config.tsx
frontend/components/software/edit/package-managers/config.ts

Fixes #1442 
* update regex in database tables and patterns for frontend input fields to not allow white spaces within or at the end of URLs
* allow URLs without dots in frontend URL fields for testing purposes (e.g. `http:///localhost`)
How to test:
*  Sign in as admin
*  Edit any URL e.g. repository URL
*  When entering a white space within or at the end of the otherwise valid URL, an error message should appear
Cleanup for production:
When this becomes part of production, existing entries in tables `software`, `repository_url`, `package_manager`, `url_for_project`, `mention` need cleanup first.
PR Checklist:
*   [ ] Increase version …

feat: don't allow white spaces in URLs

---

.env.example
.github/workflows/background_services_tests.yml
background-services/Dockerfile
background-services/README.md
background-services/pom.xml
background-services/src/main/java/nl/esciencecenter/rsd/MainDatabase.java
background-services/src/main/resources/logback.xml
database/000-fill-authenticator-password.sh
database/001-setup-basic-roles.sql
database/005-create-relations-for-software.sql
database/007-create-relations-for-projects.sql
database/020-row-level-security.sql
database/100-create-api-views.sql
database/104-software-views.sql
database/124-aggregated-software-views.sql
deployment/docker-compose.yml
docker-compose.yml
frontend/README.md
frontend/utils/postgrestUrl.test.ts
frontend/utils/postgrestUrl.ts

* Disable Postgres' [JIT](https://www.postgresql.org/docs/15/jit.html) by default (you might have to do that manually on your production instance, which can be done with `ALTER DATABASE "rsd-db" SET JIT = OFF;` followed by `docker compose kill -s SIGUSR1 backend`)
* Add indices on some database columns
* Add a [materialized view](https://www.postgresql.org/docs/15/rules-materializedviews.html) that caches the mention counts for software
* Add a new module called `background-services` that refreshes this materialized view every 5 minutes
* In the software overview, don't select the category filter when no category is selected
* Read the `README.md` of the `background-services` and follow its instructions to set up the env variables
* `docker compose down --volumes && docker compose build …

perf: better performance for certain database queries

---

frontend/components/layout/TabAsLink.tsx
frontend/components/profile/tabs/index.tsx

Closes #1461
* Created TabAsLink component to be used when tab should be a link instead of JS button (default). Created comment about disabling TS and current working of the component
* Applied new component to public Profile page
How to test:
* `make start` to build and created test data
* navigate to software page where random user has a link. 
* confirm that tab is a link and works properly with JS enabled
* disable JS and confirm that link still works
PR Checklist:
*   [ ] Tests

TabAsLink to be used when tab should be a link

---

frontend/components/form/MarkdownInputWithPreview.tsx

Closes #1468
* Remove text area resizing while typing as it does not work properly on FF. The user can make markdown area larger manually, using size icon in the bottom right corner.
How to test:
* `make start` to build and generate some test data
* edit software or project markdown with a large text portion. There should be no "jumps" while editing. 
PR Checklist:
*   [ ] Tests

fix: screen jumps when editing large markdown content

---

frontend/components/AppHeader/ResponsiveMenu.tsx
frontend/components/login/LoginButton.tsx

fix: hide login button when no valid providers
Closes #1474
* fix mobile menu items to be clickable as complete button and mark selected item
* do not show login button when no valid login providers
How to test:
* `make start` to build and generate test data (test data is not required)
* open developer console (F12), select mobile device, the mobile menu will appear. You can click anywhere in the button and the menu should work.
* in your .env file remove all entries from `RSD_AUTH_PROVIDERS` or use invalid values. The login button should not be shown. If you use only one value the login button will forward you directly to login screen of the provider. If there is more than one login provider the modal will appear.
PR Checklist:
*   [ ] Increase …

fix: clickable mobile menu button

---

frontend/auth/api/authHelpers.test.ts
frontend/auth/api/authHelpers.ts

Fixes #1483 
* do not enforce `prompt=login+consent`
I tested login for Surfconext and HelmholtzID, both still work.
How to test:
* `docker compose build --parallel && docker compose up --scale scrapers=0`
* confirm that login via all IdPs works (especially Linkedin, Azure and Orcid)
PR Checklist:
*   [x] Tests

fix: do not enforce login and consent prompt

---

database/125-global-search.sql
database/126-public-persons-overview.sql
docker-compose.yml
documentation/docs/03-rsd-instance/02-configurations.md
frontend/components/GlobalSearchAutocomplete/SearchItemIcon.tsx
frontend/components/GlobalSearchAutocomplete/apiGlobalSearch.ts
frontend/components/GlobalSearchAutocomplete/index.tsx
frontend/components/profile/ProfileSearchPanel.tsx
frontend/components/profile/overview/PersonCard.tsx
frontend/components/profile/overview/PersonListItem.tsx
frontend/components/profile/overview/PersonMetrics.tsx
frontend/components/profile/overview/PersonsGrid.tsx
frontend/components/profile/overview/PersonsList.tsx
frontend/components/profile/overview/apiPersonsOverview.ts
frontend/components/profile/tabs/index.tsx
frontend/components/search/useSearchParams.tsx
frontend/components/software/ContactPersonCard.tsx
frontend/components/software/ContributorsList.tsx
frontend/components/user/settings/profile/ProfileInput.tsx
frontend/components/user/settings/profile/apiUserProfile.ts
frontend/config/UserSettingsContext.tsx
frontend/config/getSettingsServerSide.ts
frontend/config/menuItems.tsx
frontend/config/rsdSettingsReducer.ts
frontend/next.config.ts
frontend/package.json
frontend/pages/persons/[id]/[tab].tsx
frontend/pages/persons/[id]/index.tsx
frontend/pages/persons/index.tsx

Closes #1482
* Persons module added to settings.json
* Persons overview page added (see image 1) with card and list layout. The person metrics, software & project counts, is shown if the module is enabled in settings.json. Persons overview page shows 404 if the module "persons" is not enabled. The order of overview is by affiliation and display name.
* Redirect old profile/{id} route to persons/{id} route
* Person/Profile page, does not shows tabs if only one module of "software/projects" is enabled
How to test:
* `make start` to build and generate random test data. Note! Software/project counts used on person card for random data do not correlate initially. Not sure why.
* Enable persons module by adding "persons" into modules prop of settings.json …

feat: persons overview page

---

database/125-global-search.sql
frontend/components/admin/logs/apiLogs.ts
frontend/components/admin/mentions/MentionsOverview.tsx
frontend/components/admin/organisations/apiOrganisation.tsx
frontend/components/admin/remote-rsd/apiRemoteRsd.ts
frontend/components/admin/rsd-contributors/apiRsdContributors.ts
frontend/components/admin/rsd-info/apiRsdInfo.ts
frontend/components/admin/rsd-users/apiRsdUsers.ts
frontend/components/admin/software-highlights/apiSoftwareHighlights.ts
frontend/components/communities/apiCommunities.ts
frontend/components/news/apiNews.tsx
frontend/components/organisation/apiOrganisations.ts
frontend/components/profile/apiProfile.ts
frontend/components/user/communities/index.tsx
frontend/components/user/organisations/useUserOrganisations.tsx
frontend/components/user/project/useUserProjects.tsx
frontend/components/user/software/useUserSoftware.tsx
frontend/utils/editOrganisation.ts

Closes #1504
* When `or`  and `ilike` search is performed using postgrest syntax and , is used in search term the search query fails due to reserved charter (,). In order to prevent error search term need to be enclosed between quotes ("test,").
How to test:
* `make start` to build the solution and generate test data
* change one software entry title to contain "," and invite yourself to be maintainer
* change one project entry title to contain "," and invite yourself to be maintainer
* change one organisation entry to contain "," and invite yourself to be maintainer
* change one community entry to contain "," and invite yourself to be maintainer
* add "," in your profile name too and make your profile public
* search for software with "," entry on …

fix: postgrest or+ilike error when using , in search term

---

database/026-user-profile.sql
frontend/components/seo/getCommunitiesSitemap.ts
frontend/components/seo/getNewsSitemap.ts
frontend/components/seo/getPersonsSitemap.ts
frontend/pages/robots.txt.tsx
frontend/pages/sitemap/communities.xml.tsx
frontend/pages/sitemap/news.xml.tsx
frontend/pages/sitemap/organisations.xml.tsx
frontend/pages/sitemap/persons.xml.tsx
frontend/pages/sitemap/projects.xml.tsx
frontend/pages/sitemap/software.xml.tsx
frontend/public/data/settings.json

* Based on KIN-RPD repo I came to conclusion that we can improve robots.txt file based on active modules in settings.json   
* This PR implements dynamic writing of robots.txt based on active modules in settings.json
* It also requires "news" to be added into modules list in order to include news in the robots.txt content 
* The persons sitemap required minor change in `public_user_profile` RPC.
How to test:
* `make start` to build and generate test data.
* navigate to http://localhost/robots.txt
* confirm robots.txt lists sitemaps for active modules
```bash
User-agent: *
Disallow: /admin/
Disallow: /auth/
Disallow: /invite/
Disallow: /login/
Disallow: /user/
Sitemap: http://localhost/sitemap/software.xml
Sitemap: …
```

Robots modules

---

e2e/helpers/project.ts
e2e/helpers/utils.ts
frontend/components/communities/tabs/index.tsx
frontend/components/news/item/NavButtons.tsx
frontend/components/organisation/tabs/OrganisationTabs.tsx
frontend/components/projects/edit/EditProjectNav.tsx
frontend/components/software/edit/EditSoftwareNav.tsx
frontend/components/user/settings/nav/index.tsx
frontend/components/user/tabs/UserTabs.tsx

* Add anchor (`<a>`) tags to tabs and buttons
* Check that the following are clickable:
* edit software tabs in sidebar
* edit project tabs in sidebar
* tabs of an organisation
* tabs of a research unit (check that the link is correct)
* tabs of a community
* when viewing a news item, the edit button
* the tabs at "My settings"
* the tabs at the admin interface
closes #1518
PR Checklist:

Use anchor tags on tabs and buttons

---

frontend/components/charts/progress/PeriodProgressBar.tsx
frontend/components/projects/ProjectStatus.tsx
frontend/components/projects/overview/cards/ProjectPeriod.tsx
frontend/utils/getProjects.ts

* Show the progress bar on project cards that have a start date in the future or an end date in the past, when the other date is missing
* Check the projects overview page
* For upcoming projects, the progress bar is always shown (empty), even if the end date is missing
* For finished projects, the progress bar is always shown (full), even if the start date is missing
closes #933
PR Checklist:

Show progress bar when status is known for projects

---

frontend/components/form/ControlledImageInput.tsx
frontend/components/form/ImageDropZone.tsx
frontend/components/form/LogoDropZone.tsx
frontend/components/layout/Logo.tsx
frontend/components/news/edit/AutosaveNewsImage.tsx
frontend/components/organisation/units/ResearchUnitModal.tsx
frontend/components/person/AvatarOptions.tsx
frontend/components/person/AvatarOptionsPerson.tsx
frontend/components/projects/edit/information/AutosaveProjectImage.test.tsx
frontend/components/projects/edit/information/AutosaveProjectImage.tsx
frontend/components/software/edit/information/AutosaveSoftwareLogo.tsx

* Allow to drop images from either your file system or the browser to upload them, reducing the need to download images first
* Try to edit images in all places with drag and drop
* The existing method of clicking to get a file chooser should still work
closes #1387
PR Checklist:

feat: drag and drop images to upload

---

frontend/__tests__/OrganisationsOverview.test.tsx
frontend/components/organisation/overview/OrganisationList.tsx
frontend/pages/communities/index.tsx
frontend/pages/organisations/index.tsx

Closes #1566
* Align organisation layout and functionality with communities overview pages
* User can change page layout between grid and list as on the other pages. The settings is shared with other pages
How to test:
* `make start` to build solution and generate test data
* visit organisation overiew. Change layout and confirm it works
* test search, it should work as previously
* test pagination, it should work as previously
PR Checklist:
*   [ ] Tests

feat: organisation overview as card grid or list view

---

frontend/__tests__/OrganisationsOverview.test.tsx
frontend/components/communities/overview/CommunitiesGrid.tsx
frontend/components/layout/PaginationLink.tsx
frontend/components/news/overview/NewsGrid.tsx
frontend/components/organisation/overview/OrganisationGrid.tsx
frontend/components/projects/overview/cards/ProjectOverviewGrid.tsx
frontend/components/software/overview/SoftwareOverviewContent.tsx
frontend/components/software/overview/cards/SoftwareOverviewGrid.tsx
frontend/components/software/overview/list/OverviewListItem.tsx
frontend/config/UserSettingsContext.tsx
frontend/pages/communities/index.tsx
frontend/pages/news/index.tsx
frontend/pages/organisations/index.tsx
frontend/pages/projects/index.tsx
frontend/pages/software/index.tsx
frontend/pages/spotlights/index.tsx

Closes #1505
* Created PaginationLink component to use as pagination component on all overview pages
* Fixed back/next button active on first and last page that produced "out of range" pages like -1 or max+1 page
* Fixed layout view toggle button. Clicking on same view button produced "null" value
* Applied PaginationLink component to all overview pages: software, highlights, projects, organisations, communities and news overviews.  
* Applied useUserSettings hook to all overview pages to obtain and save preferred view type
* Minor layout fix: the pagination component is kept at the bottom of the page even when few items (1-3) are displayed (on the last page).
How to test:
* `make start` to build app and generate test data. You might need to edit …

fix: pagination previous and next buttons

---

database/002-create-account-table.sql
frontend/components/admin/rsd-invites/CreateRsdInvite.tsx
frontend/components/admin/rsd-invites/apiRsdInvite.ts
frontend/components/admin/rsd-invites/index.tsx
frontend/components/admin/rsd-invites/useRsdInvite.tsx
frontend/components/maintainers/InvitationList.tsx

* Show the ID of account invites
* Allow to add a comment to account invites and show them
* Sign in as admin, go to RSD invites in the admin menu
* Create an invite without comment, the ID should be visible
* Create an invite with a comment, the ID and the comment should be visible
* Check that other types of invites still work properly
closes #1522
closes #1573
PR Checklist:

Show ID and comment for account invites

---

frontend/components/admin/communities/index.tsx
frontend/components/admin/communities/useAdminCommunities.tsx

Fixes #1511 
* after clicking `Save` on the `Add community` modal in the admin view, redirect to the community page of the community that was created
How to test:
* Log into RSD as admin
* In the admin view, create a new community
* You should be redirected to the page of the newly created community after saving
PR Checklist:
*   [ ] Tests

fix: open community page after admin creation

---

documentation/docs/02-API/01-rest-api.md

* add request examples for using API access tokens to the documentation
* use synced tabs to provide examples using different technologies
How to test:
* go to documentation > `API endpoints` > `REST API` > `API Usage via Access Tokens` (or see attached screenshot below)
* review content and formatting of added request examples
PR Checklist:
*   [ ] Tests

docs: add request examples for API access tokens

---

docker-compose.yml
documentation/docs/04-contribute/06-plugin-development.md
documentation/docs/04-contribute/06-plugin-development.md.license
documentation/package.json
frontend/components/software/edit/EditSoftwareNav.tsx
frontend/config/getPlugins.ts
frontend/package.json

* add the ability to append the software slug as query parameter to the link url of the editSoftwareNav plugin slot
* if a plugin adds `{slug}` to the url, NextJS will replace it with the slug of the software that is currently edited
How to test:
* in a plugin (for example the [RSD-plugin-example](https://github.com/research-software-directory/RSD-plugin-example)), add `{slug}` to the [href](https://github.com/research-software-directory/RSD-plugin-example/blob/85a52500f40b2021c0f76a72eea95663b552dcb0/plugin-01/backend/main.py#L43) field, e.g.
```tsx
PluginSlot(
slot="editSoftwareNav",
icon="",
href="http://localhost/plugin/plugin-01/{slug}",
title="Plugin 01 link",
subtitle="",
),
```
* open a software edit view and click on the plugin slot, …

feat: allow to send slug as query parameter in editSoftwareNav plugin slot

---

scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/MainCitations.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/PostgrestCitationRepository.java

* When scraping citations, first update the respective `citations_scraped_at` columns so that if it takes very long, a second process won't scrape citations of the same mention
* Refactor out a method from the main method in `MainCitations`
* Sign in as admin, create a software page
* Add as reference paper `10.1038/nature14539`
* Visit http://localhost/api/v1/mention?select=title,citations_scraped_at, the date should be `null`
* Run the citation scraper: `docker compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.doi.MainCitations`
* This should take very long (unless it was already started in the container before you had the chance), …

Prevent scraping of citations of one mention in parallel

---

e2e/helpers/organisations.ts
frontend/utils/getROR.test.ts
frontend/utils/getROR.ts
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/ror/RorId.java
scrapers/src/main/java/nl/esciencecenter/rsd/scraper/ror/RorScraper.java

* Use v1 of the ROR API, since the default version is [v2 now](https://ror.readme.io/changelog/2025-07-01-sunset-of-version-1), we will later switch to v2
* Sign in
* Add organisations to software, projects and directly as admin, this should work again
part of #1597
PR Checklist:

Use v1 of ROR API

---

database/Dockerfile
docker-compose.yml

* Upgrade Postgres from version 15.13 to 17.6
* Check if everything still works, both anonymously, as an admin and as a regular user
* All tests in the CI/CD pipeline should still pass
**Important**
When this is released, a dump and restore or `pg_upgrade` is needed, see [the documentation](https://www.postgresql.org/docs/current/upgrading.html).
closes #1561
PR Checklist:

chore: upgrade Postgres from 15.13 to 17.6

---

database/106-project-views.sql
frontend/components/user/project-quality/apiProjectQuality.tsx

* Add categories to project metadata overview, it counts assigned incidental leaf nodes (nodes that can have children but of which no child is assigned to the project)
* Sign in as admin, look at the project metadata overview, the final columns should show the category count
* Create a new project, add an organisation with categories to it and assign one category to the project
* When saving the category, you will see that all parents are also saved in the dev tools of your browser (F12, network tab), but in the project metadata overview, it should be counted as one (this should also be the case whan assigning a category that does have children, but of which you don't assign …

Add categories to project metadata overview
