- authentication/src/main/java/nl/esciencecenter/rsd/authentication/Main.java
- data-migration/dockerfile
- data-migration/pom.xml
- data-migration/src/main/java/nl/esciencecenter/rsd/migration/Main.java
- database/001-setup-basic-roles.sql
- database/020-row-level-security.sql
- docker-compose.yml
- frontend/.env.local.example
* Anonymous users can only see published entries
* Admins can see and edit everything
How to test: 
* Copy the extra lines from `frontend/.env.local.example` to `frontend/.env.production.local` and `frontend/.env.local`
* Delete everything: `docker-compose down --volumes`
* Build: `docker-compose build database data-migration`
* Start: `docker-compose up database backend data-migration`
* The data-migration script should after a while finish successfully
* After the data migration is done, the following page should give an empty array: http://localhost:3500/software?select=slug&is_published=eq.false
* Create a jwt at with payload claim `"role": "rsd_admin"` signed with the secret in `frontend/.env.production.local` using HS256
* Make a request to the …
> Admin role

- docker-compose.yml
- nginx/dockerfile
- nginx/nginx.conf
* Make nginx service use a dockerfile
* Automatically install certbot to ease the process of getting https certificates
* Add test domain to nginx confguration
How to test:
* building and running should still work
PR Checklist:
*   [ ] Tests
> Improve nginx

- docker-compose.yml
- frontend/__tests__/__fixtures__/softwareIndexData.js
- frontend/components/software/AboutLanguages.tsx
- frontend/components/software/AboutSection.tsx
- frontend/package.json
- frontend/pages/software/[slug]/index.tsx
- frontend/types/SoftwareTypes.ts
- frontend/utils/getSoftware.ts
Fixes #86
*     Programming languages are shown with pct of codebase
How to test:
* As usual, you should see languages on the right side, if the scaper did its job. Otherwise the whole section will not be shown
PR Checklist:
*   [ ] Tests
> 86 software languages

- data-migration/docker-compose.yml
- data-migration/src/main/java/nl/esciencecenter/rsd/migration/Main.java
* Migrate affiliations of contributors in migration script
How to test:
* This change affects the migration script, so we need to rebuild everything:
* Run the data migration script
* Check any software page to see the affiliations
* Inspect http://localhost/api/v1/contributor?select=family_names,given_names,affiliation to see if the data makes sense
PR Checklist:
*   [ ] Tests
closes #87
> Migrate affiliations of contributors

- CITATION.cff
Fixes #148 
*      Adds a CFF file with metadata about the RSD
How to test:
*      Just read the file ;-)
PR Checklist:
*   [ ] Tests
> Added initial CFF file

- .github/workflows/tests_main.yml
- README.md
Fixes #155  
How to test:
* View header of README.md file to confirm badges. Note! I renamed tests workflow to "all tests" as badge uses the workflow name. I expect that badge name will change after we merge it to master.
PR Checklist:
*   [n/a] Tests
> 155 badges

- database/100-create-api-views.sql
- docker-compose.yml
- frontend/auth/permissions/isMaintainerOfSoftware.ts
- frontend/utils/editContributors.ts
- frontend/utils/editOrganisation.ts
- frontend/utils/getOrganisations.ts
- frontend/utils/getSoftware.ts
* Replace all views with functions, as per #170
* The endpoint calls on the frontend were adapted as well
* Some `WHERE` clauses, which filtered on the `is_published` flag, were removed, since functions do respect row level security
How to test:
* This change affects the database structure, so we need to rebuild everything.
* `docker-compose build database frontend`
* Run the migration script
* Check that everything still works on the frontend, e.g. http://localhost/organisation and on http://localhost/software/xenon check that you see on the top right of the page the mentions and contributors count
Closes #170
PR Checklist:
*   [ ] …
> Replace views with functions

- .vscode/settings.json
Fixes #226 
* Adds code style and environment settings for programming Java in Visual Studio Code
How to test:
* --
PR Checklist:
*   [ ] Tests
> #226 Update Visual Studio Code settings for Java

- frontend/components/layout/AppFooter.tsx
- frontend/pages/index.tsx
Add link to documentation in the footer page
> minor: add link to technical documentation page

- frontend/pages/_document.tsx
It adds HotJar script to allow feedback analytics and recordings
> Add hotjar script for dev env

- database/100-create-api-views.sql
- docker-compose.yml
- frontend/components/projects/edit/organisations/config.ts
- frontend/components/projects/edit/organisations/index.tsx
- frontend/components/projects/edit/organisations/useParticipatingOrganisations.ts
- frontend/components/projects/edit/team/TeamMemberList.tsx
- frontend/components/software/edit/contributors/SoftwareContributorsList.tsx
- frontend/components/software/edit/organisations/FindOrganisation.tsx
- frontend/components/software/edit/organisations/index.tsx
- frontend/package.json
- frontend/pages/software/index.tsx
- frontend/types/Project.ts
- frontend/utils/editOrganisation.ts
- frontend/utils/editProject.ts
- frontend/utils/getSoftware.ts
Closes #254 
* the user is able to add participating organisations in the project
* adding organisations is done using find feature that looks for organisations in RSD and ROR databases
* in addition the user can add completely new organisation
* when adding completely new organisation from ROR or by typing new organisation name and selecting "Add ...", the user is set as primary maintainer
* when adding organisation already present in RSD and when user is maintainer of organisation, the organisation will be added but it will have "waiting for approval" status. The organisations with "waiting for approval" status will not be show on the project view page.
How to test:
* `docker-compose down --volumes`: to remove old instance db
* `docker-compose …
> 254 edit project organisations

- frontend/pages/index.tsx
Fixes #335
As discussed, we want to redirect as soon as possible to new users to the software page
> Add call to action to Landing page

- docker-compose.yml
- frontend/components/AppHeader/index.tsx
- frontend/components/form/Searchbox.tsx
- frontend/components/layout/ContentHeader.tsx
- frontend/components/layout/PageTitle.tsx
- frontend/components/organisation/OrganisationCard.tsx
- frontend/components/organisation/OrganisationGrid.tsx
- frontend/components/organisation/OrganisationTitle.tsx
- frontend/components/organisation/project/index.tsx
- frontend/components/organisation/settings/OrganisationLogo.tsx
- frontend/components/organisation/software/index.tsx
- frontend/components/projects/ProjectCard.tsx
- frontend/components/projects/ProjectDescription.tsx
- frontend/components/projects/RelatedProjectsSection.tsx
- frontend/components/software/AboutSection.tsx
- frontend/components/software/OrganisationsSection.tsx
- frontend/components/software/RelatedSoftwareSection.tsx
- frontend/components/software/TestimonialsSection.tsx
- frontend/package.json
- frontend/pages/index.tsx
- frontend/pages/organisations/index.tsx
- frontend/pages/projects/index.tsx
- frontend/pages/software/[slug]/index.tsx
- frontend/pages/software/index.tsx
- frontend/styles/global.css
Closes #363 
* Card overflow for mobile is fixed
* Search and pagination is centered on small screens
* Other minor alignment improvements made for various screen sizes 
How to test:
* `docker-compose build` to build new frontend
* `docker-compose up` to start RSD
* View pages in various screen sizes. In Chrome we use mobile views. See printscreens
PR Checklist:
*   [ ] Tests
> Improve responsive layout

- data-migration/docker-compose.yml
- data-migration/src/main/java/nl/esciencecenter/rsd/migration/Main.java
- data-migration/src/main/resources/organisation_202207011308.csv
- data-migration/src/main/resources/organisation_202207011308.csv.license
Fixes #358 
* Deduplicate organisations when migrating
How to test:
* Build and run data migration
* Check that there are no duplicate organisations
* Check that some organisations have a ROR id
* Check that for the merged organisations, the relations with software and projects have been merged (compare with the dev vm)
PR Checklist:
*   [ ] Tests
> Deduplicate organisations

- docker-compose.yml
- frontend/components/AppHeader/AddMenu.tsx
- frontend/components/layout/EditButton.tsx
- frontend/components/projects/ProjectStatus.tsx
- frontend/components/projects/ProjectTags.tsx
- frontend/components/software/AboutLanguages.tsx
- frontend/components/software/GetStartedSection.tsx
- frontend/components/software/SoftwareCard.tsx
- frontend/package.json
- frontend/styles/themeDark.js
- frontend/styles/themeDefault.js
Fixes #376 
* fixes mislplaced anchor tag
* edit button tab focus and other styles to be aligned with add button
* hover contrast on citation buttons
* research domain tag background color on project page
* programming language bar(s)-chart
* project progress bar
How to test:
* run and validate
PR Checklist:
*   [ ] Tests
> 376 style hotfixes

- documentation/docs/api.md
> Create database diagram

- frontend/components/form/ControlledTextField.tsx
- frontend/components/form/HelperTextWithCounter.tsx
- frontend/components/projects/edit/maintainers/config.ts
- frontend/components/software/add/addConfig.ts
- frontend/components/software/edit/editSoftwareConfig.tsx
- frontend/components/software/edit/information/SoftwareMarkdown.tsx
- frontend/components/software/edit/information/index.tsx
- frontend/components/user/UserNavItems.tsx
Fixes #411
Fixes #412
* Small textual improvements
How to test:
* Check that the frontend still builds: `docker-compose build frontend`
* Check that the aforementioned issues have been resolved
PR Checklist:
*   [ ] Tests
> chore: improve help texts

- CITATION.cff
Fixes #203
* Update contributors in CFF
PR Checklist:
*   [ ] Tests
> Update citation.cff to include new contributors

- deployment/.gitignore
- docker-compose.yml
- frontend/components/organisation/OrganisationCard.tsx
- frontend/components/projects/edit/editProjectSteps.tsx
- frontend/components/projects/edit/information/FundingOrganisations.tsx
- frontend/components/projects/edit/information/ProjectLinkItem.tsx
- frontend/components/projects/edit/information/config.ts
- frontend/components/projects/edit/information/fundingOrganisationsChanges.ts
- frontend/components/projects/edit/information/index.tsx
- frontend/components/projects/edit/information/projectKeywordsChanges.ts
- frontend/components/projects/edit/information/projectLinkChanges.ts
- frontend/components/projects/edit/information/researchDomainChanges.ts
- frontend/components/projects/edit/information/useProjectToEdit.tsx
- frontend/components/software/edit/editSoftwareSteps.tsx
- frontend/components/software/edit/information/SoftwareKeywords.tsx
- frontend/components/software/edit/information/index.tsx
- frontend/components/software/edit/information/softwareKeywordsChanges.ts
- frontend/package.json
- frontend/pages/login/local.tsx
- frontend/pages/projects/[slug]/edit/index.tsx
- frontend/pages/software/[slug]/edit.tsx
- frontend/types/Organisation.ts
- frontend/types/Project.ts
- frontend/utils/dateFn.test.ts
- frontend/utils/dateFn.ts
- frontend/utils/editOrganisation.ts
- frontend/utils/editProject.ts
- frontend/utils/getROR.ts
Closes #405
Closes #421  
Closes #422 
Closes #428
* See  mentioned issues     
How to test:
* `docker-compose build` to build
* confirm you can add keywords, funding organisations and add/update project urls
PR Checklist:
*   [ ] Tests
> 428 project fixes

- README.md
Fixes #153 
*      Added the OpenSSF best practices badge to the README.md
How to test:
*     Look at the new README.md and see if the badge is there. 
PR Checklist:
*   [ ] Tests
> Added the OpenSSF best practices badge

- .gitignore
- data-generator/.dockerignore
- data-generator/Dockerfile
- data-generator/main.js
- data-generator/package-lock.json
- data-generator/package-lock.json.license
- data-generator/package.json
- data-generator/package.json.license
- docker-compose.yml
* A Node.js script is created that can generate fake data for the RSD. This data can locally be used for developing and testing purposes.
How to test:
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --scale data-generation=1 --scale scrapers=0`
* Visit http://localhost and admire all the fake data
* Check if anything is missing
Closes #473
PR Checklist:
*   [ ] Tests
> Create a fake data generation script

- .env.example
- database/017-create-narcis-table.sql
- deployment/docker-compose.yml
- docker-compose.yml
- nginx/nginx.conf
- scrapers/Dockerfile
- scrapers/jobs.cron
- scrapers/src/main/resources/oaipmh.py
* Adapt the oaipmh scraper from the legacy RSD to the current version
* Scraped data is stored in the database instead of in a file
How to test:
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up`
* Execute the large insert command at the bottom of this post
* Execute the scraper manually (it normally only runs at 1 AM): `docker-compose exec scrapers python3 -u /usr/myjava/oaipmh.py`
* You should see some warnings about not getting an expected redirect
* After every 60 results, the scraper will sleep for about one minute to cope with the rate limits
* No other errors should be reported
* Visit http://localhost/oaipmh/ to see the results
**EDIT:**
* http://localhost/oaipmh/ won't work anymore, …
> 491 add scraper for NARCIS

- database/011-create-organisation-table.sql
- database/100-create-api-views.sql
- docker-compose.yml
- frontend/__tests__/__fixtures__/apiOrganisationsOfSoftware.json
- frontend/__tests__/__fixtures__/apiParticipatingOrganisations.json
- frontend/components/organisation/OrganisationNavItems.tsx
- frontend/components/organisation/units/ResearchUnitModal.tsx
- frontend/components/organisation/units/index.tsx
- frontend/components/projects/ProjectFunding.tsx
- frontend/components/software/ParticipatingOrganisation.tsx
- frontend/package.json
- frontend/pages/software/[slug]/index.tsx
- frontend/types/Organisation.ts
- frontend/types/Project.ts
- frontend/utils/editOrganisation.ts
- frontend/utils/getOrganisations.ts
- frontend/utils/getProjects.ts
- frontend/utils/getSlugFromString.ts
Closes #357
Closes #484 
*  The projects and software attributed to child organisation are also included at the parent organisation   
How to test:
*  `docker-compose down --volumes` to remove old setup
* `docker-compose build` to build solution
* `docker-compose up --scale data-generation=1 --scale scrapers=0`  to start and generate some mocked data
*  login as rsd_admin:
* in your .env file add this value `RSD_ADMIN_EMAIL_LIST=isaacnewton@university-example.org`
* then login as professor3 via SURFConnext
*  Navigate to first organisation and add following research units:
*  Life Sciences - <Company Name>, edit slug to be shorter by removing company name, add logo if you wish 
*  Humanities and Social Sciences - <Company Name>, edit slug to be …
> 357 Show software and projects of research units at parent view

- frontend/components/GlobalSearchAutocomplete/index.tsx
- frontend/components/form/Searchbox.tsx
- frontend/components/organisation/project/index.tsx
- frontend/components/organisation/software/index.tsx
- frontend/components/search/Searchbox.tsx
- frontend/components/user/organisations/index.tsx
- frontend/components/user/project/index.tsx
- frontend/components/user/software/index.tsx
- frontend/pages/organisations/index.tsx
- frontend/pages/projects/index.tsx
- frontend/pages/software/index.tsx
Fixes #536
- This PR changes the placeholder from filtering projects, organisations and software
- Add search icon to the global searchbox
- Fix touch on mobile devices for the global search
PR Checklist:
*   [ ] Tests
> Improve ux serach boxes

- frontend/__tests__/ProjectItem.test.tsx
- frontend/__tests__/SoftwareItem.test.tsx
- frontend/__tests__/__fixtures__/apiContributors.json
- frontend/components/AppHeader/AddMenu.tsx
- frontend/components/AppHeader/index.tsx
- frontend/components/GlobalSearchAutocomplete/index.tsx
- frontend/components/feedback/FeedbackPanelButton.tsx
- frontend/components/filter/FilterPopover.tsx
- frontend/components/keyword/KeywordFilter.tsx
- frontend/components/layout/ContentHeader.tsx
- frontend/components/layout/EditFab.tsx
- frontend/components/layout/EditPageButton.tsx
- frontend/components/layout/TagChipFilter.tsx
- frontend/components/layout/UserMenu.tsx
- frontend/components/layout/ViewPageButton.tsx
- frontend/components/login/LoginButton.tsx
- frontend/components/organisation/OrganisationCard.tsx
- frontend/components/projects/ProjectDescription.tsx
- frontend/components/projects/ProjectInfo.tsx
- frontend/components/projects/ProjectSidebar.tsx
- frontend/components/projects/edit/EditProjectStickyHeader.tsx
- frontend/components/projects/filter/ResearchDomainFilter.tsx
- frontend/components/software/SoftwareIntroSection.tsx
- frontend/components/software/edit/EditSoftwareStickyHeader.tsx
- frontend/pages/projects/[slug]/index.tsx
- frontend/pages/software/[slug]/index.tsx
- frontend/styles/global.css
- frontend/utils/useDisableScrollLock.tsx
Closes #643 
Closes #649
* Edit page button is moved from app header to page itself. On mobile screen with low resolution (<400px) there was no sufficient space for all buttons in app header. Therefore I moved edit button to page itself.
* On edit page
* the title color changed from primary to normal text
* view page button created in the same "style" as the edit page button
* image and caption info are "grouped" in order to be shown/hidden at the same time
* Layout of dropdowns in the app header and filter dropdown layout and behaviour is improved for smaller screens
* Added test for edit button
* Unrelated: added mouse-over text "Officially registered organisation" to checkmark logo on organisation page
How to test:
* `make start`
* login as …
> Edit page button moved from app header to page

- data-generation/Dockerfile
- data-generation/main.js
- data-generation/package-lock.json
- data-generation/package.json
- docker-compose.yml
* Fake names are now usually short and sometimes long
* Upgrade dependencies of the data-generation module
How to test:.
* Most names should be short, some should be long
PR Checklist:
*   [ ] Tests
> Small fake data improvements

- frontend/utils/getORCID.ts
Closes #837
*   ORCID search on name includes fuzzy search "param" in order to better handle names using "special" characters   
How to test:
* login as rsd_admin to be able to edit any software/project or create new software/project
* navigate to contributors page.
* Search for `Gianluca Tirimbo`. It should return 1 entry. Notice use of special character in returned name.
* Same approach is used at team members page
PR Checklist:
*   [ ] Tests
> fix: improve ORCID search with fuzzy option

- frontend/components/software/overview/highlights/HighlightsCarousel.tsx
Fixes #916
*      fix distance cards
How to test:
*
PR Checklist:
*   [ ] Tests
> Calculate distance between left an centered container

- database/100-create-api-views.sql
- database/103-software-views.sql
count_software_countributors -> count_software_contributors
> chore: fix countributors typo

- .github/workflows/sonarcloud.yml
- authentication/pom.xml
- database/sonar-project.properties
- frontend/sonar-project.properties
- scrapers/pom.xml
* Setup GitHub workflow for the authentication, scrapers, frontend and database modules for analysing the code on [sonarcloud.io](https://sonarcloud.io/organizations/research-software-directory/projects)
Related to #915
PR Checklist:
*   [ ] Tests
> Setup SonarCloud integration

- database/100-create-api-views.sql
* Fix an RPC that duplicates an organisation of a primary maintainer as many times as there are normal maintainers
How to test :
* `docker compose down --volumes && docker compose build --parallel && docker-compose up`
* Follow the instructions in #919 and check that the bug doesn't appear anymore
The left join on maintainer_for_organisation duplicates an organisation for each maintainer. For normal maintainers, these duplications are filtered out in the where clause. But for primary maintainers, the where clause always evaluates to true, because of the predicate after the or keyword. The added distinct clause filters them out again.
Closes #919
PR Checklist:
* …
> fix: deduplicate organisations of primary maintainers

- frontend/package.json
- frontend/pages/projects/index.tsx
- frontend/pages/software/index.tsx
- frontend/yarn.lock
Closes #1001
* The user preferred layout, saved in cookie, is applied immediately if exists    
* Next is upgraded to v13.5.3 version (last released version)
How to test:
* `make start` to build app and create test data
* navigate to software overview page, select **list as layout** .
* navigate between software and project overview pages. The list layout should be applied immediately. For reference have a look at [dev](https://research-software.dev/software?order=mention_cnt) where the "jumping layout error" is still present.
PR Checklist:
*   [ ] Tests
> Apply user preferred layout

- docker-compose.yml
- frontend/Dockerfile
Closes #1009
*   fixes fetch error to load setttings.json (see #1009 for more details)
How to test:
* `make start` to build complete solution
* navigate to localhost and load home page
* examine no errors are logged from frontend service `docker compose logs frontend`
PR Checklist:
*   [ ] Tests
> fix: fetch to localhost:3000 to load settings.json

- authentication/README.md
- authentication/src/main/java/nl/esciencecenter/rsd/authentication/Account.java
- authentication/src/main/java/nl/esciencecenter/rsd/authentication/AzureLogin.java
- authentication/src/main/java/nl/esciencecenter/rsd/authentication/Config.java
- authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java
- authentication/src/main/java/nl/esciencecenter/rsd/authentication/Login.java
- authentication/src/main/java/nl/esciencecenter/rsd/authentication/OrcidLogin.java
- authentication/src/main/java/nl/esciencecenter/rsd/authentication/PostgrestAccount.java
- authentication/src/main/java/nl/esciencecenter/rsd/authentication/PostgrestCheckOrcidWhitelistedAccount.java
- authentication/src/main/java/nl/esciencecenter/rsd/authentication/SurfconextLogin.java
- authentication/src/main/java/nl/esciencecenter/rsd/authentication/Utils.java
- authentication/src/test/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLoginTest.java
- authentication/src/test/java/nl/esciencecenter/rsd/authentication/MainTest.java
- authentication/src/test/java/nl/esciencecenter/rsd/authentication/PostgrestCheckOrcidWhitelistedAccountTest.java
- authentication/src/test/java/nl/esciencecenter/rsd/authentication/UtilsTest.java
* Implement some of the suggestions from [SonarCloud](https://sonarcloud.io/summary/overall?id=nl.research-software%3Aauthentication) for the authentication module
* Add to the readme that you should relax your firewall when developing the auth module locally
**Note:** Since this PR is already big enough, I will look at further improvements later.
How to test:
* Login using the various login providers, this should work without errors
Related to #915
PR Checklist:
*   [ ] Tests
> Implement SonarCloud suggestions

- data-generation/Dockerfile
- data-generation/main.js
- data-generation/package-lock.json
- data-generation/package-lock.json.license
- data-generation/package.json
- data-generation/package.json.license
- docker-compose.yml
* Upgrade all dependencies of the data generation module to their newest versions.
* Replace removed and deprecated Faker functions.
* Improved people generation: people with an ORCID have a constant name, email address and picture over all software and projects.
How to test:
* This should run without any errors or warnings from the data generation container.
* Browse various software, project and profile pages. Note that a person with an ORCID has the same name and picture everywhere.
PR Checklist:
*   [ ] Tests
> Data generation upgrade

- .github/workflows/frontend_tests.yml
- docker-compose.yml
- frontend/Dockerfile
- frontend/Dockerfile.dev
- frontend/components/software/ContactPersonCard.tsx
- frontend/components/software/ContributorsSection.tsx
- frontend/package.json
- frontend/pages/profile/[orcid]/[tab].tsx
- frontend/yarn.lock
Closes #1072
* Fix software and project counts on the profile page when using pagination
* Add link to contact person name when profile page is enabled  
How to test:
* navigate to software or project page and find person with the link
* navigate to profile page. Look for the profile pages that have more than 12 items so you can use pagination.
* confirm that software and project counts are consistent while navigating to 2nd,3rd software/project page.
* look for the contact person that has profile enabled (or make one contact with profile page as contact person) and confirm that it has link to profile page on software and project page
PR Checklist: …
> 1072 profile counters

- authentication/README.md
- documentation/docs/03-rsd-instance/01-getting-started.md
- documentation/docs/03-rsd-instance/01-getting-started.md.license
This PR cleans up the previous external PR.
> Docs setup instance

- documentation/docs/03-rsd-instance/02-configurations.md
- documentation/docs/03-rsd-instance/02-configurations.md.license
* Add link to ORCID documentation on addding redirect URLs
How to test:
* Visit http://localhost/documentation/rsd-instance/configurations/#enable-orcid-authentication-and-coupling
Closes #1089
PR Checklist:
> Improve ORCID documentation

- .github/workflows/_cff.yml
- .github/workflows/all_tests.yml
- .github/workflows/authentication_tests.yml
- .github/workflows/database_scan.yml
- .github/workflows/e2e_tests_chrome.yml
- .github/workflows/e2e_tests_firefox.yml
- .github/workflows/e2e_tests_macos.yml
- .github/workflows/e2e_tests_ubuntu.yml
- .github/workflows/frontend_tests.yml
- .github/workflows/release.yml
- .github/workflows/scrapers_tests.yml
> Upgrade download and upload actions

- frontend/components/GlobalSearchAutocomplete/index.tsx
* the global search can always be accessed via the keyboard shortcut Ctrl K or Meta K (Mac)
How to test:
* open any RSD page 
* press `Ctrl + K` or `⌘ + K` and verify that the global search is being focused
* when global search is focused, the hint in the search bar disappears
* with a mac: verify that `⌘ K` is displayed instead of `Ctrl K`
PR Checklist:
*   [ ] Tests
> feat: global search accessible via Ctrl K / Meta K

- .github/workflows/prettier-check-data-generation.yml
- data-generation/.prettierignore
- data-generation/.prettierrc
- data-generation/.prettierrc.license
- data-generation/README.md
- data-generation/images.js
- data-generation/main.js
- data-generation/package-lock.json
- data-generation/package-lock.json.license
- data-generation/package.json
- data-generation/package.json.license
- data-generation/real-data.js
* Configure and apply [Prettier](https://prettier.io/) to the data-generation module
* Add a GitHub workflow that fails when this module is not properly formatted with Prettier
* Add a readme for the data-generation-module
How to test:
* This should run without errors
* Check the result(s) of the workflow(s)
* Check the file changes
* Check the new `README.md`
Related to #1198
Related to #915
PR Checklist:
> Prettier for data generation

- database/124-community-views.sql
- database/999-add-categories.sql.example
- frontend/__tests__/SoftwareEditPage.test.tsx
- frontend/components/communities/software/card/useAdminMenuOptions.tsx
- frontend/components/software/edit/EditSoftwareNav.tsx
- frontend/components/software/edit/communities/CommunityStatusBanner.tsx
- frontend/components/software/edit/communities/FindCommunity.tsx
- frontend/components/software/edit/communities/SoftwareCommunitiesInfo.tsx
- frontend/components/software/edit/communities/SoftwareCommunityList.tsx
- frontend/components/software/edit/communities/SoftwareCommunityListItem.tsx
- frontend/components/software/edit/communities/apiSoftwareCommunities.ts
- frontend/components/software/edit/communities/config.ts
- frontend/components/software/edit/communities/index.tsx
- frontend/components/software/edit/communities/useSoftwareCommunities.tsx
- frontend/components/software/edit/editSoftwarePages.tsx
- frontend/components/software/edit/organisations/index.tsx
Closes #1215 
* The software maintainer can request to join an community
* If the communities module is not enabled in settings.json the communites option is hidden. Note! The menu option is simply hidden but the route is not completely disabled. 
* The communities module is not enabled by default
* The communities can be still created by rsd administrators. The communities page is enabled in the admin section.
How to test:
* `make start` to build and create test data
* confirm that "Communities" menu option **is not present in the header of the page**
* login as rsd-admin ((first user is always promoted to rsd-admin in dev), navigate to edit software section. Confirm that **communities page is not shown**.
* navigate to admin section and confirm …
> feat: add communities to edit software

- frontend/components/GlobalSearchAutocomplete/index.tsx
Closes #1231
* Increase z-index of global search results list
How to test:
* Use global search on homepage, confirm the list is completely visible
PR Checklist:
*   [ ] Tests
> fix: visibility of global search results

- .github/workflows/codemeta_scan_build.yml
- codemeta/README.md
- codemeta/go.mod
Fixes out of date go version since #1263
> chore: update go versions in go.mod, documentation and actions

- database/008-community.sql
- database/100-create-api-views.sql
* When someone is both a primary and regular maintainer of an organisation or a community, don't show them in the list of maintainers twice, by fixing the respective database functions
How to test:
* Create some maintainer invitations for an organisation, accept them on different accounts
* Assign a regular maintaine rto also be a primary maintainer
* The primary maintainer should not be duplicated in the maintainers list
* The primary maintainer should be shown first
* Do the same for communities
Closes #1230
PR Checklist:
> Don't show duplicate maintainers

- database/005-create-relations-for-software.sql
- docker-compose.yml
- frontend/components/software/edit/package-managers/EditPackageManagerModal.tsx
- frontend/components/software/edit/package-managers/PackageManagerItem.tsx
- frontend/components/software/edit/package-managers/__mocks__/apiPackageManager.ts
- frontend/components/software/edit/package-managers/apiPackageManager.ts
- frontend/components/software/edit/package-managers/config.ts
- frontend/components/software/edit/package-managers/index.tsx
- frontend/components/software/edit/package-managers/usePackageManagers.tsx
- frontend/components/software/edit/services/ServiceInfoListItem.tsx
- frontend/package-lock.json
- frontend/package-lock.json.license
- frontend/package.json
Closes #1277
* Rsd admin can edit package manager item. It can: 
* disable service by adding a comment into designated input field. The input is enabled only for the services that are "supported". **The info about "supported services" is kept locally (in an data object) and need to be manually updated.**
* change "detected platform" using a drop-down options. The list of supported providers is kept locally (in same data object) and need to be manually updated. 
* When updating package manager entry only platform and the reasons for disabling are updated
How to test:
* `make start` to build app and create test data
* login as rsd_admin, first user should become rsd_admin automatically if you have correct .env settings
* open first software item and …
> rsd admin can edit package manager item

- README.md
> docs: add a note on Safari for developing the RSD

- .github/workflows/editorconfig-check.yml
> upgrade EditorConfig Checker runner from ubuntu-20.04 to ububtu-22.04

- database/104-software-views.sql
- database/108-community-views.sql
- database/113-organisation-views.sql
Remove unused SQL from code. See #1394 for testing instructions.
> chore: remove unused SQL code

- authentication/pom.xml
- backend-postgrest/Dockerfile
- backend-tests/pom.xml
- database/Dockerfile
- scrapers/pom.xml
* Upgrade Postgres from 15.9 to 15.12 ([release notes](https://www.postgresql.org/docs/release/))
* Upgrade PostgREST from v12.2.3 to v12.2.8 ([release notes](https://github.com/PostgREST/postgrest/releases))
* Upgrade Javalin from 6.3.0 to 6.4.0 ([release notes](https://github.com/javalin/javalin/releases))
* Upgrade Java JWT from 4.4.0 to 4.5.0 ([release notes](https://github.com/auth0/java-jwt/releases))
* Check if everything still works, especially signing in
Closes #1405
PR Checklist:
> 1405 upgrade postgres

- frontend/styles/global.css
Fixes #1451
* remove background color for text in code block
How to test:
```
docker compose down --volumes && docker compose build --parallel && docker compose up --scale scrapers=0
```
* create a new software entry and add a code block in mardkown
* verify it is readable
PR Checklist:
*   [ ] Tests
> fix: correctly display markdown code blocks

- frontend/auth/api/__mocks__/useLoginProviders.tsx
- frontend/auth/api/useLoginProviders.tsx
- frontend/auth/loginProvidersContext.tsx
- frontend/components/home/imperial/MainContentImperialCollege.tsx
- frontend/components/login/LoginButton.tsx
- frontend/pages/_app.tsx
Closes #1497
* Added providers context to _app to share providers list to the rest of the pages. 
* Use new context in useLoginProviders hook to share data
How to test:
* Navigate between all pages and confirm that SignIn button is showed directly on the page load
PR Checklist:
*   [ ] Tests
> fix: SignIn button hidden during page load

- authentication/src/main/java/nl/esciencecenter/rsd/authentication/RsdProviders.java
* Properly check if a provider is disabled first to prevent it from wrongly being returned in the JSON
* Omit `LOCAL` from `RSD_AUTH_PROVIDERS`
* Local accounts should not be shown, the rest should show as you configured
* Also check on http://localhost/auth/providers
* Try around different configurations
PR Checklist:
> Fix RSD providers
